// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/script/script.proto

package go_micro_srv_task_script

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nop) Reset()         { *m = Nop{} }
func (m *Nop) String() string { return proto.CompactTextString(m) }
func (*Nop) ProtoMessage()    {}
func (*Nop) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{0}
}

func (m *Nop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nop.Unmarshal(m, b)
}
func (m *Nop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nop.Marshal(b, m, deterministic)
}
func (m *Nop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nop.Merge(m, src)
}
func (m *Nop) XXX_Size() int {
	return xxx_messageInfo_Nop.Size(m)
}
func (m *Nop) XXX_DiscardUnknown() {
	xxx_messageInfo_Nop.DiscardUnknown(m)
}

var xxx_messageInfo_Nop proto.InternalMessageInfo

type Script struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CancelFunc           string   `protobuf:"bytes,4,opt,name=cancelFunc,proto3" json:"cancelFunc,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Script) Reset()         { *m = Script{} }
func (m *Script) String() string { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()    {}
func (*Script) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{1}
}

func (m *Script) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Script.Unmarshal(m, b)
}
func (m *Script) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Script.Marshal(b, m, deterministic)
}
func (m *Script) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Script.Merge(m, src)
}
func (m *Script) XXX_Size() int {
	return xxx_messageInfo_Script.Size(m)
}
func (m *Script) XXX_DiscardUnknown() {
	xxx_messageInfo_Script.DiscardUnknown(m)
}

var xxx_messageInfo_Script proto.InternalMessageInfo

func (m *Script) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Script) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Script) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Script) GetCancelFunc() string {
	if m != nil {
		return m.CancelFunc
	}
	return ""
}

func (m *Script) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateScript struct {
	Id                   *wrappers.Int32Value  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CancelFunc           *wrappers.StringValue `protobuf:"bytes,4,opt,name=cancelFunc,proto3" json:"cancelFunc,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateScript) Reset()         { *m = UpdateScript{} }
func (m *UpdateScript) String() string { return proto.CompactTextString(m) }
func (*UpdateScript) ProtoMessage()    {}
func (*UpdateScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{2}
}

func (m *UpdateScript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScript.Unmarshal(m, b)
}
func (m *UpdateScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScript.Marshal(b, m, deterministic)
}
func (m *UpdateScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScript.Merge(m, src)
}
func (m *UpdateScript) XXX_Size() int {
	return xxx_messageInfo_UpdateScript.Size(m)
}
func (m *UpdateScript) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScript.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScript proto.InternalMessageInfo

func (m *UpdateScript) GetId() *wrappers.Int32Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateScript) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateScript) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateScript) GetCancelFunc() *wrappers.StringValue {
	if m != nil {
		return m.CancelFunc
	}
	return nil
}

func (m *UpdateScript) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

type UpdateScriptReq struct {
	Id                   uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Update               *UpdateScript `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateScriptReq) Reset()         { *m = UpdateScriptReq{} }
func (m *UpdateScriptReq) String() string { return proto.CompactTextString(m) }
func (*UpdateScriptReq) ProtoMessage()    {}
func (*UpdateScriptReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{3}
}

func (m *UpdateScriptReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScriptReq.Unmarshal(m, b)
}
func (m *UpdateScriptReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScriptReq.Marshal(b, m, deterministic)
}
func (m *UpdateScriptReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScriptReq.Merge(m, src)
}
func (m *UpdateScriptReq) XXX_Size() int {
	return xxx_messageInfo_UpdateScriptReq.Size(m)
}
func (m *UpdateScriptReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScriptReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScriptReq proto.InternalMessageInfo

func (m *UpdateScriptReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateScriptReq) GetUpdate() *UpdateScript {
	if m != nil {
		return m.Update
	}
	return nil
}

type ScriptIndex struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScriptIndex) Reset()         { *m = ScriptIndex{} }
func (m *ScriptIndex) String() string { return proto.CompactTextString(m) }
func (*ScriptIndex) ProtoMessage()    {}
func (*ScriptIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{4}
}

func (m *ScriptIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptIndex.Unmarshal(m, b)
}
func (m *ScriptIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptIndex.Marshal(b, m, deterministic)
}
func (m *ScriptIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptIndex.Merge(m, src)
}
func (m *ScriptIndex) XXX_Size() int {
	return xxx_messageInfo_ScriptIndex.Size(m)
}
func (m *ScriptIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptIndex proto.InternalMessageInfo

func (m *ScriptIndex) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Scripts struct {
	Scripts              []*Script `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	Totalpages           uint32    `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32    `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	Totals               uint32    `protobuf:"varint,4,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Scripts) Reset()         { *m = Scripts{} }
func (m *Scripts) String() string { return proto.CompactTextString(m) }
func (*Scripts) ProtoMessage()    {}
func (*Scripts) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{5}
}

func (m *Scripts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scripts.Unmarshal(m, b)
}
func (m *Scripts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scripts.Marshal(b, m, deterministic)
}
func (m *Scripts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scripts.Merge(m, src)
}
func (m *Scripts) XXX_Size() int {
	return xxx_messageInfo_Scripts.Size(m)
}
func (m *Scripts) XXX_DiscardUnknown() {
	xxx_messageInfo_Scripts.DiscardUnknown(m)
}

var xxx_messageInfo_Scripts proto.InternalMessageInfo

func (m *Scripts) GetScripts() []*Script {
	if m != nil {
		return m.Scripts
	}
	return nil
}

func (m *Scripts) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *Scripts) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

func (m *Scripts) GetTotals() uint32 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type ScriptFilter struct {
	And                  []*ScriptFilter       `protobuf:"bytes,1,rep,name=and,proto3" json:"and,omitempty"`
	Or                   []*ScriptFilter       `protobuf:"bytes,2,rep,name=or,proto3" json:"or,omitempty"`
	Id                   *wrappers.Int32Value  `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	IdIn                 []int32               `protobuf:"varint,4,rep,packed,name=idIn,proto3" json:"idIn,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	NameIn               []string              `protobuf:"bytes,6,rep,name=nameIn,proto3" json:"nameIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ScriptFilter) Reset()         { *m = ScriptFilter{} }
func (m *ScriptFilter) String() string { return proto.CompactTextString(m) }
func (*ScriptFilter) ProtoMessage()    {}
func (*ScriptFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{7}
}

func (m *ScriptFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptFilter.Unmarshal(m, b)
}
func (m *ScriptFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptFilter.Marshal(b, m, deterministic)
}
func (m *ScriptFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptFilter.Merge(m, src)
}
func (m *ScriptFilter) XXX_Size() int {
	return xxx_messageInfo_ScriptFilter.Size(m)
}
func (m *ScriptFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptFilter proto.InternalMessageInfo

func (m *ScriptFilter) GetAnd() []*ScriptFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *ScriptFilter) GetOr() []*ScriptFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *ScriptFilter) GetId() *wrappers.Int32Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ScriptFilter) GetIdIn() []int32 {
	if m != nil {
		return m.IdIn
	}
	return nil
}

func (m *ScriptFilter) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ScriptFilter) GetNameIn() []string {
	if m != nil {
		return m.NameIn
	}
	return nil
}

type Query struct {
	Limit                uint32        `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32        `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32        `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Filter               *ScriptFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_78c9a66419e32ad3, []int{8}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Query) GetFilter() *ScriptFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*Nop)(nil), "go.micro.srv.task.script.Nop")
	proto.RegisterType((*Script)(nil), "go.micro.srv.task.script.Script")
	proto.RegisterType((*UpdateScript)(nil), "go.micro.srv.task.script.UpdateScript")
	proto.RegisterType((*UpdateScriptReq)(nil), "go.micro.srv.task.script.UpdateScriptReq")
	proto.RegisterType((*ScriptIndex)(nil), "go.micro.srv.task.script.ScriptIndex")
	proto.RegisterType((*Scripts)(nil), "go.micro.srv.task.script.Scripts")
	proto.RegisterType((*Response)(nil), "go.micro.srv.task.script.Response")
	proto.RegisterType((*ScriptFilter)(nil), "go.micro.srv.task.script.ScriptFilter")
	proto.RegisterType((*Query)(nil), "go.micro.srv.task.script.Query")
}

func init() { proto.RegisterFile("proto/script/script.proto", fileDescriptor_78c9a66419e32ad3) }

var fileDescriptor_78c9a66419e32ad3 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x76, 0x92, 0x2e, 0x27, 0xcd, 0x0a, 0x62, 0x14, 0x2f, 0x6b, 0x3b, 0xcf, 0xb0, 0x92,
	0x31, 0x70, 0x47, 0x0a, 0x65, 0x8c, 0x51, 0x18, 0x94, 0x96, 0xdc, 0x94, 0xd6, 0xdd, 0x0f, 0xbb,
	0xd8, 0x85, 0x6b, 0x9f, 0x04, 0x33, 0x57, 0x72, 0x25, 0xb9, 0xeb, 0xde, 0x60, 0xb0, 0x47, 0x18,
	0xbb, 0xea, 0x8b, 0x0e, 0x4b, 0x4a, 0xe6, 0x34, 0x04, 0xbb, 0x57, 0xd2, 0xf9, 0xf9, 0x8e, 0xce,
	0xf9, 0xf4, 0x49, 0xf0, 0x34, 0xe7, 0x4c, 0xb2, 0x3d, 0x11, 0xf3, 0x34, 0x97, 0x66, 0x09, 0x94,
	0x8f, 0xb8, 0x53, 0x16, 0x5c, 0xa5, 0x31, 0x67, 0x81, 0xe0, 0x37, 0x81, 0x8c, 0xc4, 0xf7, 0x40,
	0xc7, 0x07, 0x3b, 0x53, 0xc6, 0xa6, 0x19, 0xee, 0xa9, 0xbc, 0xcb, 0x62, 0xb2, 0xf7, 0x83, 0x47,
	0x79, 0x8e, 0x5c, 0x68, 0xa4, 0xdf, 0x06, 0xe7, 0x94, 0xe5, 0xfe, 0x2f, 0x0b, 0x3a, 0x17, 0x0a,
	0x41, 0x1e, 0x83, 0x9d, 0x26, 0xae, 0xe5, 0x59, 0xc3, 0x7e, 0x68, 0xa7, 0x09, 0x21, 0xd0, 0xa2,
	0xd1, 0x15, 0xba, 0xb6, 0x67, 0x0d, 0xbb, 0xa1, 0xda, 0x13, 0x0f, 0x7a, 0x09, 0xea, 0x13, 0x52,
	0x46, 0x5d, 0x47, 0x85, 0xaa, 0x2e, 0xb2, 0x03, 0x10, 0x47, 0x34, 0xc6, 0xec, 0xb8, 0xa0, 0xb1,
	0xdb, 0x52, 0x09, 0x15, 0x0f, 0x71, 0x61, 0x2d, 0x66, 0x54, 0x22, 0x95, 0x6e, 0x5b, 0x05, 0x67,
	0xa6, 0x7f, 0x67, 0xc3, 0xfa, 0xa7, 0x3c, 0x89, 0x24, 0x9a, 0x86, 0x5e, 0xcf, 0x1b, 0xea, 0x8d,
	0x9e, 0x05, 0x7a, 0x9e, 0x60, 0x36, 0x4f, 0x30, 0xa6, 0x72, 0x7f, 0xf4, 0x39, 0xca, 0x0a, 0x54,
	0xdd, 0xbe, 0xa9, 0x74, 0xdb, 0x1b, 0x6d, 0x2d, 0xa5, 0x5f, 0x48, 0x9e, 0xd2, 0xa9, 0xce, 0xd7,
	0xb3, 0x1c, 0x2e, 0xcf, 0x52, 0x07, 0x5c, 0x98, 0xf4, 0xfd, 0xd2, 0xa4, 0x75, 0xf0, 0x2a, 0x0f,
	0x07, 0x8b, 0x3c, 0xd4, 0x41, 0xe7, 0x2c, 0x45, 0xb0, 0x51, 0x25, 0x29, 0xc4, 0xeb, 0xa5, 0x8b,
	0x3b, 0x84, 0x4e, 0xa1, 0x52, 0x0c, 0x19, 0xbb, 0xc1, 0x2a, 0x95, 0x04, 0x0b, 0xa5, 0x0c, 0xca,
	0xdf, 0x86, 0x9e, 0xf6, 0x8c, 0x69, 0x82, 0xb7, 0xf7, 0xcb, 0xfb, 0x7f, 0x2c, 0x58, 0xd3, 0x71,
	0x41, 0xde, 0xc1, 0x9a, 0xae, 0x24, 0x5c, 0xcb, 0x73, 0x86, 0xbd, 0x91, 0xb7, 0xfa, 0x2c, 0x73,
	0xca, 0x0c, 0x50, 0x2a, 0x45, 0x32, 0x19, 0x65, 0x79, 0x34, 0x45, 0xa1, 0x5a, 0xed, 0x87, 0x15,
	0x0f, 0xd9, 0x82, 0x6e, 0x5c, 0x70, 0xae, 0xc3, 0x8e, 0x0a, 0xff, 0x77, 0x90, 0x4d, 0xe8, 0xa8,
	0x5c, 0xa1, 0x98, 0xef, 0x87, 0xc6, 0xf2, 0x01, 0x1e, 0x85, 0x28, 0x72, 0x46, 0x05, 0xfa, 0xbf,
	0x6d, 0x58, 0xd7, 0xa7, 0x1e, 0xa7, 0x99, 0x44, 0x4e, 0xde, 0x82, 0x13, 0xd1, 0xc4, 0xb4, 0xba,
	0x5b, 0xd7, 0xaa, 0x06, 0x85, 0x25, 0x84, 0x1c, 0x80, 0xcd, 0xb8, 0x6b, 0x3f, 0x08, 0x68, 0x33,
	0x6e, 0x34, 0xec, 0x34, 0xd3, 0x30, 0x81, 0x56, 0x9a, 0x8c, 0xa9, 0xdb, 0xf2, 0x9c, 0x61, 0x3b,
	0x54, 0xfb, 0xb9, 0xae, 0xdb, 0x8d, 0x75, 0xbd, 0x09, 0x9d, 0x72, 0x1d, 0x53, 0xb7, 0xe3, 0x39,
	0xc3, 0x6e, 0x68, 0x2c, 0xff, 0xce, 0x82, 0xf6, 0x79, 0x81, 0xfc, 0x27, 0x79, 0x02, 0xed, 0x2c,
	0xbd, 0x4a, 0xa5, 0xb9, 0x54, 0x6d, 0x94, 0x38, 0x36, 0x99, 0x08, 0x94, 0xe6, 0x2e, 0x8c, 0x55,
	0x76, 0x55, 0x52, 0x6e, 0xae, 0x40, 0xed, 0xcb, 0x57, 0x9c, 0x23, 0x3f, 0x2b, 0xdd, 0x9a, 0xfe,
	0x99, 0x59, 0x8a, 0x6f, 0xa2, 0xc6, 0x37, 0x1d, 0x37, 0x25, 0xcb, 0xa0, 0x46, 0x7f, 0x5b, 0xd0,
	0xd7, 0x81, 0x0b, 0xe4, 0x37, 0x69, 0x8c, 0xe4, 0x1c, 0xba, 0x1f, 0x92, 0xc4, 0xfc, 0x09, 0xb5,
	0xfa, 0x1a, 0xf8, 0xab, 0x33, 0x66, 0xc2, 0x20, 0x5f, 0x61, 0xfd, 0x08, 0x33, 0x9c, 0xff, 0x34,
	0x2f, 0xeb, 0xaa, 0xaa, 0x97, 0xd0, 0xa8, 0xf4, 0xb7, 0x7b, 0x9f, 0xd8, 0xab, 0x86, 0x8f, 0x0f,
	0xaf, 0x1b, 0x95, 0xff, 0x08, 0xdd, 0x13, 0x94, 0x0f, 0x6b, 0xbb, 0x96, 0x33, 0x72, 0x06, 0x30,
	0xaf, 0x2a, 0xc8, 0xf3, 0xd5, 0xf9, 0x4a, 0x3f, 0x83, 0x17, 0x75, 0x05, 0x05, 0xf9, 0x02, 0x1b,
	0x27, 0x28, 0x4f, 0xf1, 0xd6, 0x54, 0x1d, 0x1f, 0x91, 0xed, 0xd5, 0xa8, 0x53, 0x96, 0x0f, 0x9a,
	0x0d, 0x73, 0xd9, 0x51, 0xca, 0xdf, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x42, 0x49, 0x19, 0x77,
	0x15, 0x07, 0x00, 0x00,
}
