// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/station/station.proto

package go_micro_srv_station

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphqlQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlQuery) Reset()         { *m = GraphqlQuery{} }
func (m *GraphqlQuery) String() string { return proto.CompactTextString(m) }
func (*GraphqlQuery) ProtoMessage()    {}
func (*GraphqlQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{0}
}

func (m *GraphqlQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlQuery.Unmarshal(m, b)
}
func (m *GraphqlQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlQuery.Marshal(b, m, deterministic)
}
func (m *GraphqlQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlQuery.Merge(m, src)
}
func (m *GraphqlQuery) XXX_Size() int {
	return xxx_messageInfo_GraphqlQuery.Size(m)
}
func (m *GraphqlQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlQuery proto.InternalMessageInfo

func (m *GraphqlQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GraphqlStations struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlStations) Reset()         { *m = GraphqlStations{} }
func (m *GraphqlStations) String() string { return proto.CompactTextString(m) }
func (*GraphqlStations) ProtoMessage()    {}
func (*GraphqlStations) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{1}
}

func (m *GraphqlStations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlStations.Unmarshal(m, b)
}
func (m *GraphqlStations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlStations.Marshal(b, m, deterministic)
}
func (m *GraphqlStations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlStations.Merge(m, src)
}
func (m *GraphqlStations) XXX_Size() int {
	return xxx_messageInfo_GraphqlStations.Size(m)
}
func (m *GraphqlStations) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlStations.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlStations proto.InternalMessageInfo

func (m *GraphqlStations) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type IdRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{2}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Query struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type StationResponse struct {
	StationID            uint32   `protobuf:"varint,1,opt,name=stationID,proto3" json:"stationID,omitempty"`
	PointID              uint32   `protobuf:"varint,2,opt,name=pointID,proto3" json:"pointID,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SysModes             uint32   `protobuf:"varint,4,opt,name=sysModes,proto3" json:"sysModes,omitempty"`
	CarrierTypes         uint32   `protobuf:"varint,5,opt,name=carrierTypes,proto3" json:"carrierTypes,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	StationName          string   `protobuf:"bytes,7,opt,name=stationName,proto3" json:"stationName,omitempty"`
	X                    uint32   `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
	Angle                uint32   `protobuf:"varint,10,opt,name=angle,proto3" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationResponse) Reset()         { *m = StationResponse{} }
func (m *StationResponse) String() string { return proto.CompactTextString(m) }
func (*StationResponse) ProtoMessage()    {}
func (*StationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{4}
}

func (m *StationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationResponse.Unmarshal(m, b)
}
func (m *StationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationResponse.Marshal(b, m, deterministic)
}
func (m *StationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationResponse.Merge(m, src)
}
func (m *StationResponse) XXX_Size() int {
	return xxx_messageInfo_StationResponse.Size(m)
}
func (m *StationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StationResponse proto.InternalMessageInfo

func (m *StationResponse) GetStationID() uint32 {
	if m != nil {
		return m.StationID
	}
	return 0
}

func (m *StationResponse) GetPointID() uint32 {
	if m != nil {
		return m.PointID
	}
	return 0
}

func (m *StationResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StationResponse) GetSysModes() uint32 {
	if m != nil {
		return m.SysModes
	}
	return 0
}

func (m *StationResponse) GetCarrierTypes() uint32 {
	if m != nil {
		return m.CarrierTypes
	}
	return 0
}

func (m *StationResponse) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *StationResponse) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *StationResponse) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *StationResponse) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *StationResponse) GetAngle() uint32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

type StationsResponse struct {
	Stations             []*StationResponse `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	Totalpages           uint32             `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	TotalNumber          uint32             `protobuf:"varint,3,opt,name=totalNumber,proto3" json:"totalNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StationsResponse) Reset()         { *m = StationsResponse{} }
func (m *StationsResponse) String() string { return proto.CompactTextString(m) }
func (*StationsResponse) ProtoMessage()    {}
func (*StationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89d528e10793bd7b, []int{5}
}

func (m *StationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationsResponse.Unmarshal(m, b)
}
func (m *StationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationsResponse.Marshal(b, m, deterministic)
}
func (m *StationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationsResponse.Merge(m, src)
}
func (m *StationsResponse) XXX_Size() int {
	return xxx_messageInfo_StationsResponse.Size(m)
}
func (m *StationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StationsResponse proto.InternalMessageInfo

func (m *StationsResponse) GetStations() []*StationResponse {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *StationsResponse) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *StationsResponse) GetTotalNumber() uint32 {
	if m != nil {
		return m.TotalNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GraphqlQuery)(nil), "go.micro.srv.station.GraphqlQuery")
	proto.RegisterType((*GraphqlStations)(nil), "go.micro.srv.station.GraphqlStations")
	proto.RegisterType((*IdRequest)(nil), "go.micro.srv.station.IdRequest")
	proto.RegisterType((*Query)(nil), "go.micro.srv.station.Query")
	proto.RegisterType((*StationResponse)(nil), "go.micro.srv.station.StationResponse")
	proto.RegisterType((*StationsResponse)(nil), "go.micro.srv.station.StationsResponse")
}

func init() { proto.RegisterFile("proto/station/station.proto", fileDescriptor_89d528e10793bd7b) }

var fileDescriptor_89d528e10793bd7b = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x6e, 0xf3, 0xe3, 0x49, 0xda, 0xa2, 0x51, 0x85, 0x56, 0x09, 0x82, 0x68, 0x05, 0xa8,
	0x2f, 0x18, 0xa9, 0x88, 0x03, 0x80, 0x22, 0x55, 0x7e, 0xa0, 0x02, 0xd3, 0x27, 0xde, 0xb6, 0xf1,
	0x28, 0x58, 0xc4, 0x5e, 0x67, 0x77, 0x83, 0xe2, 0x23, 0x70, 0x02, 0x0e, 0xc3, 0xe5, 0x90, 0xc7,
	0x1b, 0x27, 0xa0, 0x08, 0xf5, 0xc9, 0xf3, 0x7d, 0x33, 0xf3, 0xcd, 0xdf, 0x1a, 0xa6, 0x95, 0xd1,
	0x4e, 0xbf, 0xb1, 0x4e, 0xb9, 0x5c, 0x97, 0xbb, 0x6f, 0xcc, 0x2c, 0x5e, 0x2e, 0x75, 0x5c, 0xe4,
	0x0b, 0xa3, 0x63, 0x6b, 0x7e, 0xc4, 0xde, 0x27, 0x5f, 0xc0, 0xf8, 0xc6, 0xa8, 0xea, 0xdb, 0x7a,
	0xf5, 0x79, 0x43, 0xa6, 0xc6, 0x4b, 0xe8, 0xad, 0x1b, 0x43, 0x04, 0xb3, 0xe0, 0x2a, 0x4a, 0x5b,
	0x20, 0x5f, 0xc3, 0x85, 0x8f, 0xfa, 0xd2, 0xe6, 0x59, 0x9c, 0xc0, 0xd0, 0x90, 0xad, 0x74, 0x69,
	0xc9, 0xc7, 0x76, 0x58, 0x4e, 0x21, 0x4a, 0xb2, 0x94, 0xd6, 0x1b, 0xb2, 0x0e, 0xcf, 0x21, 0xcc,
	0x33, 0x0e, 0x39, 0x4b, 0xc3, 0x3c, 0x93, 0xef, 0xa0, 0xd7, 0x96, 0x42, 0x38, 0xad, 0xd4, 0x92,
	0xbc, 0x8b, 0x6d, 0x14, 0x30, 0xa8, 0xc8, 0x7c, 0x6a, 0xe8, 0x90, 0xe9, 0x1d, 0x94, 0x3f, 0x43,
	0xb8, 0xf0, 0xc5, 0x53, 0x5f, 0x07, 0x9f, 0x42, 0xe4, 0xe7, 0x48, 0xe6, 0x5e, 0x66, 0x4f, 0xb0,
	0x96, 0xce, 0x4b, 0x97, 0xcc, 0x3b, 0xad, 0x16, 0x36, 0x95, 0x5d, 0x5d, 0x91, 0x38, 0xe1, 0xbe,
	0xd9, 0x6e, 0xe6, 0xb1, 0xb5, 0xfd, 0xa8, 0x33, 0xb2, 0xe2, 0x94, 0xc3, 0x3b, 0x8c, 0x12, 0xc6,
	0x0b, 0x65, 0x4c, 0x4e, 0xe6, 0xae, 0xae, 0xc8, 0x8a, 0x1e, 0xfb, 0xff, 0xe2, 0xf0, 0x09, 0xf4,
	0x0d, 0x15, 0xca, 0x7c, 0x17, 0x7d, 0x56, 0xf5, 0x08, 0x67, 0x30, 0xf2, 0x2d, 0xdd, 0xaa, 0x82,
	0xc4, 0x80, 0x9d, 0x87, 0x14, 0x8e, 0x21, 0xd8, 0x8a, 0x21, 0x4b, 0x06, 0xdb, 0x06, 0xd5, 0x22,
	0x6a, 0x11, 0x9f, 0x43, 0x95, 0xcb, 0x15, 0x09, 0x60, 0xa6, 0x05, 0xf2, 0x57, 0x00, 0x8f, 0x77,
	0x87, 0xe8, 0x96, 0xf1, 0x1e, 0x86, 0x5e, 0xd5, 0x8a, 0x60, 0x76, 0x72, 0x35, 0xba, 0x7e, 0x19,
	0x1f, 0x3b, 0x79, 0xfc, 0xcf, 0x16, 0xd3, 0x2e, 0x0d, 0x9f, 0x01, 0x38, 0xed, 0xd4, 0xaa, 0x39,
	0x85, 0xf5, 0x4b, 0x3b, 0x60, 0x9a, 0x59, 0x18, 0xdd, 0x6e, 0x8a, 0x7b, 0x32, 0xbc, 0xbe, 0xb3,
	0xf4, 0x90, 0xba, 0xfe, 0x1d, 0xc0, 0xc0, 0xeb, 0xe3, 0x57, 0x38, 0xbf, 0x21, 0xe7, 0xd1, 0x87,
	0x3a, 0x99, 0xe3, 0xf3, 0xe3, 0x0d, 0x75, 0x6f, 0x65, 0xf2, 0xb0, 0x8e, 0xe5, 0x23, 0xbc, 0x83,
	0xd1, 0x5e, 0xdb, 0xe2, 0xf4, 0x78, 0x1e, 0xbf, 0xb3, 0xc9, 0xab, 0xff, 0x8a, 0xda, 0xbd, 0xea,
	0x7d, 0x9f, 0xff, 0x94, 0xb7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xf2, 0x46, 0x42, 0x48,
	0x03, 0x00, 0x00,
}
