// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/area/area.proto

package go_micro_srv_area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AreaType struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaType) Reset()         { *m = AreaType{} }
func (m *AreaType) String() string { return proto.CompactTextString(m) }
func (*AreaType) ProtoMessage()    {}
func (*AreaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{0}
}

func (m *AreaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaType.Unmarshal(m, b)
}
func (m *AreaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaType.Marshal(b, m, deterministic)
}
func (m *AreaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaType.Merge(m, src)
}
func (m *AreaType) XXX_Size() int {
	return xxx_messageInfo_AreaType.Size(m)
}
func (m *AreaType) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaType.DiscardUnknown(m)
}

var xxx_messageInfo_AreaType proto.InternalMessageInfo

func (m *AreaType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AreaType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AreaTypes struct {
	AreaTypes            []*AreaType `protobuf:"bytes,1,rep,name=areaTypes,proto3" json:"areaTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AreaTypes) Reset()         { *m = AreaTypes{} }
func (m *AreaTypes) String() string { return proto.CompactTextString(m) }
func (*AreaTypes) ProtoMessage()    {}
func (*AreaTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{1}
}

func (m *AreaTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaTypes.Unmarshal(m, b)
}
func (m *AreaTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaTypes.Marshal(b, m, deterministic)
}
func (m *AreaTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaTypes.Merge(m, src)
}
func (m *AreaTypes) XXX_Size() int {
	return xxx_messageInfo_AreaTypes.Size(m)
}
func (m *AreaTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaTypes.DiscardUnknown(m)
}

var xxx_messageInfo_AreaTypes proto.InternalMessageInfo

func (m *AreaTypes) GetAreaTypes() []*AreaType {
	if m != nil {
		return m.AreaTypes
	}
	return nil
}

type Area struct {
	// 区域ID
	Id int32 `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	// 父级区域ID
	ParentAreaID int32 `protobuf:"varint,21,opt,name=parentAreaID,proto3" json:"parentAreaID,omitempty"`
	// 区域类型
	Type *AreaType `protobuf:"bytes,22,opt,name=type,proto3" json:"type,omitempty"`
	//区域的货位列表，待仔细考虑
	Racklots []int32 `protobuf:"varint,23,rep,packed,name=racklots,proto3" json:"racklots,omitempty"`
	// 区域允许的货位类型
	RacklotType int32 `protobuf:"varint,24,opt,name=racklotType,proto3" json:"racklotType,omitempty"`
	// 区域任务容量
	OrderCapacity int32 `protobuf:"varint,25,opt,name=orderCapacity,proto3" json:"orderCapacity,omitempty"`
	//是否按区域入库
	AreaInbound bool `protobuf:"varint,26,opt,name=areaInbound,proto3" json:"areaInbound,omitempty"`
	//是否按区域出库
	AreaOutbound bool `protobuf:"varint,27,opt,name=areaOutbound,proto3" json:"areaOutbound,omitempty"`
	//是否允许入库
	Inbound bool `protobuf:"varint,28,opt,name=inbound,proto3" json:"inbound,omitempty"`
	//是否允许出库
	Outbound bool `protobuf:"varint,29,opt,name=outbound,proto3" json:"outbound,omitempty"`
	// 所属仓库Ikey
	WarehouseIkey string `protobuf:"bytes,30,opt,name=warehouseIkey,proto3" json:"warehouseIkey,omitempty"`
	//区域任务数量
	OrderNum             uint32   `protobuf:"varint,31,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	OrderIDs             []uint32 `protobuf:"varint,32,rep,packed,name=orderIDs,proto3" json:"orderIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{2}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area) GetParentAreaID() int32 {
	if m != nil {
		return m.ParentAreaID
	}
	return 0
}

func (m *Area) GetType() *AreaType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Area) GetRacklots() []int32 {
	if m != nil {
		return m.Racklots
	}
	return nil
}

func (m *Area) GetRacklotType() int32 {
	if m != nil {
		return m.RacklotType
	}
	return 0
}

func (m *Area) GetOrderCapacity() int32 {
	if m != nil {
		return m.OrderCapacity
	}
	return 0
}

func (m *Area) GetAreaInbound() bool {
	if m != nil {
		return m.AreaInbound
	}
	return false
}

func (m *Area) GetAreaOutbound() bool {
	if m != nil {
		return m.AreaOutbound
	}
	return false
}

func (m *Area) GetInbound() bool {
	if m != nil {
		return m.Inbound
	}
	return false
}

func (m *Area) GetOutbound() bool {
	if m != nil {
		return m.Outbound
	}
	return false
}

func (m *Area) GetWarehouseIkey() string {
	if m != nil {
		return m.WarehouseIkey
	}
	return ""
}

func (m *Area) GetOrderNum() uint32 {
	if m != nil {
		return m.OrderNum
	}
	return 0
}

func (m *Area) GetOrderIDs() []uint32 {
	if m != nil {
		return m.OrderIDs
	}
	return nil
}

type UpdateAreaReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Area                 *Area    `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAreaReq) Reset()         { *m = UpdateAreaReq{} }
func (m *UpdateAreaReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAreaReq) ProtoMessage()    {}
func (*UpdateAreaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{3}
}

func (m *UpdateAreaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAreaReq.Unmarshal(m, b)
}
func (m *UpdateAreaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAreaReq.Marshal(b, m, deterministic)
}
func (m *UpdateAreaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAreaReq.Merge(m, src)
}
func (m *UpdateAreaReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAreaReq.Size(m)
}
func (m *UpdateAreaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAreaReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAreaReq proto.InternalMessageInfo

func (m *UpdateAreaReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAreaReq) GetArea() *Area {
	if m != nil {
		return m.Area
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type AreaIDReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaIDReq) Reset()         { *m = AreaIDReq{} }
func (m *AreaIDReq) String() string { return proto.CompactTextString(m) }
func (*AreaIDReq) ProtoMessage()    {}
func (*AreaIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{5}
}

func (m *AreaIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaIDReq.Unmarshal(m, b)
}
func (m *AreaIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaIDReq.Marshal(b, m, deterministic)
}
func (m *AreaIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaIDReq.Merge(m, src)
}
func (m *AreaIDReq) XXX_Size() int {
	return xxx_messageInfo_AreaIDReq.Size(m)
}
func (m *AreaIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_AreaIDReq proto.InternalMessageInfo

func (m *AreaIDReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Query struct {
	Limit                uint32       `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32       `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32       `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	QueryString          string       `protobuf:"bytes,5,opt,name=queryString,proto3" json:"queryString,omitempty"`
	QueryParams          []*Parameter `protobuf:"bytes,6,rep,name=queryParams,proto3" json:"queryParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{6}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Query) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *Query) GetQueryParams() []*Parameter {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

type GraphqlQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlQuery) Reset()         { *m = GraphqlQuery{} }
func (m *GraphqlQuery) String() string { return proto.CompactTextString(m) }
func (*GraphqlQuery) ProtoMessage()    {}
func (*GraphqlQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{7}
}

func (m *GraphqlQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlQuery.Unmarshal(m, b)
}
func (m *GraphqlQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlQuery.Marshal(b, m, deterministic)
}
func (m *GraphqlQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlQuery.Merge(m, src)
}
func (m *GraphqlQuery) XXX_Size() int {
	return xxx_messageInfo_GraphqlQuery.Size(m)
}
func (m *GraphqlQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlQuery proto.InternalMessageInfo

func (m *GraphqlQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GraphqlAreas struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlAreas) Reset()         { *m = GraphqlAreas{} }
func (m *GraphqlAreas) String() string { return proto.CompactTextString(m) }
func (*GraphqlAreas) ProtoMessage()    {}
func (*GraphqlAreas) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{8}
}

func (m *GraphqlAreas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlAreas.Unmarshal(m, b)
}
func (m *GraphqlAreas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlAreas.Marshal(b, m, deterministic)
}
func (m *GraphqlAreas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlAreas.Merge(m, src)
}
func (m *GraphqlAreas) XXX_Size() int {
	return xxx_messageInfo_GraphqlAreas.Size(m)
}
func (m *GraphqlAreas) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlAreas.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlAreas proto.InternalMessageInfo

func (m *GraphqlAreas) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type Areas struct {
	Areas                []*Area  `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	Totalpages           uint32   `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32   `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	Totals               uint32   `protobuf:"varint,4,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Areas) Reset()         { *m = Areas{} }
func (m *Areas) String() string { return proto.CompactTextString(m) }
func (*Areas) ProtoMessage()    {}
func (*Areas) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{9}
}

func (m *Areas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Areas.Unmarshal(m, b)
}
func (m *Areas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Areas.Marshal(b, m, deterministic)
}
func (m *Areas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Areas.Merge(m, src)
}
func (m *Areas) XXX_Size() int {
	return xxx_messageInfo_Areas.Size(m)
}
func (m *Areas) XXX_DiscardUnknown() {
	xxx_messageInfo_Areas.DiscardUnknown(m)
}

var xxx_messageInfo_Areas proto.InternalMessageInfo

func (m *Areas) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

func (m *Areas) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *Areas) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

func (m *Areas) GetTotals() uint32 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type TypeReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeReq) Reset()         { *m = TypeReq{} }
func (m *TypeReq) String() string { return proto.CompactTextString(m) }
func (*TypeReq) ProtoMessage()    {}
func (*TypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{10}
}

func (m *TypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeReq.Unmarshal(m, b)
}
func (m *TypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeReq.Marshal(b, m, deterministic)
}
func (m *TypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeReq.Merge(m, src)
}
func (m *TypeReq) XXX_Size() int {
	return xxx_messageInfo_TypeReq.Size(m)
}
func (m *TypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TypeReq proto.InternalMessageInfo

func (m *TypeReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TypeReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TypeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FlagReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Flag                 bool     `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagReq) Reset()         { *m = FlagReq{} }
func (m *FlagReq) String() string { return proto.CompactTextString(m) }
func (*FlagReq) ProtoMessage()    {}
func (*FlagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{11}
}

func (m *FlagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagReq.Unmarshal(m, b)
}
func (m *FlagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagReq.Marshal(b, m, deterministic)
}
func (m *FlagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagReq.Merge(m, src)
}
func (m *FlagReq) XXX_Size() int {
	return xxx_messageInfo_FlagReq.Size(m)
}
func (m *FlagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagReq.DiscardUnknown(m)
}

var xxx_messageInfo_FlagReq proto.InternalMessageInfo

func (m *FlagReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FlagReq) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type CapReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cap                  int32    `protobuf:"varint,2,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapReq) Reset()         { *m = CapReq{} }
func (m *CapReq) String() string { return proto.CompactTextString(m) }
func (*CapReq) ProtoMessage()    {}
func (*CapReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{12}
}

func (m *CapReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapReq.Unmarshal(m, b)
}
func (m *CapReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapReq.Marshal(b, m, deterministic)
}
func (m *CapReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapReq.Merge(m, src)
}
func (m *CapReq) XXX_Size() int {
	return xxx_messageInfo_CapReq.Size(m)
}
func (m *CapReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CapReq.DiscardUnknown(m)
}

var xxx_messageInfo_CapReq proto.InternalMessageInfo

func (m *CapReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CapReq) GetCap() int32 {
	if m != nil {
		return m.Cap
	}
	return 0
}

type RacklotsReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Racklots             []int32  `protobuf:"varint,2,rep,packed,name=racklots,proto3" json:"racklots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RacklotsReq) Reset()         { *m = RacklotsReq{} }
func (m *RacklotsReq) String() string { return proto.CompactTextString(m) }
func (*RacklotsReq) ProtoMessage()    {}
func (*RacklotsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{13}
}

func (m *RacklotsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RacklotsReq.Unmarshal(m, b)
}
func (m *RacklotsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RacklotsReq.Marshal(b, m, deterministic)
}
func (m *RacklotsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RacklotsReq.Merge(m, src)
}
func (m *RacklotsReq) XXX_Size() int {
	return xxx_messageInfo_RacklotsReq.Size(m)
}
func (m *RacklotsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RacklotsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RacklotsReq proto.InternalMessageInfo

func (m *RacklotsReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RacklotsReq) GetRacklots() []int32 {
	if m != nil {
		return m.Racklots
	}
	return nil
}

type TaskReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskID               uint32   `protobuf:"varint,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReq) Reset()         { *m = TaskReq{} }
func (m *TaskReq) String() string { return proto.CompactTextString(m) }
func (*TaskReq) ProtoMessage()    {}
func (*TaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{14}
}

func (m *TaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReq.Unmarshal(m, b)
}
func (m *TaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReq.Marshal(b, m, deterministic)
}
func (m *TaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReq.Merge(m, src)
}
func (m *TaskReq) XXX_Size() int {
	return xxx_messageInfo_TaskReq.Size(m)
}
func (m *TaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReq proto.InternalMessageInfo

func (m *TaskReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskReq) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

type Parameter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{15}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AreaType)(nil), "go.micro.srv.area.AreaType")
	proto.RegisterType((*AreaTypes)(nil), "go.micro.srv.area.AreaTypes")
	proto.RegisterType((*Area)(nil), "go.micro.srv.area.Area")
	proto.RegisterType((*UpdateAreaReq)(nil), "go.micro.srv.area.UpdateAreaReq")
	proto.RegisterType((*Response)(nil), "go.micro.srv.area.Response")
	proto.RegisterType((*AreaIDReq)(nil), "go.micro.srv.area.AreaIDReq")
	proto.RegisterType((*Query)(nil), "go.micro.srv.area.Query")
	proto.RegisterType((*GraphqlQuery)(nil), "go.micro.srv.area.GraphqlQuery")
	proto.RegisterType((*GraphqlAreas)(nil), "go.micro.srv.area.GraphqlAreas")
	proto.RegisterType((*Areas)(nil), "go.micro.srv.area.Areas")
	proto.RegisterType((*TypeReq)(nil), "go.micro.srv.area.TypeReq")
	proto.RegisterType((*FlagReq)(nil), "go.micro.srv.area.FlagReq")
	proto.RegisterType((*CapReq)(nil), "go.micro.srv.area.CapReq")
	proto.RegisterType((*RacklotsReq)(nil), "go.micro.srv.area.RacklotsReq")
	proto.RegisterType((*TaskReq)(nil), "go.micro.srv.area.TaskReq")
	proto.RegisterType((*Parameter)(nil), "go.micro.srv.area.Parameter")
}

func init() { proto.RegisterFile("proto/area/area.proto", fileDescriptor_ce7e3eb842cc36cb) }

var fileDescriptor_ce7e3eb842cc36cb = []byte{
	// 948 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0x87, 0xff, 0xc5, 0xf6, 0x29, 0x0e, 0x5a, 0xa2, 0x7f, 0x18, 0x27, 0x4b, 0x05, 0xa2, 0x0f,
	0x46, 0x87, 0xba, 0x58, 0xfa, 0xd4, 0x97, 0x0e, 0x4e, 0xd4, 0x78, 0xee, 0x86, 0x25, 0x53, 0xda,
	0xe7, 0x81, 0xb1, 0x19, 0x57, 0x88, 0x2c, 0x29, 0x24, 0x9d, 0xc1, 0xdf, 0x61, 0x5f, 0x64, 0x9f,
	0x63, 0xc0, 0x3e, 0xd7, 0xc0, 0x13, 0x25, 0xcb, 0xa8, 0x6c, 0x0f, 0x73, 0x5f, 0x02, 0xde, 0xdd,
	0x8f, 0x3f, 0x1e, 0x7f, 0xbc, 0x3b, 0x2b, 0xf0, 0x34, 0x91, 0xb1, 0x8e, 0xdf, 0x70, 0x29, 0x38,
	0xfe, 0xe9, 0xa3, 0x4d, 0x1e, 0x4f, 0xe3, 0xfe, 0x2c, 0x18, 0xcb, 0xb8, 0xaf, 0xe4, 0x43, 0xdf,
	0x04, 0xd8, 0x15, 0xb4, 0x06, 0x52, 0xf0, 0x4f, 0x8b, 0x44, 0x90, 0x03, 0xa8, 0x06, 0x13, 0x5a,
	0x71, 0x2b, 0xbd, 0x86, 0x5f, 0x0d, 0x26, 0x84, 0x40, 0x3d, 0xe2, 0x33, 0x41, 0xab, 0x6e, 0xa5,
	0xd7, 0xf6, 0x71, 0x4d, 0x5c, 0x70, 0x26, 0x42, 0x8d, 0x65, 0x90, 0xe8, 0x20, 0x8e, 0x68, 0x0d,
	0x43, 0x45, 0x17, 0xbb, 0x80, 0x76, 0xc6, 0xa8, 0xc8, 0x3b, 0x68, 0xf3, 0xcc, 0xa0, 0x15, 0xb7,
	0xd6, 0x73, 0x4e, 0x8f, 0xfa, 0x5f, 0x65, 0xd1, 0xcf, 0x36, 0xf8, 0x4b, 0x34, 0xfb, 0xab, 0x06,
	0x75, 0xe3, 0xb7, 0x69, 0x3d, 0xc9, 0xd3, 0x62, 0xb0, 0x9f, 0x70, 0x29, 0x22, 0x6d, 0xa2, 0x23,
	0x8f, 0x3e, 0xc5, 0xc8, 0x8a, 0x8f, 0xbc, 0x81, 0xba, 0x5e, 0x24, 0x82, 0x3e, 0x73, 0x2b, 0xdb,
	0x8e, 0x44, 0x20, 0xe9, 0x42, 0x4b, 0xf2, 0xf1, 0x5d, 0x18, 0x6b, 0x45, 0x9f, 0xbb, 0xb5, 0x5e,
	0xc3, 0xcf, 0x6d, 0x73, 0x67, 0xbb, 0x36, 0x1b, 0x28, 0xc5, 0xf3, 0x8a, 0x2e, 0xf2, 0x12, 0x3a,
	0xb1, 0x9c, 0x08, 0x79, 0xce, 0x13, 0x3e, 0x0e, 0xf4, 0x82, 0x1e, 0x22, 0x66, 0xd5, 0x69, 0x78,
	0xcc, 0xd1, 0xa3, 0xe8, 0x26, 0x9e, 0x47, 0x13, 0xda, 0x75, 0x2b, 0xbd, 0x96, 0x5f, 0x74, 0x99,
	0xab, 0x19, 0xf3, 0x72, 0xae, 0x53, 0xc8, 0x11, 0x42, 0x56, 0x7c, 0x84, 0x42, 0x33, 0xb0, 0x0c,
	0xc7, 0x18, 0xce, 0x4c, 0x73, 0x87, 0x38, 0xdb, 0xf9, 0x1d, 0x86, 0x72, 0xdb, 0x64, 0xf8, 0x07,
	0x97, 0xe2, 0x4b, 0x3c, 0x57, 0x62, 0x74, 0x27, 0x16, 0xf4, 0x04, 0x5f, 0x6e, 0xd5, 0x89, 0x0c,
	0x26, 0xe5, 0x5f, 0xe7, 0x33, 0xfa, 0xc2, 0xad, 0xf4, 0x3a, 0x7e, 0x6e, 0xe7, 0xb1, 0x91, 0xa7,
	0xa8, 0xeb, 0xd6, 0xf2, 0xd8, 0xc8, 0x53, 0xec, 0x17, 0xe8, 0x7c, 0x4e, 0x26, 0x5c, 0x0b, 0xa3,
	0xaa, 0x2f, 0xee, 0xbf, 0x2a, 0xa5, 0xef, 0xa1, 0x6e, 0x2e, 0x81, 0xa5, 0xe4, 0x9c, 0x3e, 0x5f,
	0xf3, 0x1e, 0x3e, 0x82, 0x18, 0x40, 0xcb, 0x17, 0x2a, 0x89, 0x23, 0x25, 0xd8, 0x51, 0x5a, 0x4d,
	0x23, 0xaf, 0x84, 0x95, 0xfd, 0x53, 0x81, 0xc6, 0x6f, 0x73, 0x21, 0x17, 0xe4, 0x09, 0x34, 0xc2,
	0x60, 0x16, 0x68, 0x0c, 0x76, 0xfc, 0xd4, 0x20, 0xcf, 0x60, 0x2f, 0xbe, 0xbd, 0x55, 0x42, 0xe3,
	0xb9, 0x1d, 0xdf, 0x5a, 0xa6, 0xb0, 0x13, 0x3e, 0x15, 0x58, 0xbd, 0x1d, 0x1f, 0xd7, 0xe4, 0x10,
	0x5a, 0x89, 0x90, 0xbf, 0xa3, 0xbf, 0x8e, 0xfe, 0x66, 0x22, 0xe4, 0x95, 0x09, 0xb9, 0xe0, 0xdc,
	0x9b, 0x53, 0xae, 0xb5, 0x0c, 0xa2, 0x29, 0x6d, 0xa4, 0x35, 0x5f, 0x70, 0x91, 0xf7, 0x16, 0x71,
	0xc5, 0x25, 0x9f, 0x29, 0xba, 0x87, 0x85, 0x7e, 0x5c, 0x72, 0x4b, 0x04, 0x08, 0x2d, 0xa4, 0x5f,
	0xdc, 0xc0, 0x5e, 0xc2, 0xfe, 0x50, 0xf2, 0xe4, 0xcb, 0x7d, 0x98, 0x5f, 0x07, 0xc3, 0x78, 0x9d,
	0xb6, 0x9f, 0x1a, 0xec, 0x55, 0x8e, 0x32, 0x92, 0x28, 0xac, 0x59, 0xab, 0x93, 0x05, 0xe6, 0x36,
	0xfb, 0xb3, 0x02, 0x8d, 0x14, 0xf5, 0x1a, 0x1a, 0xe6, 0xe8, 0xac, 0xfd, 0xd6, 0x6a, 0x9f, 0xa2,
	0xc8, 0x09, 0x80, 0x8e, 0x35, 0x0f, 0x8d, 0x10, 0xca, 0xea, 0x56, 0xf0, 0x90, 0x63, 0x68, 0x8f,
	0xe7, 0x52, 0xa6, 0xe1, 0x54, 0xc0, 0xa5, 0xc3, 0x28, 0x8e, 0x58, 0x65, 0x35, 0xb4, 0x16, 0x1b,
	0x40, 0x13, 0x9b, 0xad, 0xa4, 0x34, 0x88, 0x6d, 0xd5, 0x2a, 0x7a, 0xd2, 0x6e, 0xcc, 0x26, 0x4f,
	0x6d, 0x39, 0x79, 0xd8, 0x6b, 0x68, 0x5e, 0x84, 0x7c, 0xba, 0x86, 0xe2, 0x36, 0xe4, 0x53, 0xa4,
	0x68, 0xf9, 0xb8, 0x66, 0xaf, 0x60, 0xef, 0x9c, 0x27, 0x65, 0xe8, 0x47, 0x50, 0x1b, 0xf3, 0xc4,
	0x9e, 0x67, 0x96, 0xec, 0x1d, 0x38, 0xbe, 0x6d, 0xf6, 0xb2, 0x0d, 0xc5, 0xd9, 0x50, 0x5d, 0x9d,
	0x0d, 0xec, 0x07, 0x68, 0x7e, 0xe2, 0xea, 0xae, 0x6c, 0x9b, 0xd1, 0x82, 0xab, 0xbb, 0x91, 0x97,
	0x55, 0x5f, 0x6a, 0xb1, 0xb7, 0xd0, 0xce, 0xcb, 0xc0, 0x24, 0x63, 0xba, 0x31, 0x7d, 0x3e, 0xb3,
	0x34, 0x6f, 0xff, 0xc0, 0xc3, 0x79, 0x36, 0x76, 0x53, 0xe3, 0xf4, 0xef, 0x7d, 0x70, 0xcc, 0x33,
	0x5d, 0x0b, 0xf9, 0x10, 0x8c, 0x05, 0x19, 0x82, 0x33, 0x98, 0x4c, 0xf2, 0xd1, 0xbd, 0x69, 0xc2,
	0x75, 0xcb, 0x82, 0x59, 0x83, 0x91, 0x8f, 0x70, 0xb0, 0x6c, 0xdd, 0xdd, 0xb9, 0x3c, 0x11, 0x8a,
	0x6f, 0xc2, 0xf5, 0x01, 0x9c, 0xa1, 0xd0, 0x39, 0x11, 0x2d, 0xc1, 0x62, 0xaf, 0x74, 0x8f, 0x37,
	0x1c, 0xa1, 0xc8, 0x8f, 0xd0, 0xb4, 0x3a, 0x91, 0x75, 0x95, 0xbf, 0x39, 0x8f, 0x9f, 0x01, 0x96,
	0xfa, 0x10, 0xb7, 0x04, 0xba, 0x32, 0xf9, 0x36, 0x93, 0x0d, 0x01, 0x96, 0x02, 0x91, 0x75, 0x99,
	0xe3, 0xb0, 0xdb, 0x4c, 0x74, 0x0e, 0x30, 0x14, 0xfa, 0x32, 0xfa, 0x2f, 0x44, 0xeb, 0xee, 0x4d,
	0xde, 0x43, 0xcb, 0x4a, 0xac, 0x36, 0xe8, 0x4b, 0xd7, 0x6c, 0x57, 0xc4, 0x83, 0x83, 0x6c, 0xff,
	0xd9, 0x62, 0xcb, 0x2b, 0xad, 0x67, 0xf9, 0x0c, 0x8f, 0x97, 0x2c, 0x76, 0xbe, 0x91, 0x17, 0x25,
	0xf0, 0xe2, 0x84, 0xec, 0x6e, 0x00, 0xa4, 0xb4, 0x1f, 0xb1, 0x41, 0xb2, 0xb6, 0x26, 0x27, 0x65,
	0x6a, 0x2e, 0x7b, 0x7e, 0xb3, 0xda, 0x17, 0xe0, 0x5c, 0x17, 0x6a, 0xb1, 0x5b, 0x82, 0xb5, 0xd3,
	0x6d, 0x5b, 0x7f, 0x3c, 0xba, 0x16, 0xfa, 0x72, 0xe5, 0xa3, 0xe0, 0xb0, 0x64, 0x43, 0x3a, 0xb8,
	0xb6, 0xe6, 0x34, 0x28, 0x7c, 0x39, 0x94, 0xe5, 0x64, 0xc7, 0xe5, 0xb6, 0x92, 0xdc, 0x1f, 0x14,
	0x3f, 0x2f, 0xfe, 0x37, 0xd1, 0x19, 0x34, 0x77, 0x4e, 0xe6, 0x1c, 0x5a, 0xbb, 0x27, 0xf2, 0x13,
	0x38, 0x5e, 0xa0, 0xf8, 0x4d, 0xb8, 0x73, 0x97, 0x0d, 0x01, 0x3e, 0x44, 0xdf, 0x82, 0xe8, 0x0c,
	0xa7, 0x90, 0xf9, 0xa1, 0x28, 0x2f, 0x9e, 0xf4, 0x17, 0x64, 0x2b, 0x87, 0x27, 0xc2, 0x9d, 0x38,
	0x6e, 0xf6, 0xf0, 0xff, 0x80, 0xb7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x8d, 0xbb, 0x82,
	0x20, 0x0c, 0x00, 0x00,
}
