// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/area/area.proto

package go_micro_srv_area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AreaType struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Properties           string   `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaType) Reset()         { *m = AreaType{} }
func (m *AreaType) String() string { return proto.CompactTextString(m) }
func (*AreaType) ProtoMessage()    {}
func (*AreaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{0}
}

func (m *AreaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaType.Unmarshal(m, b)
}
func (m *AreaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaType.Marshal(b, m, deterministic)
}
func (m *AreaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaType.Merge(m, src)
}
func (m *AreaType) XXX_Size() int {
	return xxx_messageInfo_AreaType.Size(m)
}
func (m *AreaType) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaType.DiscardUnknown(m)
}

var xxx_messageInfo_AreaType proto.InternalMessageInfo

func (m *AreaType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AreaType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AreaType) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

type UpdateAreaType struct {
	Id                   *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Properties           string                `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateAreaType) Reset()         { *m = UpdateAreaType{} }
func (m *UpdateAreaType) String() string { return proto.CompactTextString(m) }
func (*UpdateAreaType) ProtoMessage()    {}
func (*UpdateAreaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{1}
}

func (m *UpdateAreaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAreaType.Unmarshal(m, b)
}
func (m *UpdateAreaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAreaType.Marshal(b, m, deterministic)
}
func (m *UpdateAreaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAreaType.Merge(m, src)
}
func (m *UpdateAreaType) XXX_Size() int {
	return xxx_messageInfo_UpdateAreaType.Size(m)
}
func (m *UpdateAreaType) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAreaType.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAreaType proto.InternalMessageInfo

func (m *UpdateAreaType) GetId() *wrappers.UInt32Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateAreaType) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateAreaType) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateAreaType) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

type AreaTypes struct {
	AreaTypes            []*AreaType `protobuf:"bytes,1,rep,name=areaTypes,proto3" json:"areaTypes,omitempty"`
	Totalpages           uint32      `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32      `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	Totals               uint32      `protobuf:"varint,4,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AreaTypes) Reset()         { *m = AreaTypes{} }
func (m *AreaTypes) String() string { return proto.CompactTextString(m) }
func (*AreaTypes) ProtoMessage()    {}
func (*AreaTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{2}
}

func (m *AreaTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaTypes.Unmarshal(m, b)
}
func (m *AreaTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaTypes.Marshal(b, m, deterministic)
}
func (m *AreaTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaTypes.Merge(m, src)
}
func (m *AreaTypes) XXX_Size() int {
	return xxx_messageInfo_AreaTypes.Size(m)
}
func (m *AreaTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaTypes.DiscardUnknown(m)
}

var xxx_messageInfo_AreaTypes proto.InternalMessageInfo

func (m *AreaTypes) GetAreaTypes() []*AreaType {
	if m != nil {
		return m.AreaTypes
	}
	return nil
}

func (m *AreaTypes) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *AreaTypes) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

func (m *AreaTypes) GetTotals() uint32 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type Area struct {
	// 区域ID
	Id uint32 `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	// 父级区域ID
	ParentAreaID uint32 `protobuf:"varint,21,opt,name=parentAreaID,proto3" json:"parentAreaID,omitempty"`
	// 区域类型
	Type *AreaType `protobuf:"bytes,22,opt,name=type,proto3" json:"type,omitempty"`
	//区域的货位列表，待仔细考虑
	Racklots []uint32 `protobuf:"varint,23,rep,packed,name=racklots,proto3" json:"racklots,omitempty"`
	// 区域任务容量
	OrderCapacity uint32 `protobuf:"varint,25,opt,name=orderCapacity,proto3" json:"orderCapacity,omitempty"`
	//是否允许入库
	IsInbound bool `protobuf:"varint,28,opt,name=isInbound,proto3" json:"isInbound,omitempty"`
	//是否允许出库
	IsOutbound bool `protobuf:"varint,29,opt,name=isOutbound,proto3" json:"isOutbound,omitempty"`
	IsValid    bool `protobuf:"varint,32,opt,name=isValid,proto3" json:"isValid,omitempty"`
	// 子级区域ID
	ChildAreaIDs         []uint32 `protobuf:"varint,27,rep,packed,name=childAreaIDs,proto3" json:"childAreaIDs,omitempty"`
	Properties           string   `protobuf:"bytes,31,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{3}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area) GetParentAreaID() uint32 {
	if m != nil {
		return m.ParentAreaID
	}
	return 0
}

func (m *Area) GetType() *AreaType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Area) GetRacklots() []uint32 {
	if m != nil {
		return m.Racklots
	}
	return nil
}

func (m *Area) GetOrderCapacity() uint32 {
	if m != nil {
		return m.OrderCapacity
	}
	return 0
}

func (m *Area) GetIsInbound() bool {
	if m != nil {
		return m.IsInbound
	}
	return false
}

func (m *Area) GetIsOutbound() bool {
	if m != nil {
		return m.IsOutbound
	}
	return false
}

func (m *Area) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *Area) GetChildAreaIDs() []uint32 {
	if m != nil {
		return m.ChildAreaIDs
	}
	return nil
}

func (m *Area) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

type UpdateArea struct {
	// 区域任务容量
	Id *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 区域任务容量
	OrderCapacity *wrappers.UInt32Value `protobuf:"bytes,25,opt,name=orderCapacity,proto3" json:"orderCapacity,omitempty"`
	//是否有效
	IsValid *wrappers.BoolValue `protobuf:"bytes,27,opt,name=isValid,proto3" json:"isValid,omitempty"`
	//是否允许入库
	IsInbound *wrappers.BoolValue `protobuf:"bytes,28,opt,name=isInbound,proto3" json:"isInbound,omitempty"`
	//是否允许出库
	IsOutbound *wrappers.BoolValue `protobuf:"bytes,29,opt,name=isOutbound,proto3" json:"isOutbound,omitempty"`
	// 父区域
	ParentAreaID *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=parentAreaID,proto3" json:"parentAreaID,omitempty"`
	//区域的货位列表，待仔细考虑
	Racklots             []uint32 `protobuf:"varint,23,rep,packed,name=racklots,proto3" json:"racklots,omitempty"`
	Properties           string   `protobuf:"bytes,31,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArea) Reset()         { *m = UpdateArea{} }
func (m *UpdateArea) String() string { return proto.CompactTextString(m) }
func (*UpdateArea) ProtoMessage()    {}
func (*UpdateArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{4}
}

func (m *UpdateArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArea.Unmarshal(m, b)
}
func (m *UpdateArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArea.Marshal(b, m, deterministic)
}
func (m *UpdateArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArea.Merge(m, src)
}
func (m *UpdateArea) XXX_Size() int {
	return xxx_messageInfo_UpdateArea.Size(m)
}
func (m *UpdateArea) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArea.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArea proto.InternalMessageInfo

func (m *UpdateArea) GetId() *wrappers.UInt32Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateArea) GetOrderCapacity() *wrappers.UInt32Value {
	if m != nil {
		return m.OrderCapacity
	}
	return nil
}

func (m *UpdateArea) GetIsValid() *wrappers.BoolValue {
	if m != nil {
		return m.IsValid
	}
	return nil
}

func (m *UpdateArea) GetIsInbound() *wrappers.BoolValue {
	if m != nil {
		return m.IsInbound
	}
	return nil
}

func (m *UpdateArea) GetIsOutbound() *wrappers.BoolValue {
	if m != nil {
		return m.IsOutbound
	}
	return nil
}

func (m *UpdateArea) GetParentAreaID() *wrappers.UInt32Value {
	if m != nil {
		return m.ParentAreaID
	}
	return nil
}

func (m *UpdateArea) GetRacklots() []uint32 {
	if m != nil {
		return m.Racklots
	}
	return nil
}

func (m *UpdateArea) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

type UpdateAreaReq struct {
	Id                   uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Area                 *UpdateArea `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAreaReq) Reset()         { *m = UpdateAreaReq{} }
func (m *UpdateAreaReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAreaReq) ProtoMessage()    {}
func (*UpdateAreaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{5}
}

func (m *UpdateAreaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAreaReq.Unmarshal(m, b)
}
func (m *UpdateAreaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAreaReq.Marshal(b, m, deterministic)
}
func (m *UpdateAreaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAreaReq.Merge(m, src)
}
func (m *UpdateAreaReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAreaReq.Size(m)
}
func (m *UpdateAreaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAreaReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAreaReq proto.InternalMessageInfo

func (m *UpdateAreaReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAreaReq) GetArea() *UpdateArea {
	if m != nil {
		return m.Area
	}
	return nil
}

type UpdateAreaTypeReq struct {
	Id                   uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Area                 *UpdateAreaType `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAreaTypeReq) Reset()         { *m = UpdateAreaTypeReq{} }
func (m *UpdateAreaTypeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAreaTypeReq) ProtoMessage()    {}
func (*UpdateAreaTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{6}
}

func (m *UpdateAreaTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAreaTypeReq.Unmarshal(m, b)
}
func (m *UpdateAreaTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAreaTypeReq.Marshal(b, m, deterministic)
}
func (m *UpdateAreaTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAreaTypeReq.Merge(m, src)
}
func (m *UpdateAreaTypeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAreaTypeReq.Size(m)
}
func (m *UpdateAreaTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAreaTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAreaTypeReq proto.InternalMessageInfo

func (m *UpdateAreaTypeReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAreaTypeReq) GetArea() *UpdateAreaType {
	if m != nil {
		return m.Area
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type AreaIDReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaIDReq) Reset()         { *m = AreaIDReq{} }
func (m *AreaIDReq) String() string { return proto.CompactTextString(m) }
func (*AreaIDReq) ProtoMessage()    {}
func (*AreaIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{8}
}

func (m *AreaIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaIDReq.Unmarshal(m, b)
}
func (m *AreaIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaIDReq.Marshal(b, m, deterministic)
}
func (m *AreaIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaIDReq.Merge(m, src)
}
func (m *AreaIDReq) XXX_Size() int {
	return xxx_messageInfo_AreaIDReq.Size(m)
}
func (m *AreaIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_AreaIDReq proto.InternalMessageInfo

func (m *AreaIDReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AreaFilter struct {
	And                  []*AreaFilter         `protobuf:"bytes,1,rep,name=and,proto3" json:"and,omitempty"`
	Or                   []*AreaFilter         `protobuf:"bytes,2,rep,name=or,proto3" json:"or,omitempty"`
	IdIn                 []uint32              `protobuf:"varint,3,rep,packed,name=idIn,proto3" json:"idIn,omitempty"`
	ChildAreaIDIn        []uint32              `protobuf:"varint,4,rep,packed,name=childAreaIDIn,proto3" json:"childAreaIDIn,omitempty"`
	RacklotIDIn          []uint32              `protobuf:"varint,5,rep,packed,name=racklotIDIn,proto3" json:"racklotIDIn,omitempty"`
	IsInbound            *wrappers.BoolValue   `protobuf:"bytes,6,opt,name=isInbound,proto3" json:"isInbound,omitempty"`
	IsOutbound           *wrappers.BoolValue   `protobuf:"bytes,7,opt,name=isOutbound,proto3" json:"isOutbound,omitempty"`
	IsValid              *wrappers.BoolValue   `protobuf:"bytes,8,opt,name=isValid,proto3" json:"isValid,omitempty"`
	ParentAreaID         *wrappers.UInt32Value `protobuf:"bytes,9,opt,name=parentAreaID,proto3" json:"parentAreaID,omitempty"`
	TypeFilter           *AreaTypeFilter       `protobuf:"bytes,11,opt,name=typeFilter,proto3" json:"typeFilter,omitempty"`
	PropertiesFilter     *AreaPropertiesFilter `protobuf:"bytes,12,opt,name=propertiesFilter,proto3" json:"propertiesFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AreaFilter) Reset()         { *m = AreaFilter{} }
func (m *AreaFilter) String() string { return proto.CompactTextString(m) }
func (*AreaFilter) ProtoMessage()    {}
func (*AreaFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{9}
}

func (m *AreaFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaFilter.Unmarshal(m, b)
}
func (m *AreaFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaFilter.Marshal(b, m, deterministic)
}
func (m *AreaFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaFilter.Merge(m, src)
}
func (m *AreaFilter) XXX_Size() int {
	return xxx_messageInfo_AreaFilter.Size(m)
}
func (m *AreaFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AreaFilter proto.InternalMessageInfo

func (m *AreaFilter) GetAnd() []*AreaFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *AreaFilter) GetOr() []*AreaFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *AreaFilter) GetIdIn() []uint32 {
	if m != nil {
		return m.IdIn
	}
	return nil
}

func (m *AreaFilter) GetChildAreaIDIn() []uint32 {
	if m != nil {
		return m.ChildAreaIDIn
	}
	return nil
}

func (m *AreaFilter) GetRacklotIDIn() []uint32 {
	if m != nil {
		return m.RacklotIDIn
	}
	return nil
}

func (m *AreaFilter) GetIsInbound() *wrappers.BoolValue {
	if m != nil {
		return m.IsInbound
	}
	return nil
}

func (m *AreaFilter) GetIsOutbound() *wrappers.BoolValue {
	if m != nil {
		return m.IsOutbound
	}
	return nil
}

func (m *AreaFilter) GetIsValid() *wrappers.BoolValue {
	if m != nil {
		return m.IsValid
	}
	return nil
}

func (m *AreaFilter) GetParentAreaID() *wrappers.UInt32Value {
	if m != nil {
		return m.ParentAreaID
	}
	return nil
}

func (m *AreaFilter) GetTypeFilter() *AreaTypeFilter {
	if m != nil {
		return m.TypeFilter
	}
	return nil
}

func (m *AreaFilter) GetPropertiesFilter() *AreaPropertiesFilter {
	if m != nil {
		return m.PropertiesFilter
	}
	return nil
}

type AreaTypeFilter struct {
	And                  []*AreaTypeFilter     `protobuf:"bytes,1,rep,name=and,proto3" json:"and,omitempty"`
	Or                   []*AreaTypeFilter     `protobuf:"bytes,2,rep,name=or,proto3" json:"or,omitempty"`
	IdIn                 []uint32              `protobuf:"varint,3,rep,packed,name=idIn,proto3" json:"idIn,omitempty"`
	NameIn               []string              `protobuf:"bytes,4,rep,name=nameIn,proto3" json:"nameIn,omitempty"`
	Id                   *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AreaTypeFilter) Reset()         { *m = AreaTypeFilter{} }
func (m *AreaTypeFilter) String() string { return proto.CompactTextString(m) }
func (*AreaTypeFilter) ProtoMessage()    {}
func (*AreaTypeFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{10}
}

func (m *AreaTypeFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaTypeFilter.Unmarshal(m, b)
}
func (m *AreaTypeFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaTypeFilter.Marshal(b, m, deterministic)
}
func (m *AreaTypeFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaTypeFilter.Merge(m, src)
}
func (m *AreaTypeFilter) XXX_Size() int {
	return xxx_messageInfo_AreaTypeFilter.Size(m)
}
func (m *AreaTypeFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaTypeFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AreaTypeFilter proto.InternalMessageInfo

func (m *AreaTypeFilter) GetAnd() []*AreaTypeFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *AreaTypeFilter) GetOr() []*AreaTypeFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *AreaTypeFilter) GetIdIn() []uint32 {
	if m != nil {
		return m.IdIn
	}
	return nil
}

func (m *AreaTypeFilter) GetNameIn() []string {
	if m != nil {
		return m.NameIn
	}
	return nil
}

func (m *AreaTypeFilter) GetId() *wrappers.UInt32Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *AreaTypeFilter) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

type AreaPropertiesFilter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaPropertiesFilter) Reset()         { *m = AreaPropertiesFilter{} }
func (m *AreaPropertiesFilter) String() string { return proto.CompactTextString(m) }
func (*AreaPropertiesFilter) ProtoMessage()    {}
func (*AreaPropertiesFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{11}
}

func (m *AreaPropertiesFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaPropertiesFilter.Unmarshal(m, b)
}
func (m *AreaPropertiesFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaPropertiesFilter.Marshal(b, m, deterministic)
}
func (m *AreaPropertiesFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaPropertiesFilter.Merge(m, src)
}
func (m *AreaPropertiesFilter) XXX_Size() int {
	return xxx_messageInfo_AreaPropertiesFilter.Size(m)
}
func (m *AreaPropertiesFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaPropertiesFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AreaPropertiesFilter proto.InternalMessageInfo

func (m *AreaPropertiesFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AreaPropertiesFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AreaQuery struct {
	Limit                uint32      `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32      `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32      `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Filter               *AreaFilter `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AreaQuery) Reset()         { *m = AreaQuery{} }
func (m *AreaQuery) String() string { return proto.CompactTextString(m) }
func (*AreaQuery) ProtoMessage()    {}
func (*AreaQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{12}
}

func (m *AreaQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaQuery.Unmarshal(m, b)
}
func (m *AreaQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaQuery.Marshal(b, m, deterministic)
}
func (m *AreaQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaQuery.Merge(m, src)
}
func (m *AreaQuery) XXX_Size() int {
	return xxx_messageInfo_AreaQuery.Size(m)
}
func (m *AreaQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AreaQuery proto.InternalMessageInfo

func (m *AreaQuery) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AreaQuery) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AreaQuery) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AreaQuery) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *AreaQuery) GetFilter() *AreaFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type AreaTypeQuery struct {
	Limit                uint32          `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32          `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32          `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Filter               *AreaTypeFilter `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AreaTypeQuery) Reset()         { *m = AreaTypeQuery{} }
func (m *AreaTypeQuery) String() string { return proto.CompactTextString(m) }
func (*AreaTypeQuery) ProtoMessage()    {}
func (*AreaTypeQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{13}
}

func (m *AreaTypeQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaTypeQuery.Unmarshal(m, b)
}
func (m *AreaTypeQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaTypeQuery.Marshal(b, m, deterministic)
}
func (m *AreaTypeQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaTypeQuery.Merge(m, src)
}
func (m *AreaTypeQuery) XXX_Size() int {
	return xxx_messageInfo_AreaTypeQuery.Size(m)
}
func (m *AreaTypeQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaTypeQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AreaTypeQuery proto.InternalMessageInfo

func (m *AreaTypeQuery) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AreaTypeQuery) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AreaTypeQuery) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AreaTypeQuery) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *AreaTypeQuery) GetFilter() *AreaTypeFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Areas struct {
	Areas                []*Area  `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	Totalpages           uint32   `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32   `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	Totals               uint32   `protobuf:"varint,4,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Areas) Reset()         { *m = Areas{} }
func (m *Areas) String() string { return proto.CompactTextString(m) }
func (*Areas) ProtoMessage()    {}
func (*Areas) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{14}
}

func (m *Areas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Areas.Unmarshal(m, b)
}
func (m *Areas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Areas.Marshal(b, m, deterministic)
}
func (m *Areas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Areas.Merge(m, src)
}
func (m *Areas) XXX_Size() int {
	return xxx_messageInfo_Areas.Size(m)
}
func (m *Areas) XXX_DiscardUnknown() {
	xxx_messageInfo_Areas.DiscardUnknown(m)
}

var xxx_messageInfo_Areas proto.InternalMessageInfo

func (m *Areas) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

func (m *Areas) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *Areas) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

func (m *Areas) GetTotals() uint32 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type TypeReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeReq) Reset()         { *m = TypeReq{} }
func (m *TypeReq) String() string { return proto.CompactTextString(m) }
func (*TypeReq) ProtoMessage()    {}
func (*TypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{15}
}

func (m *TypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeReq.Unmarshal(m, b)
}
func (m *TypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeReq.Marshal(b, m, deterministic)
}
func (m *TypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeReq.Merge(m, src)
}
func (m *TypeReq) XXX_Size() int {
	return xxx_messageInfo_TypeReq.Size(m)
}
func (m *TypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TypeReq proto.InternalMessageInfo

func (m *TypeReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TypeReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TypeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FlagReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Flag                 bool     `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagReq) Reset()         { *m = FlagReq{} }
func (m *FlagReq) String() string { return proto.CompactTextString(m) }
func (*FlagReq) ProtoMessage()    {}
func (*FlagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{16}
}

func (m *FlagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagReq.Unmarshal(m, b)
}
func (m *FlagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagReq.Marshal(b, m, deterministic)
}
func (m *FlagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagReq.Merge(m, src)
}
func (m *FlagReq) XXX_Size() int {
	return xxx_messageInfo_FlagReq.Size(m)
}
func (m *FlagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagReq.DiscardUnknown(m)
}

var xxx_messageInfo_FlagReq proto.InternalMessageInfo

func (m *FlagReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FlagReq) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type CapReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cap                  uint32   `protobuf:"varint,2,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapReq) Reset()         { *m = CapReq{} }
func (m *CapReq) String() string { return proto.CompactTextString(m) }
func (*CapReq) ProtoMessage()    {}
func (*CapReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{17}
}

func (m *CapReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapReq.Unmarshal(m, b)
}
func (m *CapReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapReq.Marshal(b, m, deterministic)
}
func (m *CapReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapReq.Merge(m, src)
}
func (m *CapReq) XXX_Size() int {
	return xxx_messageInfo_CapReq.Size(m)
}
func (m *CapReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CapReq.DiscardUnknown(m)
}

var xxx_messageInfo_CapReq proto.InternalMessageInfo

func (m *CapReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CapReq) GetCap() uint32 {
	if m != nil {
		return m.Cap
	}
	return 0
}

type RacklotsReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Racklots             []uint32 `protobuf:"varint,2,rep,packed,name=racklots,proto3" json:"racklots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RacklotsReq) Reset()         { *m = RacklotsReq{} }
func (m *RacklotsReq) String() string { return proto.CompactTextString(m) }
func (*RacklotsReq) ProtoMessage()    {}
func (*RacklotsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{18}
}

func (m *RacklotsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RacklotsReq.Unmarshal(m, b)
}
func (m *RacklotsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RacklotsReq.Marshal(b, m, deterministic)
}
func (m *RacklotsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RacklotsReq.Merge(m, src)
}
func (m *RacklotsReq) XXX_Size() int {
	return xxx_messageInfo_RacklotsReq.Size(m)
}
func (m *RacklotsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RacklotsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RacklotsReq proto.InternalMessageInfo

func (m *RacklotsReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RacklotsReq) GetRacklots() []uint32 {
	if m != nil {
		return m.Racklots
	}
	return nil
}

type TaskReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskID               uint32   `protobuf:"varint,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReq) Reset()         { *m = TaskReq{} }
func (m *TaskReq) String() string { return proto.CompactTextString(m) }
func (*TaskReq) ProtoMessage()    {}
func (*TaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{19}
}

func (m *TaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReq.Unmarshal(m, b)
}
func (m *TaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReq.Marshal(b, m, deterministic)
}
func (m *TaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReq.Merge(m, src)
}
func (m *TaskReq) XXX_Size() int {
	return xxx_messageInfo_TaskReq.Size(m)
}
func (m *TaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReq proto.InternalMessageInfo

func (m *TaskReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskReq) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

type PropertiesReq struct {
	Id                   uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties           []*Property `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PropertiesReq) Reset()         { *m = PropertiesReq{} }
func (m *PropertiesReq) String() string { return proto.CompactTextString(m) }
func (*PropertiesReq) ProtoMessage()    {}
func (*PropertiesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{20}
}

func (m *PropertiesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesReq.Unmarshal(m, b)
}
func (m *PropertiesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesReq.Marshal(b, m, deterministic)
}
func (m *PropertiesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesReq.Merge(m, src)
}
func (m *PropertiesReq) XXX_Size() int {
	return xxx_messageInfo_PropertiesReq.Size(m)
}
func (m *PropertiesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesReq.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesReq proto.InternalMessageInfo

func (m *PropertiesReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PropertiesReq) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Property struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{21}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ParentReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentAreaID         uint32   `protobuf:"varint,2,opt,name=parentAreaID,proto3" json:"parentAreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentReq) Reset()         { *m = ParentReq{} }
func (m *ParentReq) String() string { return proto.CompactTextString(m) }
func (*ParentReq) ProtoMessage()    {}
func (*ParentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{22}
}

func (m *ParentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentReq.Unmarshal(m, b)
}
func (m *ParentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentReq.Marshal(b, m, deterministic)
}
func (m *ParentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentReq.Merge(m, src)
}
func (m *ParentReq) XXX_Size() int {
	return xxx_messageInfo_ParentReq.Size(m)
}
func (m *ParentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentReq.DiscardUnknown(m)
}

var xxx_messageInfo_ParentReq proto.InternalMessageInfo

func (m *ParentReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ParentReq) GetParentAreaID() uint32 {
	if m != nil {
		return m.ParentAreaID
	}
	return 0
}

type ChildsReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChildAreaIDs         []uint32 `protobuf:"varint,2,rep,packed,name=childAreaIDs,proto3" json:"childAreaIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChildsReq) Reset()         { *m = ChildsReq{} }
func (m *ChildsReq) String() string { return proto.CompactTextString(m) }
func (*ChildsReq) ProtoMessage()    {}
func (*ChildsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce7e3eb842cc36cb, []int{23}
}

func (m *ChildsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildsReq.Unmarshal(m, b)
}
func (m *ChildsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildsReq.Marshal(b, m, deterministic)
}
func (m *ChildsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildsReq.Merge(m, src)
}
func (m *ChildsReq) XXX_Size() int {
	return xxx_messageInfo_ChildsReq.Size(m)
}
func (m *ChildsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChildsReq proto.InternalMessageInfo

func (m *ChildsReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChildsReq) GetChildAreaIDs() []uint32 {
	if m != nil {
		return m.ChildAreaIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*AreaType)(nil), "go.micro.srv.area.AreaType")
	proto.RegisterType((*UpdateAreaType)(nil), "go.micro.srv.area.UpdateAreaType")
	proto.RegisterType((*AreaTypes)(nil), "go.micro.srv.area.AreaTypes")
	proto.RegisterType((*Area)(nil), "go.micro.srv.area.Area")
	proto.RegisterType((*UpdateArea)(nil), "go.micro.srv.area.UpdateArea")
	proto.RegisterType((*UpdateAreaReq)(nil), "go.micro.srv.area.UpdateAreaReq")
	proto.RegisterType((*UpdateAreaTypeReq)(nil), "go.micro.srv.area.UpdateAreaTypeReq")
	proto.RegisterType((*Response)(nil), "go.micro.srv.area.Response")
	proto.RegisterType((*AreaIDReq)(nil), "go.micro.srv.area.AreaIDReq")
	proto.RegisterType((*AreaFilter)(nil), "go.micro.srv.area.AreaFilter")
	proto.RegisterType((*AreaTypeFilter)(nil), "go.micro.srv.area.AreaTypeFilter")
	proto.RegisterType((*AreaPropertiesFilter)(nil), "go.micro.srv.area.AreaPropertiesFilter")
	proto.RegisterType((*AreaQuery)(nil), "go.micro.srv.area.AreaQuery")
	proto.RegisterType((*AreaTypeQuery)(nil), "go.micro.srv.area.AreaTypeQuery")
	proto.RegisterType((*Areas)(nil), "go.micro.srv.area.Areas")
	proto.RegisterType((*TypeReq)(nil), "go.micro.srv.area.TypeReq")
	proto.RegisterType((*FlagReq)(nil), "go.micro.srv.area.FlagReq")
	proto.RegisterType((*CapReq)(nil), "go.micro.srv.area.CapReq")
	proto.RegisterType((*RacklotsReq)(nil), "go.micro.srv.area.RacklotsReq")
	proto.RegisterType((*TaskReq)(nil), "go.micro.srv.area.TaskReq")
	proto.RegisterType((*PropertiesReq)(nil), "go.micro.srv.area.PropertiesReq")
	proto.RegisterType((*Property)(nil), "go.micro.srv.area.Property")
	proto.RegisterType((*ParentReq)(nil), "go.micro.srv.area.ParentReq")
	proto.RegisterType((*ChildsReq)(nil), "go.micro.srv.area.ChildsReq")
}

func init() { proto.RegisterFile("proto/area/area.proto", fileDescriptor_ce7e3eb842cc36cb) }

var fileDescriptor_ce7e3eb842cc36cb = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x57, 0x9c, 0xef, 0x97, 0xa6, 0xea, 0x8e, 0xba, 0x5d, 0x6f, 0xda, 0x2e, 0xc1, 0x5a, 0x89,
	0x0a, 0xd1, 0x94, 0xb6, 0xac, 0x44, 0x41, 0xda, 0xdd, 0x7e, 0xd0, 0x2a, 0x45, 0xb0, 0xc5, 0xd9,
	0xdd, 0x03, 0xe2, 0x32, 0x8d, 0xa7, 0xc1, 0xaa, 0x1b, 0x7b, 0x67, 0x26, 0x45, 0xbd, 0x73, 0xe4,
	0xc0, 0x1f, 0x80, 0x38, 0x22, 0xfe, 0x15, 0x2e, 0x88, 0x3f, 0x09, 0xcd, 0x87, 0x63, 0x3b, 0xb1,
	0x9d, 0xa4, 0xb0, 0x97, 0xc8, 0x33, 0xef, 0xbd, 0xdf, 0xbc, 0xef, 0xf7, 0x02, 0x0f, 0x03, 0xea,
	0x73, 0x7f, 0x07, 0x53, 0x82, 0xe5, 0x4f, 0x47, 0x9e, 0xd1, 0x83, 0x81, 0xdf, 0xb9, 0x71, 0xfb,
	0xd4, 0xef, 0x30, 0x7a, 0xdb, 0x11, 0x84, 0xd6, 0x93, 0x81, 0xef, 0x0f, 0x3c, 0xb2, 0x23, 0x19,
	0x2e, 0x47, 0x57, 0x3b, 0x3f, 0x51, 0x1c, 0x04, 0x84, 0x32, 0x25, 0x62, 0x05, 0x50, 0x3b, 0xa4,
	0x04, 0xbf, 0xbe, 0x0b, 0x08, 0x5a, 0x06, 0xc3, 0x75, 0xcc, 0x42, 0xbb, 0xb0, 0xd5, 0xb4, 0x0d,
	0xd7, 0x41, 0x08, 0x4a, 0x43, 0x7c, 0x43, 0x4c, 0xa3, 0x5d, 0xd8, 0xaa, 0xdb, 0xf2, 0x1b, 0xb5,
	0xa1, 0xe1, 0x10, 0xd6, 0xa7, 0x6e, 0xc0, 0x5d, 0x7f, 0x68, 0x16, 0x25, 0x29, 0x7e, 0x85, 0x9e,
	0x00, 0x04, 0xd4, 0x0f, 0x08, 0xe5, 0x2e, 0x61, 0x66, 0x49, 0x32, 0xc4, 0x6e, 0xac, 0x7f, 0x0a,
	0xb0, 0xfc, 0x26, 0x70, 0x30, 0x27, 0xe3, 0x87, 0x3f, 0x19, 0x3f, 0xdc, 0xd8, 0xdb, 0xe8, 0x28,
	0x8d, 0x3b, 0xa1, 0xc6, 0x9d, 0x37, 0xdd, 0x21, 0xdf, 0xdf, 0x7b, 0x8b, 0xbd, 0x11, 0x91, 0x6a,
	0x7d, 0x1a, 0x53, 0x2b, 0x8d, 0xbf, 0xc7, 0xa9, 0x3b, 0x1c, 0x28, 0x7e, 0xa5, 0xf4, 0xf3, 0x69,
	0xa5, 0x67, 0x09, 0x2e, 0x64, 0xd2, 0x6f, 0x05, 0xa8, 0x87, 0xc6, 0x30, 0x74, 0x00, 0x75, 0x1c,
	0x1e, 0xcc, 0x42, 0xbb, 0xb8, 0xd5, 0xd8, 0x5b, 0xef, 0x4c, 0x45, 0xa6, 0x13, 0x0a, 0xd8, 0x11,
	0xb7, 0x78, 0x88, 0xfb, 0x1c, 0x7b, 0x01, 0x1e, 0x10, 0x26, 0x0d, 0x6c, 0xda, 0xb1, 0x1b, 0xb4,
	0x01, 0xf5, 0xfe, 0x88, 0x52, 0x45, 0x2e, 0x4a, 0x72, 0x74, 0x81, 0xd6, 0xa0, 0x22, 0x79, 0x95,
	0x8a, 0x4d, 0x5b, 0x9f, 0xac, 0xbf, 0x0c, 0x28, 0x89, 0xd7, 0x74, 0x80, 0x57, 0xc7, 0x01, 0xb6,
	0x60, 0x29, 0xc0, 0x94, 0x0c, 0xb9, 0xa0, 0x76, 0x4f, 0xcc, 0x87, 0x92, 0x92, 0xb8, 0x43, 0x3b,
	0x50, 0xe2, 0x77, 0x01, 0x31, 0xd7, 0xa4, 0xd3, 0x72, 0x0d, 0x91, 0x8c, 0xa8, 0x05, 0x35, 0x8a,
	0xfb, 0xd7, 0x9e, 0xcf, 0x99, 0xf9, 0xa8, 0x5d, 0xdc, 0x6a, 0xda, 0xe3, 0x33, 0x7a, 0x0a, 0x4d,
	0x9f, 0x3a, 0x84, 0x1e, 0xe3, 0x00, 0xf7, 0x5d, 0x7e, 0x67, 0x3e, 0x96, 0x2f, 0x26, 0x2f, 0x85,
	0x95, 0x2e, 0xeb, 0x0e, 0x2f, 0xfd, 0xd1, 0xd0, 0x31, 0x37, 0xda, 0x85, 0xad, 0x9a, 0x1d, 0x5d,
	0x08, 0x1f, 0xb9, 0xec, 0xd5, 0x88, 0x2b, 0xf2, 0xa6, 0x24, 0xc7, 0x6e, 0x90, 0x09, 0x55, 0x97,
	0xbd, 0xc5, 0x9e, 0xeb, 0x98, 0x6d, 0x49, 0x0c, 0x8f, 0xc2, 0xdc, 0xfe, 0x8f, 0xae, 0xe7, 0x28,
	0xcb, 0x98, 0xb9, 0x2e, 0xb5, 0x4b, 0xdc, 0x4d, 0x84, 0xfa, 0x83, 0xa9, 0x50, 0xff, 0x59, 0x04,
	0x88, 0xb2, 0x77, 0xc1, 0xcc, 0x3d, 0x4a, 0x33, 0x7f, 0x96, 0xe0, 0x84, 0x73, 0x3e, 0x8b, 0xcc,
	0x5b, 0x97, 0xd2, 0xad, 0x29, 0xe9, 0x23, 0xdf, 0xf7, 0x94, 0xec, 0xd8, 0xf4, 0xcf, 0x27, 0x5d,
	0x9a, 0x2f, 0x17, 0x73, 0xf7, 0x17, 0x53, 0xee, 0xce, 0x17, 0x8d, 0x87, 0xe2, 0xe5, 0x44, 0x7e,
	0x19, 0x73, 0x98, 0x9b, 0xcc, 0xbe, 0xbc, 0x64, 0x9a, 0x15, 0x2a, 0x1b, 0x9a, 0x51, 0xa4, 0x6c,
	0xf2, 0x6e, 0xaa, 0xbf, 0xed, 0x42, 0x49, 0x24, 0xb0, 0x56, 0x6b, 0x33, 0x25, 0xb5, 0x63, 0xf2,
	0x92, 0xd5, 0xfa, 0x1e, 0x1e, 0x24, 0x7b, 0x57, 0x1a, 0xee, 0xb3, 0x04, 0xee, 0x87, 0xb9, 0xb8,
	0xaa, 0x70, 0x24, 0x36, 0x40, 0xcd, 0x26, 0x2c, 0xf0, 0x87, 0x8c, 0x58, 0xeb, 0xaa, 0xa1, 0x74,
	0x4f, 0x52, 0xf0, 0xad, 0xbf, 0x4b, 0x00, 0x82, 0x7a, 0xea, 0x7a, 0x9c, 0x50, 0xb4, 0x03, 0x45,
	0x3c, 0x74, 0x74, 0xa7, 0xd9, 0xcc, 0x28, 0x50, 0xc5, 0x6b, 0x0b, 0x4e, 0xb4, 0x0d, 0x86, 0x4f,
	0x4d, 0x63, 0x1e, 0x7e, 0xc3, 0xa7, 0x62, 0x0c, 0xb8, 0x4e, 0x57, 0xb4, 0x4d, 0xe1, 0x7f, 0xf9,
	0x2d, 0x0a, 0x39, 0x56, 0x36, 0xdd, 0xa1, 0x59, 0x92, 0xc4, 0xe4, 0xa5, 0x18, 0x16, 0x3a, 0x5a,
	0x92, 0xa7, 0x2c, 0x79, 0xe2, 0x57, 0xc9, 0xbc, 0xac, 0xdc, 0x3f, 0x2f, 0xab, 0x0b, 0xe5, 0x65,
	0xac, 0x86, 0x6a, 0xf3, 0xd7, 0xd0, 0x64, 0x36, 0xd7, 0x17, 0xce, 0xe6, 0x43, 0x00, 0xd1, 0x22,
	0x95, 0x6f, 0xcd, 0x46, 0x66, 0x7a, 0x84, 0x89, 0xa1, 0x83, 0x10, 0x13, 0x42, 0x3d, 0x58, 0x89,
	0x52, 0x5c, 0x03, 0x2d, 0x49, 0xa0, 0x8f, 0x32, 0x80, 0x2e, 0x26, 0xd8, 0xed, 0x29, 0x00, 0xeb,
	0x67, 0x03, 0x96, 0x93, 0x6f, 0xa2, 0xfd, 0x78, 0x52, 0xcd, 0xa1, 0xa3, 0x4c, 0xac, 0xdd, 0x58,
	0x62, 0xcd, 0x21, 0x93, 0x95, 0x5c, 0x6b, 0x50, 0x11, 0x63, 0x5b, 0x67, 0x55, 0xdd, 0xd6, 0x27,
	0xdd, 0x6c, 0xcb, 0x0b, 0xae, 0x09, 0x95, 0x79, 0xd7, 0x04, 0xeb, 0x39, 0xac, 0xa6, 0x39, 0x0c,
	0xad, 0x40, 0xf1, 0x9a, 0xdc, 0xc9, 0x02, 0xac, 0xdb, 0xe2, 0x13, 0xad, 0x42, 0xf9, 0x56, 0x08,
	0xea, 0xd5, 0x48, 0x1d, 0xac, 0xdf, 0xf5, 0x1a, 0xf0, 0xdd, 0x88, 0x50, 0xc9, 0xe3, 0xb9, 0x37,
	0x2e, 0xd7, 0x85, 0xab, 0x0e, 0xc2, 0x36, 0xff, 0xea, 0x8a, 0x11, 0xae, 0xa7, 0xbb, 0x3e, 0x09,
	0x3f, 0x88, 0x21, 0xae, 0x87, 0xba, 0xfc, 0x16, 0x93, 0x2c, 0x20, 0xf4, 0x42, 0x5c, 0xab, 0x81,
	0x1e, 0x1e, 0xd1, 0x33, 0xa8, 0x5c, 0xa9, 0xd8, 0x57, 0x33, 0x7b, 0x57, 0xac, 0x8a, 0x35, 0xb3,
	0xf5, 0x47, 0x01, 0x9a, 0x61, 0x0c, 0xde, 0xbf, 0x92, 0x07, 0x13, 0x4a, 0xce, 0x91, 0x11, 0xa1,
	0xa2, 0xbf, 0x14, 0xa0, 0x2c, 0x48, 0x0c, 0x6d, 0x43, 0x59, 0x30, 0x86, 0x8b, 0xd4, 0xa3, 0x0c,
	0x0c, 0x5b, 0x71, 0xbd, 0xa7, 0x05, 0xea, 0x10, 0xaa, 0x59, 0xbd, 0x1e, 0xe9, 0xf5, 0x48, 0x3c,
	0x55, 0xd6, 0x1b, 0x50, 0xb8, 0x37, 0x17, 0xa3, 0xbd, 0xd9, 0xda, 0x86, 0xea, 0xa9, 0x87, 0x07,
	0x19, 0x10, 0x57, 0x1e, 0x1e, 0x48, 0x88, 0x9a, 0x2d, 0xbf, 0xad, 0x8f, 0xa1, 0x72, 0x8c, 0x83,
	0x34, 0xee, 0x15, 0x28, 0xf6, 0x71, 0xa0, 0x4d, 0x13, 0x9f, 0xd6, 0x01, 0x34, 0x6c, 0x3d, 0x13,
	0xd3, 0x04, 0xe2, 0x23, 0xd4, 0x48, 0x8e, 0x50, 0x6b, 0x17, 0xaa, 0xaf, 0x31, 0xbb, 0x4e, 0x13,
	0x13, 0xbe, 0xc0, 0xec, 0x5a, 0x4f, 0x6d, 0xe1, 0x0b, 0x79, 0xb2, 0x7e, 0x80, 0x66, 0x54, 0x20,
	0x69, 0x82, 0x5f, 0x26, 0xc6, 0xb2, 0x91, 0xb9, 0xff, 0x6a, 0x94, 0xbb, 0xc4, 0xcc, 0xde, 0x83,
	0x5a, 0x78, 0x3f, 0x77, 0xd9, 0xbd, 0x80, 0xfa, 0x85, 0xec, 0xb2, 0x69, 0xda, 0x58, 0x29, 0x2b,
	0xc8, 0xc4, 0x8a, 0x2b, 0x00, 0x8e, 0xc5, 0xdc, 0x62, 0x19, 0x00, 0x89, 0xa5, 0xd1, 0x98, 0x5e,
	0x1a, 0xf7, 0x7e, 0x6d, 0x40, 0x43, 0x7c, 0xf7, 0x08, 0xbd, 0x75, 0xfb, 0x04, 0xbd, 0x84, 0xea,
	0x19, 0x91, 0xe8, 0x68, 0x23, 0x23, 0x61, 0xe5, 0x64, 0x6f, 0x65, 0xa5, 0x33, 0x3a, 0x82, 0x9a,
	0x46, 0x60, 0x99, 0x10, 0xb2, 0x82, 0x5b, 0x66, 0x06, 0x95, 0xa1, 0x17, 0x50, 0x3d, 0x74, 0xa4,
	0x8e, 0x28, 0xeb, 0x9d, 0x56, 0x5a, 0x60, 0xc2, 0x25, 0x04, 0x7d, 0x9d, 0x58, 0x75, 0xdb, 0xf9,
	0xfb, 0x11, 0x79, 0x97, 0x0f, 0x76, 0x06, 0x70, 0x42, 0x3c, 0xa2, 0xc1, 0xf2, 0xdd, 0x92, 0x0b,
	0xf4, 0x2d, 0x2c, 0x69, 0xd7, 0xa8, 0xff, 0x4c, 0xed, 0x9c, 0xb6, 0xa2, 0x5c, 0xb4, 0x91, 0xc3,
	0xc1, 0xd0, 0x19, 0x34, 0x62, 0x78, 0x28, 0xef, 0x1f, 0x4e, 0x2b, 0x8f, 0x28, 0x80, 0xb4, 0xbf,
	0xef, 0x07, 0x34, 0xb6, 0xb0, 0x37, 0xf5, 0x07, 0xf9, 0xe9, 0xec, 0x1d, 0x72, 0x96, 0xdb, 0xce,
	0x61, 0x39, 0xf2, 0xff, 0x7f, 0x54, 0xf0, 0x5c, 0x5a, 0x6a, 0x8f, 0x17, 0xf1, 0x34, 0xde, 0xa8,
	0x23, 0xe5, 0x63, 0x7d, 0x13, 0xea, 0xf5, 0xff, 0xc0, 0x9d, 0x43, 0xf3, 0xd0, 0x71, 0x8e, 0xc3,
	0xea, 0x4c, 0xaf, 0x9e, 0x71, 0xb5, 0xcf, 0xca, 0x34, 0x81, 0x15, 0x75, 0xbb, 0xd4, 0x54, 0x4b,
	0x34, 0xc3, 0x59, 0xba, 0xad, 0xf4, 0x08, 0x7f, 0x95, 0xf8, 0x3b, 0xf7, 0x38, 0x4d, 0x3d, 0xd9,
	0xf9, 0xf3, 0xb1, 0xbe, 0x02, 0xe8, 0x11, 0x1e, 0x2e, 0xc3, 0xad, 0x14, 0x56, 0x3d, 0x6e, 0xf2,
	0x61, 0x4e, 0xa1, 0x21, 0x54, 0x0a, 0x17, 0xe3, 0x7b, 0xe3, 0x1c, 0x43, 0xad, 0x47, 0xb8, 0xda,
	0x93, 0xef, 0x0d, 0x72, 0x0e, 0xcd, 0x1e, 0xe1, 0x17, 0xe3, 0xd6, 0x9c, 0x1a, 0xbb, 0x71, 0xab,
	0xcf, 0xc5, 0xba, 0xac, 0xc8, 0x3d, 0x6f, 0xff, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x7c,
	0x50, 0x28, 0x2a, 0x13, 0x00, 0x00,
}
