// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/point/point.proto

package go_micro_srv_point

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	GarageID             uint32   `protobuf:"varint,1,opt,name=garageID,proto3" json:"garageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetGarageID() uint32 {
	if m != nil {
		return m.GarageID
	}
	return 0
}

type Response struct {
	Res                  bool     `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

type FileRequest struct {
	GarageID             uint32   `protobuf:"varint,1,opt,name=garageID,proto3" json:"garageID,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Filebytes            []byte   `protobuf:"bytes,3,opt,name=filebytes,proto3" json:"filebytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{2}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetGarageID() uint32 {
	if m != nil {
		return m.GarageID
	}
	return 0
}

func (m *FileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileRequest) GetFilebytes() []byte {
	if m != nil {
		return m.Filebytes
	}
	return nil
}

type FileResponse struct {
	Res                  bool     `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileResponse) Reset()         { *m = FileResponse{} }
func (m *FileResponse) String() string { return proto.CompactTextString(m) }
func (*FileResponse) ProtoMessage()    {}
func (*FileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{3}
}

func (m *FileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileResponse.Unmarshal(m, b)
}
func (m *FileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileResponse.Marshal(b, m, deterministic)
}
func (m *FileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileResponse.Merge(m, src)
}
func (m *FileResponse) XXX_Size() int {
	return xxx_messageInfo_FileResponse.Size(m)
}
func (m *FileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileResponse proto.InternalMessageInfo

func (m *FileResponse) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

type IdRequest struct {
	GarageID             uint32   `protobuf:"varint,1,opt,name=garageID,proto3" json:"garageID,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{4}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetGarageID() uint32 {
	if m != nil {
		return m.GarageID
	}
	return 0
}

func (m *IdRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Query struct {
	GarageID             uint32   `protobuf:"varint,1,opt,name=garageID,proto3" json:"garageID,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	QueryString          string   `protobuf:"bytes,6,opt,name=queryString,proto3" json:"queryString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{5}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetGarageID() uint32 {
	if m != nil {
		return m.GarageID
	}
	return 0
}

func (m *Query) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Query) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

type PointResponse struct {
	PointID              uint32   `protobuf:"varint,1,opt,name=pointID,proto3" json:"pointID,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Angle                uint32   `protobuf:"varint,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Curvature            uint32   `protobuf:"varint,5,opt,name=curvature,proto3" json:"curvature,omitempty"`
	PlcBits              uint32   `protobuf:"varint,6,opt,name=plcBits,proto3" json:"plcBits,omitempty"`
	PlcWord              uint32   `protobuf:"varint,7,opt,name=plcWord,proto3" json:"plcWord,omitempty"`
	PlcWord2             uint32   `protobuf:"varint,8,opt,name=plcWord2,proto3" json:"plcWord2,omitempty"`
	ChangeTime           uint32   `protobuf:"varint,9,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
	Remark               string   `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointResponse) Reset()         { *m = PointResponse{} }
func (m *PointResponse) String() string { return proto.CompactTextString(m) }
func (*PointResponse) ProtoMessage()    {}
func (*PointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{6}
}

func (m *PointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointResponse.Unmarshal(m, b)
}
func (m *PointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointResponse.Marshal(b, m, deterministic)
}
func (m *PointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointResponse.Merge(m, src)
}
func (m *PointResponse) XXX_Size() int {
	return xxx_messageInfo_PointResponse.Size(m)
}
func (m *PointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointResponse proto.InternalMessageInfo

func (m *PointResponse) GetPointID() uint32 {
	if m != nil {
		return m.PointID
	}
	return 0
}

func (m *PointResponse) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PointResponse) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointResponse) GetAngle() uint32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *PointResponse) GetCurvature() uint32 {
	if m != nil {
		return m.Curvature
	}
	return 0
}

func (m *PointResponse) GetPlcBits() uint32 {
	if m != nil {
		return m.PlcBits
	}
	return 0
}

func (m *PointResponse) GetPlcWord() uint32 {
	if m != nil {
		return m.PlcWord
	}
	return 0
}

func (m *PointResponse) GetPlcWord2() uint32 {
	if m != nil {
		return m.PlcWord2
	}
	return 0
}

func (m *PointResponse) GetChangeTime() uint32 {
	if m != nil {
		return m.ChangeTime
	}
	return 0
}

func (m *PointResponse) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type PointsResponse struct {
	Points               []*PointResponse `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Totalpages           uint32           `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32           `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PointsResponse) Reset()         { *m = PointsResponse{} }
func (m *PointsResponse) String() string { return proto.CompactTextString(m) }
func (*PointsResponse) ProtoMessage()    {}
func (*PointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b92d483b7a94ed0, []int{7}
}

func (m *PointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointsResponse.Unmarshal(m, b)
}
func (m *PointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointsResponse.Marshal(b, m, deterministic)
}
func (m *PointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointsResponse.Merge(m, src)
}
func (m *PointsResponse) XXX_Size() int {
	return xxx_messageInfo_PointsResponse.Size(m)
}
func (m *PointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointsResponse proto.InternalMessageInfo

func (m *PointsResponse) GetPoints() []*PointResponse {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *PointsResponse) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *PointsResponse) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.point.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.point.Response")
	proto.RegisterType((*FileRequest)(nil), "go.micro.srv.point.FileRequest")
	proto.RegisterType((*FileResponse)(nil), "go.micro.srv.point.FileResponse")
	proto.RegisterType((*IdRequest)(nil), "go.micro.srv.point.IdRequest")
	proto.RegisterType((*Query)(nil), "go.micro.srv.point.Query")
	proto.RegisterType((*PointResponse)(nil), "go.micro.srv.point.PointResponse")
	proto.RegisterType((*PointsResponse)(nil), "go.micro.srv.point.PointsResponse")
}

func init() { proto.RegisterFile("proto/point/point.proto", fileDescriptor_3b92d483b7a94ed0) }

var fileDescriptor_3b92d483b7a94ed0 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0xed, 0x26, 0xcd, 0xbf, 0x49, 0xd2, 0xdf, 0x4f, 0x16, 0x82, 0x6d, 0x08, 0xb0, 0x58, 0x42,
	0xca, 0x69, 0x91, 0xc2, 0x01, 0x71, 0xa4, 0x8a, 0x40, 0x91, 0x50, 0x55, 0xdc, 0x4a, 0x1c, 0x91,
	0x9b, 0x4c, 0x16, 0x8b, 0x4d, 0x76, 0x6b, 0x3b, 0x51, 0x73, 0xe4, 0xc8, 0xd7, 0xe0, 0x0b, 0xf1,
	0x95, 0x90, 0x67, 0xbd, 0xdb, 0x20, 0x12, 0xe8, 0x25, 0xf2, 0x7b, 0xb3, 0xf3, 0xfc, 0xfc, 0x3c,
	0x0e, 0x3c, 0xca, 0x75, 0x66, 0xb3, 0x97, 0x79, 0xa6, 0x56, 0xb6, 0xf8, 0x8d, 0x89, 0x61, 0x2c,
	0xc9, 0xe2, 0xa5, 0x9a, 0xe9, 0x2c, 0x36, 0x7a, 0x13, 0x53, 0x85, 0xbf, 0x80, 0x96, 0xc0, 0x9b,
	0x35, 0x1a, 0xcb, 0x06, 0xd0, 0x4e, 0xa4, 0x96, 0x09, 0x4e, 0x27, 0x61, 0x10, 0x05, 0xa3, 0xbe,
	0xa8, 0x30, 0x1f, 0x42, 0x5b, 0xa0, 0xc9, 0xb3, 0x95, 0x41, 0xf6, 0x3f, 0xd4, 0x35, 0x1a, 0xfa,
	0xa4, 0x2d, 0xdc, 0x92, 0xcf, 0xa0, 0xfb, 0x4e, 0xa5, 0x78, 0x0f, 0x21, 0x57, 0x5b, 0xa8, 0x14,
	0xcf, 0xe5, 0x12, 0xc3, 0x5a, 0x14, 0x8c, 0x3a, 0xa2, 0xc2, 0x6c, 0x08, 0x1d, 0xb7, 0xbe, 0xde,
	0x5a, 0x34, 0x61, 0x3d, 0x0a, 0x46, 0x3d, 0x71, 0x47, 0xf0, 0x08, 0x7a, 0xc5, 0x26, 0x07, 0x6d,
	0xbc, 0x86, 0xce, 0x74, 0x7e, 0x1f, 0x13, 0x27, 0x50, 0x53, 0x73, 0xda, 0xbe, 0x2f, 0x6a, 0x6a,
	0xce, 0x7f, 0x04, 0xd0, 0xf8, 0xb8, 0x46, 0xbd, 0xfd, 0x6b, 0xd7, 0x03, 0x68, 0xa4, 0x6a, 0xa9,
	0xac, 0x6f, 0x2c, 0x00, 0x7b, 0x08, 0xcd, 0x6c, 0xb1, 0x30, 0x68, 0xc9, 0x71, 0x5f, 0x78, 0xc4,
	0x18, 0x1c, 0xe7, 0x32, 0xc1, 0xf0, 0x98, 0x58, 0x5a, 0xb3, 0x53, 0x68, 0xe7, 0xa8, 0x3f, 0x13,
	0xdf, 0x20, 0xbe, 0x95, 0xa3, 0xbe, 0x70, 0xa5, 0x08, 0xba, 0x37, 0xce, 0xc1, 0xa5, 0xd5, 0x6a,
	0x95, 0x84, 0x4d, 0x8a, 0x66, 0x97, 0xe2, 0xdf, 0x6a, 0xd0, 0xbf, 0x70, 0x77, 0x56, 0x25, 0x10,
	0x42, 0x8b, 0x2e, 0xb1, 0xf2, 0x5a, 0x42, 0xd6, 0x83, 0xe0, 0xd6, 0xdb, 0x0c, 0x6e, 0x1d, 0xda,
	0x7a, 0x77, 0xc1, 0xd6, 0x1d, 0x43, 0xae, 0x92, 0xb4, 0x74, 0x56, 0x00, 0x97, 0xfd, 0x6c, 0xad,
	0x37, 0xd2, 0xae, 0x75, 0xe9, 0xed, 0x8e, 0xa0, 0x9d, 0xd2, 0xd9, 0x99, 0xb2, 0x86, 0x9c, 0xb9,
	0x9d, 0x0a, 0xe8, 0x2b, 0x9f, 0x32, 0x3d, 0x0f, 0x5b, 0x55, 0xc5, 0x41, 0x17, 0xa5, 0x5f, 0x8e,
	0xc3, 0x76, 0x11, 0x65, 0x89, 0xd9, 0x53, 0x80, 0xd9, 0x17, 0xb9, 0x4a, 0xf0, 0x4a, 0x2d, 0x31,
	0xec, 0x50, 0x75, 0x87, 0x71, 0xa1, 0x6a, 0x5c, 0x4a, 0xfd, 0x35, 0x04, 0x0a, 0xc2, 0x23, 0xfe,
	0x3d, 0x80, 0x13, 0xca, 0xc0, 0x54, 0x21, 0xbc, 0x81, 0x26, 0x9d, 0xda, 0x4d, 0x42, 0x7d, 0xd4,
	0x1d, 0x3f, 0x8f, 0xff, 0x9c, 0xf2, 0xf8, 0xb7, 0xdc, 0x84, 0x6f, 0x70, 0x2e, 0x6c, 0x66, 0x65,
	0xea, 0xee, 0xc3, 0xf8, 0xb8, 0x76, 0x18, 0x9f, 0x89, 0x2e, 0xca, 0xf5, 0x2a, 0x93, 0x82, 0x18,
	0xff, 0xac, 0x41, 0x83, 0x74, 0xd9, 0x15, 0xf4, 0x2f, 0xe5, 0x06, 0x09, 0xb8, 0x11, 0x65, 0xcf,
	0xf6, 0x79, 0xd8, 0x79, 0x21, 0x83, 0xe8, 0xf0, 0x07, 0x85, 0x47, 0x7e, 0xc4, 0x04, 0xf4, 0xde,
	0xa3, 0x25, 0xd1, 0xb3, 0xed, 0x74, 0xc2, 0x9e, 0xec, 0xeb, 0xa9, 0xe6, 0x7d, 0xf0, 0xef, 0x73,
	0xf3, 0x23, 0xf6, 0x01, 0x3a, 0xa5, 0xa6, 0x61, 0xa7, 0xfb, 0x3a, 0xe8, 0x19, 0x0c, 0xf8, 0x41,
	0x31, 0xb3, 0xa3, 0x76, 0x0e, 0xff, 0x4d, 0x30, 0x45, 0x8b, 0x6f, 0xd3, 0xd4, 0x6b, 0x3e, 0xde,
	0xd7, 0x58, 0x5a, 0x1c, 0xee, 0x2f, 0x96, 0x7a, 0xd7, 0x4d, 0xfa, 0x9b, 0x7a, 0xf5, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0x6a, 0x49, 0x79, 0xc1, 0x04, 0x00, 0x00,
}
