// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package go_micro_srv_agv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateReq struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ParaNo               uint32   `protobuf:"varint,2,opt,name=paraNo,proto3" json:"paraNo,omitempty"`
	Value                uint32   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UpdateReq) GetParaNo() uint32 {
	if m != nil {
		return m.ParaNo
	}
	return 0
}

func (m *UpdateReq) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type CancelReq struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReq) Reset()         { *m = CancelReq{} }
func (m *CancelReq) String() string { return proto.CompactTextString(m) }
func (*CancelReq) ProtoMessage()    {}
func (*CancelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *CancelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReq.Unmarshal(m, b)
}
func (m *CancelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReq.Marshal(b, m, deterministic)
}
func (m *CancelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReq.Merge(m, src)
}
func (m *CancelReq) XXX_Size() int {
	return xxx_messageInfo_CancelReq.Size(m)
}
func (m *CancelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReq proto.InternalMessageInfo

func (m *CancelReq) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Response struct {
	Res                  bool     `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Task struct {
	TsId                 uint32   `protobuf:"varint,1,opt,name=tsId,proto3" json:"tsId,omitempty"`
	Priority             uint32   `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Ikey                 uint32   `protobuf:"varint,3,opt,name=ikey,proto3" json:"ikey,omitempty"`
	Params               []int32  `protobuf:"varint,4,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{4}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTsId() uint32 {
	if m != nil {
		return m.TsId
	}
	return 0
}

func (m *Task) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Task) GetIkey() uint32 {
	if m != nil {
		return m.Ikey
	}
	return 0
}

func (m *Task) GetParams() []int32 {
	if m != nil {
		return m.Params
	}
	return nil
}

type QBMessage struct {
	TaskID               uint32   `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	TsID                 uint32   `protobuf:"varint,2,opt,name=tsID,proto3" json:"tsID,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Code                 uint32   `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Ikey                 uint32   `protobuf:"varint,5,opt,name=ikey,proto3" json:"ikey,omitempty"`
	Params               []uint32 `protobuf:"varint,6,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QBMessage) Reset()         { *m = QBMessage{} }
func (m *QBMessage) String() string { return proto.CompactTextString(m) }
func (*QBMessage) ProtoMessage()    {}
func (*QBMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{5}
}

func (m *QBMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QBMessage.Unmarshal(m, b)
}
func (m *QBMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QBMessage.Marshal(b, m, deterministic)
}
func (m *QBMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QBMessage.Merge(m, src)
}
func (m *QBMessage) XXX_Size() int {
	return xxx_messageInfo_QBMessage.Size(m)
}
func (m *QBMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_QBMessage.DiscardUnknown(m)
}

var xxx_messageInfo_QBMessage proto.InternalMessageInfo

func (m *QBMessage) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

func (m *QBMessage) GetTsID() uint32 {
	if m != nil {
		return m.TsID
	}
	return 0
}

func (m *QBMessage) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *QBMessage) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QBMessage) GetIkey() uint32 {
	if m != nil {
		return m.Ikey
	}
	return 0
}

func (m *QBMessage) GetParams() []uint32 {
	if m != nil {
		return m.Params
	}
	return nil
}

type MMessage struct {
	TaskID               uint32   `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Function             uint32   `protobuf:"varint,3,opt,name=function,proto3" json:"function,omitempty"`
	ParNo                uint32   `protobuf:"varint,4,opt,name=parNo,proto3" json:"parNo,omitempty"`
	Params               []uint32 `protobuf:"varint,6,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MMessage) Reset()         { *m = MMessage{} }
func (m *MMessage) String() string { return proto.CompactTextString(m) }
func (*MMessage) ProtoMessage()    {}
func (*MMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{6}
}

func (m *MMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MMessage.Unmarshal(m, b)
}
func (m *MMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MMessage.Marshal(b, m, deterministic)
}
func (m *MMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MMessage.Merge(m, src)
}
func (m *MMessage) XXX_Size() int {
	return xxx_messageInfo_MMessage.Size(m)
}
func (m *MMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MMessage proto.InternalMessageInfo

func (m *MMessage) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

func (m *MMessage) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MMessage) GetFunction() uint32 {
	if m != nil {
		return m.Function
	}
	return 0
}

func (m *MMessage) GetParNo() uint32 {
	if m != nil {
		return m.ParNo
	}
	return 0
}

func (m *MMessage) GetParams() []uint32 {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateReq)(nil), "go.micro.srv.agv.order.UpdateReq")
	proto.RegisterType((*Request)(nil), "go.micro.srv.agv.order.Request")
	proto.RegisterType((*CancelReq)(nil), "go.micro.srv.agv.order.CancelReq")
	proto.RegisterType((*Response)(nil), "go.micro.srv.agv.order.Response")
	proto.RegisterType((*Task)(nil), "go.micro.srv.agv.order.Task")
	proto.RegisterType((*QBMessage)(nil), "go.micro.srv.agv.order.QBMessage")
	proto.RegisterType((*MMessage)(nil), "go.micro.srv.agv.order.MMessage")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xea, 0xfc, 0xd8, 0x23, 0x2a, 0xd0, 0x0a, 0x15, 0x2b, 0x42, 0xc2, 0xf5, 0xa9, 0x27,
	0x23, 0x81, 0xc4, 0x03, 0xd0, 0x1e, 0xf0, 0x21, 0xa9, 0xba, 0x84, 0x07, 0xd8, 0xda, 0x43, 0x64,
	0xa5, 0xde, 0x75, 0x77, 0x37, 0x81, 0x5e, 0x79, 0x05, 0x5e, 0x96, 0x23, 0xda, 0x1f, 0x2f, 0x20,
	0xea, 0xc6, 0x97, 0x68, 0xbe, 0x9d, 0x6f, 0xbe, 0xf9, 0xb2, 0x33, 0x6b, 0x78, 0xd5, 0x49, 0xa1,
	0xc5, 0x5b, 0x21, 0x6b, 0x94, 0xee, 0xb7, 0xb0, 0x27, 0xe4, 0x6c, 0x2b, 0x8a, 0xb6, 0xa9, 0xa4,
	0x28, 0x94, 0x3c, 0x14, 0x6c, 0x7b, 0x28, 0x6c, 0x36, 0xbf, 0x86, 0xe4, 0x4b, 0x57, 0x33, 0x8d,
	0x14, 0xef, 0xc9, 0x4b, 0x98, 0x35, 0xbc, 0xc6, 0xef, 0xe9, 0x24, 0x9b, 0x5c, 0x9c, 0x52, 0x07,
	0xc8, 0x19, 0xcc, 0x3b, 0x26, 0xd9, 0x5a, 0xa4, 0x27, 0xf6, 0xd8, 0x23, 0xc3, 0x3e, 0xb0, 0xbb,
	0x3d, 0xa6, 0x91, 0x63, 0x5b, 0x90, 0x27, 0xb0, 0xa0, 0x78, 0xbf, 0x47, 0xa5, 0xf3, 0x73, 0x48,
	0x2e, 0x19, 0xaf, 0xf0, 0x6e, 0x50, 0x3b, 0xff, 0x00, 0x31, 0x45, 0xd5, 0x09, 0xae, 0x90, 0xbc,
	0x80, 0x48, 0xa2, 0xb2, 0xf9, 0x98, 0x9a, 0x90, 0xa4, 0xb0, 0x68, 0x51, 0x29, 0xb6, 0x45, 0xdb,
	0x3a, 0xa1, 0x3d, 0xcc, 0x6f, 0x61, 0xba, 0x61, 0x6a, 0x47, 0x08, 0x4c, 0xb5, 0x2a, 0x6b, 0x2f,
	0x6a, 0x63, 0xb2, 0x84, 0xb8, 0x93, 0x8d, 0x90, 0x8d, 0x7e, 0xf0, 0x8e, 0x03, 0x36, 0xfc, 0x66,
	0x87, 0x0f, 0xde, 0xb2, 0x8d, 0xfb, 0xff, 0xd7, 0xaa, 0x74, 0x9a, 0x45, 0x17, 0x33, 0xea, 0x51,
	0xfe, 0x73, 0x02, 0xc9, 0xcd, 0xc7, 0x95, 0xeb, 0x68, 0x58, 0x9a, 0xa9, 0x5d, 0x79, 0xe5, 0x7b,
	0x79, 0xe4, 0x1d, 0x5c, 0xf9, 0x4e, 0x36, 0xfe, 0xc7, 0x41, 0xf4, 0xbf, 0x83, 0x4a, 0xd4, 0x98,
	0x4e, 0x1d, 0xdf, 0xc4, 0xc1, 0xd5, 0xec, 0x51, 0x57, 0xf3, 0x2c, 0xea, 0x6f, 0xbd, 0x55, 0xf9,
	0x8f, 0x09, 0xc4, 0xab, 0x63, 0xa6, 0xc2, 0x65, 0x9f, 0xfc, 0x3d, 0xc8, 0x25, 0xc4, 0x5f, 0xf7,
	0xbc, 0xd2, 0x8d, 0xe0, 0xbd, 0xad, 0x1e, 0x9b, 0x8a, 0x8e, 0xc9, 0xb5, 0xf0, 0xbe, 0x1c, 0x18,
	0x32, 0xf1, 0xee, 0x57, 0x04, 0xb3, 0x6b, 0xb3, 0x3f, 0xa4, 0x84, 0xc5, 0x1a, 0xbf, 0xd9, 0x59,
	0xbc, 0x2e, 0x1e, 0xdf, 0xb1, 0xc2, 0x64, 0x97, 0xd9, 0x50, 0x36, 0xcc, 0xff, 0x06, 0xc0, 0xad,
	0x8b, 0x55, 0x3b, 0x1f, 0xe2, 0x87, 0x95, 0x1a, 0x27, 0xe9, 0xb6, 0xfb, 0x69, 0xc9, 0xf0, 0x02,
	0x46, 0x48, 0x6e, 0xe0, 0xf4, 0x33, 0xf2, 0xfa, 0xcf, 0x62, 0x0c, 0xaa, 0x06, 0xca, 0x08, 0x55,
	0x0a, 0xcf, 0x8c, 0x6a, 0x18, 0xec, 0x60, 0xc5, 0x6a, 0xbc, 0xe6, 0x06, 0x9e, 0x7f, 0x12, 0x4a,
	0x97, 0xea, 0x52, 0x70, 0x8e, 0x95, 0xc6, 0x9a, 0xbc, 0x19, 0x2e, 0xb2, 0x4f, 0xf6, 0xb8, 0xea,
	0xed, 0xdc, 0x7e, 0x4f, 0xde, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x97, 0x16, 0x12, 0x0a, 0x6a,
	0x04, 0x00, 0x00,
}
