// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/report/report.proto

package go_micro_srv_report

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskReportReq struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReportReq) Reset()         { *m = TaskReportReq{} }
func (m *TaskReportReq) String() string { return proto.CompactTextString(m) }
func (*TaskReportReq) ProtoMessage()    {}
func (*TaskReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{0}
}

func (m *TaskReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReportReq.Unmarshal(m, b)
}
func (m *TaskReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReportReq.Marshal(b, m, deterministic)
}
func (m *TaskReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReportReq.Merge(m, src)
}
func (m *TaskReportReq) XXX_Size() int {
	return xxx_messageInfo_TaskReportReq.Size(m)
}
func (m *TaskReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReportReq proto.InternalMessageInfo

func (m *TaskReportReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TaskReportReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *TaskReportReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TaskReportReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReportItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportItem) Reset()         { *m = ReportItem{} }
func (m *ReportItem) String() string { return proto.CompactTextString(m) }
func (*ReportItem) ProtoMessage()    {}
func (*ReportItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{1}
}

func (m *ReportItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportItem.Unmarshal(m, b)
}
func (m *ReportItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportItem.Marshal(b, m, deterministic)
}
func (m *ReportItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportItem.Merge(m, src)
}
func (m *ReportItem) XXX_Size() int {
	return xxx_messageInfo_ReportItem.Size(m)
}
func (m *ReportItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportItem.DiscardUnknown(m)
}

var xxx_messageInfo_ReportItem proto.InternalMessageInfo

func (m *ReportItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReportItem) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AgvReportItem struct {
	Items                []*ReportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	AgvID                uint32        `protobuf:"varint,3,opt,name=agvID,proto3" json:"agvID,omitempty"`
	MaxTime              uint32        `protobuf:"varint,6,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	MaxTimeID            uint32        `protobuf:"varint,7,opt,name=maxTimeID,proto3" json:"maxTimeID,omitempty"`
	MinTime              uint32        `protobuf:"varint,8,opt,name=minTime,proto3" json:"minTime,omitempty"`
	MinTimeID            uint32        `protobuf:"varint,9,opt,name=minTimeID,proto3" json:"minTimeID,omitempty"`
	AvgTime              float64       `protobuf:"fixed64,10,opt,name=avgTime,proto3" json:"avgTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AgvReportItem) Reset()         { *m = AgvReportItem{} }
func (m *AgvReportItem) String() string { return proto.CompactTextString(m) }
func (*AgvReportItem) ProtoMessage()    {}
func (*AgvReportItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{2}
}

func (m *AgvReportItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgvReportItem.Unmarshal(m, b)
}
func (m *AgvReportItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgvReportItem.Marshal(b, m, deterministic)
}
func (m *AgvReportItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgvReportItem.Merge(m, src)
}
func (m *AgvReportItem) XXX_Size() int {
	return xxx_messageInfo_AgvReportItem.Size(m)
}
func (m *AgvReportItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AgvReportItem.DiscardUnknown(m)
}

var xxx_messageInfo_AgvReportItem proto.InternalMessageInfo

func (m *AgvReportItem) GetItems() []*ReportItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *AgvReportItem) GetAgvID() uint32 {
	if m != nil {
		return m.AgvID
	}
	return 0
}

func (m *AgvReportItem) GetMaxTime() uint32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

func (m *AgvReportItem) GetMaxTimeID() uint32 {
	if m != nil {
		return m.MaxTimeID
	}
	return 0
}

func (m *AgvReportItem) GetMinTime() uint32 {
	if m != nil {
		return m.MinTime
	}
	return 0
}

func (m *AgvReportItem) GetMinTimeID() uint32 {
	if m != nil {
		return m.MinTimeID
	}
	return 0
}

func (m *AgvReportItem) GetAvgTime() float64 {
	if m != nil {
		return m.AvgTime
	}
	return 0
}

type ReportItems struct {
	Item                 []*ReportItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	TotalCount           uint32        `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Max                  uint32        `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Min                  uint32        `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	Avg                  float64       `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	MaxTime              uint32        `protobuf:"varint,6,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	MaxTimeID            uint32        `protobuf:"varint,7,opt,name=maxTimeID,proto3" json:"maxTimeID,omitempty"`
	MinTime              uint32        `protobuf:"varint,8,opt,name=minTime,proto3" json:"minTime,omitempty"`
	MinTimeID            uint32        `protobuf:"varint,9,opt,name=minTimeID,proto3" json:"minTimeID,omitempty"`
	AvgTime              float64       `protobuf:"fixed64,10,opt,name=avgTime,proto3" json:"avgTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReportItems) Reset()         { *m = ReportItems{} }
func (m *ReportItems) String() string { return proto.CompactTextString(m) }
func (*ReportItems) ProtoMessage()    {}
func (*ReportItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{3}
}

func (m *ReportItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportItems.Unmarshal(m, b)
}
func (m *ReportItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportItems.Marshal(b, m, deterministic)
}
func (m *ReportItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportItems.Merge(m, src)
}
func (m *ReportItems) XXX_Size() int {
	return xxx_messageInfo_ReportItems.Size(m)
}
func (m *ReportItems) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportItems.DiscardUnknown(m)
}

var xxx_messageInfo_ReportItems proto.InternalMessageInfo

func (m *ReportItems) GetItem() []*ReportItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ReportItems) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ReportItems) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ReportItems) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ReportItems) GetAvg() float64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

func (m *ReportItems) GetMaxTime() uint32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

func (m *ReportItems) GetMaxTimeID() uint32 {
	if m != nil {
		return m.MaxTimeID
	}
	return 0
}

func (m *ReportItems) GetMinTime() uint32 {
	if m != nil {
		return m.MinTime
	}
	return 0
}

func (m *ReportItems) GetMinTimeID() uint32 {
	if m != nil {
		return m.MinTimeID
	}
	return 0
}

func (m *ReportItems) GetAvgTime() float64 {
	if m != nil {
		return m.AvgTime
	}
	return 0
}

type AgvTaskReportReq struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	AgvIDs               []uint32 `protobuf:"varint,4,rep,packed,name=agvIDs,proto3" json:"agvIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgvTaskReportReq) Reset()         { *m = AgvTaskReportReq{} }
func (m *AgvTaskReportReq) String() string { return proto.CompactTextString(m) }
func (*AgvTaskReportReq) ProtoMessage()    {}
func (*AgvTaskReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{4}
}

func (m *AgvTaskReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgvTaskReportReq.Unmarshal(m, b)
}
func (m *AgvTaskReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgvTaskReportReq.Marshal(b, m, deterministic)
}
func (m *AgvTaskReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgvTaskReportReq.Merge(m, src)
}
func (m *AgvTaskReportReq) XXX_Size() int {
	return xxx_messageInfo_AgvTaskReportReq.Size(m)
}
func (m *AgvTaskReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgvTaskReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgvTaskReportReq proto.InternalMessageInfo

func (m *AgvTaskReportReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *AgvTaskReportReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *AgvTaskReportReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AgvTaskReportReq) GetAgvIDs() []uint32 {
	if m != nil {
		return m.AgvIDs
	}
	return nil
}

type AgvTaskReportItems struct {
	Items                []*AgvReportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount           uint32           `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Max                  uint32           `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Min                  uint32           `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	Avg                  float64          `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AgvTaskReportItems) Reset()         { *m = AgvTaskReportItems{} }
func (m *AgvTaskReportItems) String() string { return proto.CompactTextString(m) }
func (*AgvTaskReportItems) ProtoMessage()    {}
func (*AgvTaskReportItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{5}
}

func (m *AgvTaskReportItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgvTaskReportItems.Unmarshal(m, b)
}
func (m *AgvTaskReportItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgvTaskReportItems.Marshal(b, m, deterministic)
}
func (m *AgvTaskReportItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgvTaskReportItems.Merge(m, src)
}
func (m *AgvTaskReportItems) XXX_Size() int {
	return xxx_messageInfo_AgvTaskReportItems.Size(m)
}
func (m *AgvTaskReportItems) XXX_DiscardUnknown() {
	xxx_messageInfo_AgvTaskReportItems.DiscardUnknown(m)
}

var xxx_messageInfo_AgvTaskReportItems proto.InternalMessageInfo

func (m *AgvTaskReportItems) GetItems() []*AgvReportItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *AgvTaskReportItems) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *AgvTaskReportItems) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *AgvTaskReportItems) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *AgvTaskReportItems) GetAvg() float64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

type MaterialReportReq struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaterialReportReq) Reset()         { *m = MaterialReportReq{} }
func (m *MaterialReportReq) String() string { return proto.CompactTextString(m) }
func (*MaterialReportReq) ProtoMessage()    {}
func (*MaterialReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{6}
}

func (m *MaterialReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialReportReq.Unmarshal(m, b)
}
func (m *MaterialReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialReportReq.Marshal(b, m, deterministic)
}
func (m *MaterialReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialReportReq.Merge(m, src)
}
func (m *MaterialReportReq) XXX_Size() int {
	return xxx_messageInfo_MaterialReportReq.Size(m)
}
func (m *MaterialReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialReportReq proto.InternalMessageInfo

func (m *MaterialReportReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *MaterialReportReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *MaterialReportReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MaterialReportReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskReportReq)(nil), "go.micro.srv.report.TaskReportReq")
	proto.RegisterType((*ReportItem)(nil), "go.micro.srv.report.ReportItem")
	proto.RegisterType((*AgvReportItem)(nil), "go.micro.srv.report.AgvReportItem")
	proto.RegisterType((*ReportItems)(nil), "go.micro.srv.report.ReportItems")
	proto.RegisterType((*AgvTaskReportReq)(nil), "go.micro.srv.report.AgvTaskReportReq")
	proto.RegisterType((*AgvTaskReportItems)(nil), "go.micro.srv.report.AgvTaskReportItems")
	proto.RegisterType((*MaterialReportReq)(nil), "go.micro.srv.report.MaterialReportReq")
}

func init() { proto.RegisterFile("proto/report/report.proto", fileDescriptor_db08199be84e208e) }

var fileDescriptor_db08199be84e208e = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4d, 0x8b, 0x14, 0x31,
	0x10, 0x25, 0xf3, 0xb5, 0x4e, 0x2d, 0x81, 0xd9, 0x28, 0x12, 0x45, 0xb4, 0x69, 0x50, 0xfb, 0xd4,
	0xc2, 0x2e, 0x8a, 0xd7, 0xc5, 0x81, 0x61, 0x0e, 0x5e, 0xe2, 0x7a, 0xf4, 0x90, 0xed, 0x0d, 0x4d,
	0xe3, 0x76, 0x67, 0x4c, 0x62, 0x58, 0xff, 0x8e, 0x78, 0xf1, 0x8f, 0xf9, 0x3b, 0x24, 0x95, 0x6e,
	0x7b, 0x1a, 0x5b, 0xc6, 0xcb, 0x8a, 0xa7, 0xa9, 0xf7, 0x52, 0x2f, 0x95, 0x7a, 0x55, 0xd3, 0xf0,
	0x60, 0x67, 0xb4, 0xd3, 0x2f, 0x8c, 0xda, 0x69, 0xe3, 0xda, 0x9f, 0x1c, 0x39, 0x76, 0xb7, 0xd4,
	0x79, 0x5d, 0x15, 0x46, 0xe7, 0xd6, 0xf8, 0x3c, 0x1e, 0xa5, 0x1a, 0xe8, 0x85, 0xb4, 0x1f, 0x05,
	0x22, 0xa1, 0x3e, 0xb1, 0x47, 0xb0, 0xb4, 0x4e, 0x1a, 0x77, 0x51, 0xd5, 0x8a, 0x93, 0x84, 0x64,
	0x4b, 0xd1, 0x13, 0x8c, 0xc3, 0x91, 0x6a, 0xae, 0xf0, 0x6c, 0x82, 0x67, 0x1d, 0x64, 0x0c, 0x66,
	0x85, 0xbe, 0x52, 0x7c, 0x8a, 0x34, 0xc6, 0x81, 0x73, 0x5f, 0x76, 0x8a, 0xcf, 0x12, 0x92, 0x51,
	0x81, 0x71, 0xfa, 0x0a, 0x20, 0x16, 0xdb, 0x3a, 0x55, 0x87, 0x8c, 0x46, 0xfe, 0x2a, 0x84, 0x31,
	0xbb, 0x07, 0xf3, 0x42, 0x7f, 0x6e, 0x1c, 0x56, 0xa0, 0x22, 0x82, 0xf4, 0x07, 0x01, 0x7a, 0x5e,
	0xfa, 0x3d, 0xed, 0x4b, 0x98, 0x57, 0x4e, 0xd5, 0x96, 0x93, 0x64, 0x9a, 0x1d, 0x9f, 0x3e, 0xc9,
	0x47, 0xfa, 0xcb, 0xfb, 0x7c, 0x11, 0xb3, 0xc3, 0xf5, 0xb2, 0xf4, 0xdb, 0x35, 0xbe, 0x94, 0x8a,
	0x08, 0x42, 0x63, 0xb5, 0xbc, 0xc1, 0xc6, 0x16, 0xc8, 0x77, 0x30, 0x18, 0xd2, 0x86, 0xdb, 0x35,
	0x3f, 0xc2, 0xb3, 0x9e, 0x40, 0x5d, 0xd5, 0xa0, 0xee, 0x4e, 0xab, 0x8b, 0x10, 0x75, 0x31, 0xdc,
	0xae, 0xf9, 0xb2, 0xd5, 0x75, 0x44, 0xd0, 0x49, 0x5f, 0xa2, 0x0e, 0x12, 0x92, 0x11, 0xd1, 0xc1,
	0xf4, 0xeb, 0x04, 0x8e, 0xfb, 0x57, 0x5b, 0x76, 0x06, 0xb3, 0xf0, 0xf0, 0xbf, 0xed, 0x12, 0x93,
	0xd9, 0x63, 0x00, 0xa7, 0x9d, 0xbc, 0x7e, 0xb3, 0x67, 0xe4, 0x1e, 0xc3, 0x56, 0x30, 0xad, 0xe5,
	0x4d, 0x6b, 0x41, 0x08, 0x91, 0xa9, 0x9a, 0x76, 0x54, 0x21, 0x0c, 0x8c, 0xf4, 0x25, 0x9f, 0xe3,
	0xf3, 0x42, 0xf8, 0x1f, 0x99, 0xe4, 0x61, 0x75, 0x5e, 0xfa, 0xdb, 0xdb, 0xdc, 0xfb, 0xb0, 0xc0,
	0xbd, 0xb0, 0x7c, 0x96, 0x4c, 0x33, 0x2a, 0x5a, 0x94, 0x7e, 0x23, 0xc0, 0x06, 0x85, 0xe3, 0x8c,
	0x5e, 0x0f, 0x57, 0x31, 0x1d, 0x1d, 0xd2, 0x60, 0x7b, 0xbb, 0x6d, 0xbc, 0x95, 0x41, 0xa5, 0x16,
	0x4e, 0xde, 0x4a, 0xa7, 0x4c, 0x25, 0xaf, 0xff, 0xd9, 0x3f, 0xfb, 0xf4, 0xfb, 0x04, 0x68, 0xac,
	0xf6, 0x4e, 0x19, 0x5f, 0x15, 0x8a, 0xbd, 0x07, 0xba, 0x51, 0xae, 0x37, 0x8b, 0x8d, 0x1b, 0x33,
	0x18, 0xe3, 0xc3, 0xe4, 0xc0, 0x86, 0x5b, 0x76, 0x09, 0xab, 0x8d, 0x72, 0x83, 0x31, 0xb0, 0xa7,
	0x7f, 0xb2, 0x7c, 0x78, 0xf9, 0xf3, 0xc3, 0x69, 0xb1, 0xc6, 0x07, 0x38, 0xd9, 0x28, 0x37, 0x34,
	0x91, 0x3d, 0x1b, 0x55, 0xff, 0xe6, 0xf4, 0xe1, 0x16, 0x2e, 0x17, 0xf8, 0x49, 0x3e, 0xfb, 0x19,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0xcc, 0xfb, 0x53, 0xaf, 0x05, 0x00, 0x00,
}
