// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/config/config.proto

package go_micro_srv_config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Warehouse struct {
	Ikey                 string   `protobuf:"bytes,1,opt,name=ikey,proto3" json:"ikey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Longitude            uint32   `protobuf:"varint,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             uint32   `protobuf:"varint,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	FloorNumber          uint32   `protobuf:"varint,6,opt,name=floorNumber,proto3" json:"floorNumber,omitempty"`
	Length               uint32   `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	Width                uint32   `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Warehouse) Reset()         { *m = Warehouse{} }
func (m *Warehouse) String() string { return proto.CompactTextString(m) }
func (*Warehouse) ProtoMessage()    {}
func (*Warehouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{0}
}

func (m *Warehouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Warehouse.Unmarshal(m, b)
}
func (m *Warehouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Warehouse.Marshal(b, m, deterministic)
}
func (m *Warehouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Warehouse.Merge(m, src)
}
func (m *Warehouse) XXX_Size() int {
	return xxx_messageInfo_Warehouse.Size(m)
}
func (m *Warehouse) XXX_DiscardUnknown() {
	xxx_messageInfo_Warehouse.DiscardUnknown(m)
}

var xxx_messageInfo_Warehouse proto.InternalMessageInfo

func (m *Warehouse) GetIkey() string {
	if m != nil {
		return m.Ikey
	}
	return ""
}

func (m *Warehouse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Warehouse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Warehouse) GetLongitude() uint32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Warehouse) GetLatitude() uint32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Warehouse) GetFloorNumber() uint32 {
	if m != nil {
		return m.FloorNumber
	}
	return 0
}

func (m *Warehouse) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Warehouse) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type ScriptButton struct {
	Ikey                 string   `protobuf:"bytes,1,opt,name=ikey,proto3" json:"ikey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScriptId             uint32   `protobuf:"varint,3,opt,name=scriptId,proto3" json:"scriptId,omitempty"`
	Parameters           string   `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScriptButton) Reset()         { *m = ScriptButton{} }
func (m *ScriptButton) String() string { return proto.CompactTextString(m) }
func (*ScriptButton) ProtoMessage()    {}
func (*ScriptButton) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{1}
}

func (m *ScriptButton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptButton.Unmarshal(m, b)
}
func (m *ScriptButton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptButton.Marshal(b, m, deterministic)
}
func (m *ScriptButton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptButton.Merge(m, src)
}
func (m *ScriptButton) XXX_Size() int {
	return xxx_messageInfo_ScriptButton.Size(m)
}
func (m *ScriptButton) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptButton.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptButton proto.InternalMessageInfo

func (m *ScriptButton) GetIkey() string {
	if m != nil {
		return m.Ikey
	}
	return ""
}

func (m *ScriptButton) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScriptButton) GetScriptId() uint32 {
	if m != nil {
		return m.ScriptId
	}
	return 0
}

func (m *ScriptButton) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type ScriptButtons struct {
	Button               []*ScriptButton `protobuf:"bytes,1,rep,name=button,proto3" json:"button,omitempty"`
	TotalCount           uint32          `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ScriptButtons) Reset()         { *m = ScriptButtons{} }
func (m *ScriptButtons) String() string { return proto.CompactTextString(m) }
func (*ScriptButtons) ProtoMessage()    {}
func (*ScriptButtons) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{2}
}

func (m *ScriptButtons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptButtons.Unmarshal(m, b)
}
func (m *ScriptButtons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptButtons.Marshal(b, m, deterministic)
}
func (m *ScriptButtons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptButtons.Merge(m, src)
}
func (m *ScriptButtons) XXX_Size() int {
	return xxx_messageInfo_ScriptButtons.Size(m)
}
func (m *ScriptButtons) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptButtons.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptButtons proto.InternalMessageInfo

func (m *ScriptButtons) GetButton() []*ScriptButton {
	if m != nil {
		return m.Button
	}
	return nil
}

func (m *ScriptButtons) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type IkeyRequest struct {
	Ikey                 string   `protobuf:"bytes,1,opt,name=ikey,proto3" json:"ikey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IkeyRequest) Reset()         { *m = IkeyRequest{} }
func (m *IkeyRequest) String() string { return proto.CompactTextString(m) }
func (*IkeyRequest) ProtoMessage()    {}
func (*IkeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{5}
}

func (m *IkeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IkeyRequest.Unmarshal(m, b)
}
func (m *IkeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IkeyRequest.Marshal(b, m, deterministic)
}
func (m *IkeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IkeyRequest.Merge(m, src)
}
func (m *IkeyRequest) XXX_Size() int {
	return xxx_messageInfo_IkeyRequest.Size(m)
}
func (m *IkeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IkeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IkeyRequest proto.InternalMessageInfo

func (m *IkeyRequest) GetIkey() string {
	if m != nil {
		return m.Ikey
	}
	return ""
}

type Query struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f7e909880fb5ba3, []int{6}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Warehouse)(nil), "go.micro.srv.config.Warehouse")
	proto.RegisterType((*ScriptButton)(nil), "go.micro.srv.config.ScriptButton")
	proto.RegisterType((*ScriptButtons)(nil), "go.micro.srv.config.ScriptButtons")
	proto.RegisterType((*Request)(nil), "go.micro.srv.config.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.config.Response")
	proto.RegisterType((*IkeyRequest)(nil), "go.micro.srv.config.IkeyRequest")
	proto.RegisterType((*Query)(nil), "go.micro.srv.config.Query")
}

func init() { proto.RegisterFile("proto/config/config.proto", fileDescriptor_2f7e909880fb5ba3) }

var fileDescriptor_2f7e909880fb5ba3 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6b, 0xd4, 0x50,
	0x10, 0x25, 0xb6, 0xfb, 0x91, 0xd9, 0x86, 0x95, 0x51, 0x24, 0x86, 0x5a, 0xd2, 0x3c, 0xed, 0x53,
	0x84, 0x8a, 0x0f, 0x3e, 0x6a, 0x85, 0x52, 0x10, 0xa9, 0x77, 0xa9, 0x3e, 0xdf, 0xdd, 0x4c, 0xb3,
	0xb1, 0xd9, 0xdc, 0x78, 0xef, 0x4d, 0xa5, 0xbf, 0xd4, 0x47, 0xff, 0x8a, 0x64, 0xb2, 0x1f, 0xb1,
	0x44, 0xa2, 0xe0, 0xd3, 0xce, 0x39, 0x67, 0xe7, 0xcc, 0x1c, 0xe6, 0x12, 0x78, 0x5e, 0x6a, 0x65,
	0xd5, 0xcb, 0xa5, 0x2a, 0x6e, 0xb2, 0x74, 0xf3, 0x13, 0x33, 0x87, 0x4f, 0x52, 0x15, 0xaf, 0xb3,
	0xa5, 0x56, 0xb1, 0xd1, 0x77, 0x71, 0x23, 0x45, 0x3f, 0x1c, 0x70, 0xbf, 0x48, 0x4d, 0x2b, 0x55,
	0x19, 0x42, 0x84, 0xc3, 0xec, 0x96, 0xee, 0x7d, 0x27, 0x74, 0x66, 0xae, 0xe0, 0xba, 0xe6, 0x0a,
	0xb9, 0x26, 0xff, 0x51, 0xc3, 0xd5, 0x35, 0xfa, 0x30, 0x92, 0x49, 0xa2, 0xc9, 0x18, 0xff, 0x80,
	0xe9, 0x2d, 0xc4, 0x63, 0x70, 0x73, 0x55, 0xa4, 0x99, 0xad, 0x12, 0xf2, 0x0f, 0x43, 0x67, 0xe6,
	0x89, 0x3d, 0x81, 0x01, 0x8c, 0x73, 0x69, 0x1b, 0x71, 0xc0, 0xe2, 0x0e, 0x63, 0x08, 0x93, 0x9b,
	0x5c, 0x29, 0xfd, 0xb1, 0x5a, 0x2f, 0x48, 0xfb, 0x43, 0x96, 0xdb, 0x14, 0x3e, 0x83, 0x61, 0x4e,
	0x45, 0x6a, 0x57, 0xfe, 0x88, 0xc5, 0x0d, 0xc2, 0xa7, 0x30, 0xf8, 0x9e, 0x25, 0x76, 0xe5, 0x8f,
	0x99, 0x6e, 0x40, 0xa4, 0xe1, 0x68, 0xbe, 0xd4, 0x59, 0x69, 0xdf, 0x55, 0xd6, 0xaa, 0xe2, 0xaf,
	0xb3, 0x05, 0x30, 0x36, 0xdc, 0x77, 0x99, 0x70, 0x38, 0x4f, 0xec, 0x30, 0x9e, 0x00, 0x94, 0x52,
	0xcb, 0x35, 0x59, 0xd2, 0x86, 0xe3, 0xb9, 0xa2, 0xc5, 0x44, 0x5f, 0xc1, 0x6b, 0xcf, 0x34, 0xf8,
	0x06, 0x86, 0x0b, 0x2e, 0x7d, 0x27, 0x3c, 0x98, 0x4d, 0xce, 0x4e, 0xe3, 0x8e, 0x23, 0xc4, 0xed,
	0x1e, 0xb1, 0x69, 0xa8, 0x67, 0x59, 0x65, 0x65, 0x7e, 0xae, 0xaa, 0xc2, 0xf2, 0x86, 0x9e, 0x68,
	0x31, 0x91, 0x0b, 0x23, 0x41, 0xdf, 0x2a, 0x32, 0x36, 0x02, 0x18, 0x0b, 0x32, 0xa5, 0x2a, 0x0c,
	0x45, 0xa7, 0x30, 0xb9, 0xbc, 0xa5, 0xfb, 0x8d, 0xd4, 0x95, 0x3a, 0x7a, 0x0d, 0x83, 0x4f, 0x15,
	0x69, 0x8e, 0x5f, 0xca, 0x94, 0x58, 0xf4, 0x04, 0xd7, 0xf5, 0x69, 0x4b, 0xd2, 0x57, 0x35, 0xdd,
	0xcc, 0xdc, 0xc2, 0xb3, 0x9f, 0x87, 0xe0, 0x9d, 0xf3, 0xc2, 0x73, 0xd2, 0x77, 0xd9, 0x92, 0xf0,
	0x0a, 0xa6, 0xd7, 0x65, 0x22, 0x2d, 0xed, 0x5f, 0xd0, 0x49, 0x67, 0xc0, 0x9d, 0x1e, 0xbc, 0xe8,
	0xd4, 0xb7, 0xdb, 0xe3, 0x07, 0x38, 0xba, 0x20, 0xbb, 0xb7, 0x3b, 0xfe, 0xc3, 0xdf, 0x39, 0x5c,
	0xd0, 0x33, 0x0c, 0xe7, 0x30, 0x7d, 0x9b, 0x24, 0xbf, 0xbd, 0x82, 0xfe, 0x03, 0xf4, 0xad, 0xf8,
	0x19, 0xb0, 0x09, 0xfd, 0x9f, 0x7d, 0xaf, 0x01, 0xdf, 0x53, 0x4e, 0x0f, 0x7c, 0xc3, 0xce, 0xa6,
	0xd6, 0x85, 0xfb, 0xd7, 0x9d, 0x5e, 0x90, 0xfd, 0x47, 0xcf, 0xfe, 0x34, 0x28, 0xe0, 0xf1, 0x03,
	0x5f, 0x83, 0x41, 0x67, 0x1b, 0xbf, 0xb5, 0x20, 0xea, 0xb5, 0x34, 0x8b, 0x21, 0x7f, 0xa8, 0x5e,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xbe, 0xd3, 0xc0, 0xc5, 0x04, 0x00, 0x00,
}
