// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rack/rack.proto

package go_micro_srv_rack

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RackType struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RackType) Reset()         { *m = RackType{} }
func (m *RackType) String() string { return proto.CompactTextString(m) }
func (*RackType) ProtoMessage()    {}
func (*RackType) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{0}
}

func (m *RackType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RackType.Unmarshal(m, b)
}
func (m *RackType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RackType.Marshal(b, m, deterministic)
}
func (m *RackType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RackType.Merge(m, src)
}
func (m *RackType) XXX_Size() int {
	return xxx_messageInfo_RackType.Size(m)
}
func (m *RackType) XXX_DiscardUnknown() {
	xxx_messageInfo_RackType.DiscardUnknown(m)
}

var xxx_messageInfo_RackType proto.InternalMessageInfo

func (m *RackType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RackType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Cell 储位
type Cell struct {
	// 储位ID
	Id uint32 `protobuf:"varint,21,opt,name=id,proto3" json:"id,omitempty"`
	// 储位编码
	Tag string `protobuf:"bytes,22,opt,name=tag,proto3" json:"tag,omitempty"`
	// 储位名称
	Name string `protobuf:"bytes,23,opt,name=name,proto3" json:"name,omitempty"`
	// 储位所在货架
	RackID uint32 `protobuf:"varint,24,opt,name=rackID,proto3" json:"rackID,omitempty"`
	Length int32  `protobuf:"varint,25,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32  `protobuf:"varint,26,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,27,opt,name=height,proto3" json:"height,omitempty"`
	// 储位在货架的哪一层
	Layer int32 `protobuf:"varint,28,opt,name=layer,proto3" json:"layer,omitempty"`
	// 储位在货架上的编号
	CellCode int32 `protobuf:"varint,29,opt,name=cellCode,proto3" json:"cellCode,omitempty"`
	// 是否禁用
	IsValid bool `protobuf:"varint,30,opt,name=isValid,proto3" json:"isValid,omitempty"`
	// 存放的物料对于的编号
	MaterialID uint32 `protobuf:"varint,31,opt,name=materialID,proto3" json:"materialID,omitempty"`
	// cell类型id
	Type uint32 `protobuf:"varint,32,opt,name=type,proto3" json:"type,omitempty"`
	//是否被占用
	IsOccupied           bool     `protobuf:"varint,33,opt,name=isOccupied,proto3" json:"isOccupied,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{1}
}

func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (m *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(m, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cell) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Cell) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cell) GetRackID() uint32 {
	if m != nil {
		return m.RackID
	}
	return 0
}

func (m *Cell) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Cell) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Cell) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Cell) GetLayer() int32 {
	if m != nil {
		return m.Layer
	}
	return 0
}

func (m *Cell) GetCellCode() int32 {
	if m != nil {
		return m.CellCode
	}
	return 0
}

func (m *Cell) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *Cell) GetMaterialID() uint32 {
	if m != nil {
		return m.MaterialID
	}
	return 0
}

func (m *Cell) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Cell) GetIsOccupied() bool {
	if m != nil {
		return m.IsOccupied
	}
	return false
}

type Rack struct {
	// 货架编码
	Id   uint32 `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,30,opt,name=name,proto3" json:"name,omitempty"`
	// 货架类型
	Type *RackType `protobuf:"bytes,21,opt,name=type,proto3" json:"type,omitempty"`
	// 是否禁用
	IsValid bool  `protobuf:"varint,22,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Length  int32 `protobuf:"varint,23,opt,name=length,proto3" json:"length,omitempty"`
	Width   int32 `protobuf:"varint,24,opt,name=width,proto3" json:"width,omitempty"`
	Height  int32 `protobuf:"varint,25,opt,name=height,proto3" json:"height,omitempty"`
	// 所在货位
	Racklot int32 `protobuf:"varint,26,opt,name=racklot,proto3" json:"racklot,omitempty"`
	// 货架层数
	Layers int32 `protobuf:"varint,27,opt,name=layers,proto3" json:"layers,omitempty"`
	// 货架状态(空、可用、被占用、满等)
	Status int32 `protobuf:"varint,31,opt,name=status,proto3" json:"status,omitempty"`
	// 拣货面(A、B两面或者只有一面)
	PickingSurface int32  `protobuf:"varint,32,opt,name=pickingSurface,proto3" json:"pickingSurface,omitempty"`
	Description    string `protobuf:"bytes,28,opt,name=description,proto3" json:"description,omitempty"`
	// 货架储位
	Cells []*Cell `protobuf:"bytes,29,rep,name=cells,proto3" json:"cells,omitempty"`
	//是否被占用
	IsOccupied           bool     `protobuf:"varint,33,opt,name=isOccupied,proto3" json:"isOccupied,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rack) Reset()         { *m = Rack{} }
func (m *Rack) String() string { return proto.CompactTextString(m) }
func (*Rack) ProtoMessage()    {}
func (*Rack) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{2}
}

func (m *Rack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rack.Unmarshal(m, b)
}
func (m *Rack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rack.Marshal(b, m, deterministic)
}
func (m *Rack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rack.Merge(m, src)
}
func (m *Rack) XXX_Size() int {
	return xxx_messageInfo_Rack.Size(m)
}
func (m *Rack) XXX_DiscardUnknown() {
	xxx_messageInfo_Rack.DiscardUnknown(m)
}

var xxx_messageInfo_Rack proto.InternalMessageInfo

func (m *Rack) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rack) GetType() *RackType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Rack) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *Rack) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Rack) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Rack) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Rack) GetRacklot() int32 {
	if m != nil {
		return m.Racklot
	}
	return 0
}

func (m *Rack) GetLayers() int32 {
	if m != nil {
		return m.Layers
	}
	return 0
}

func (m *Rack) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Rack) GetPickingSurface() int32 {
	if m != nil {
		return m.PickingSurface
	}
	return 0
}

func (m *Rack) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Rack) GetCells() []*Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *Rack) GetIsOccupied() bool {
	if m != nil {
		return m.IsOccupied
	}
	return false
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type RackIDReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RackIDReq) Reset()         { *m = RackIDReq{} }
func (m *RackIDReq) String() string { return proto.CompactTextString(m) }
func (*RackIDReq) ProtoMessage()    {}
func (*RackIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{4}
}

func (m *RackIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RackIDReq.Unmarshal(m, b)
}
func (m *RackIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RackIDReq.Marshal(b, m, deterministic)
}
func (m *RackIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RackIDReq.Merge(m, src)
}
func (m *RackIDReq) XXX_Size() int {
	return xxx_messageInfo_RackIDReq.Size(m)
}
func (m *RackIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RackIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_RackIDReq proto.InternalMessageInfo

func (m *RackIDReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CellIDReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellIDReq) Reset()         { *m = CellIDReq{} }
func (m *CellIDReq) String() string { return proto.CompactTextString(m) }
func (*CellIDReq) ProtoMessage()    {}
func (*CellIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{5}
}

func (m *CellIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellIDReq.Unmarshal(m, b)
}
func (m *CellIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellIDReq.Marshal(b, m, deterministic)
}
func (m *CellIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellIDReq.Merge(m, src)
}
func (m *CellIDReq) XXX_Size() int {
	return xxx_messageInfo_CellIDReq.Size(m)
}
func (m *CellIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CellIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_CellIDReq proto.InternalMessageInfo

func (m *CellIDReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateRackReq struct {
	Id                   uint32    `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *RackType `protobuf:"bytes,22,opt,name=type,proto3" json:"type,omitempty"`
	IsValid              bool      `protobuf:"varint,23,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Length               int32     `protobuf:"varint,24,opt,name=length,proto3" json:"length,omitempty"`
	Width                int32     `protobuf:"varint,25,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32     `protobuf:"varint,26,opt,name=height,proto3" json:"height,omitempty"`
	Layers               int32     `protobuf:"varint,27,opt,name=layers,proto3" json:"layers,omitempty"`
	PickingSurface       int32     `protobuf:"varint,28,opt,name=pickingSurface,proto3" json:"pickingSurface,omitempty"`
	Description          string    `protobuf:"bytes,29,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateRackReq) Reset()         { *m = UpdateRackReq{} }
func (m *UpdateRackReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRackReq) ProtoMessage()    {}
func (*UpdateRackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{6}
}

func (m *UpdateRackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRackReq.Unmarshal(m, b)
}
func (m *UpdateRackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRackReq.Marshal(b, m, deterministic)
}
func (m *UpdateRackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRackReq.Merge(m, src)
}
func (m *UpdateRackReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRackReq.Size(m)
}
func (m *UpdateRackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRackReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRackReq proto.InternalMessageInfo

func (m *UpdateRackReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRackReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRackReq) GetType() *RackType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *UpdateRackReq) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *UpdateRackReq) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UpdateRackReq) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *UpdateRackReq) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UpdateRackReq) GetLayers() int32 {
	if m != nil {
		return m.Layers
	}
	return 0
}

func (m *UpdateRackReq) GetPickingSurface() int32 {
	if m != nil {
		return m.PickingSurface
	}
	return 0
}

func (m *UpdateRackReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GraphqlQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlQuery) Reset()         { *m = GraphqlQuery{} }
func (m *GraphqlQuery) String() string { return proto.CompactTextString(m) }
func (*GraphqlQuery) ProtoMessage()    {}
func (*GraphqlQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{7}
}

func (m *GraphqlQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlQuery.Unmarshal(m, b)
}
func (m *GraphqlQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlQuery.Marshal(b, m, deterministic)
}
func (m *GraphqlQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlQuery.Merge(m, src)
}
func (m *GraphqlQuery) XXX_Size() int {
	return xxx_messageInfo_GraphqlQuery.Size(m)
}
func (m *GraphqlQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlQuery proto.InternalMessageInfo

func (m *GraphqlQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GraphqlRacks struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphqlRacks) Reset()         { *m = GraphqlRacks{} }
func (m *GraphqlRacks) String() string { return proto.CompactTextString(m) }
func (*GraphqlRacks) ProtoMessage()    {}
func (*GraphqlRacks) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{8}
}

func (m *GraphqlRacks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphqlRacks.Unmarshal(m, b)
}
func (m *GraphqlRacks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphqlRacks.Marshal(b, m, deterministic)
}
func (m *GraphqlRacks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphqlRacks.Merge(m, src)
}
func (m *GraphqlRacks) XXX_Size() int {
	return xxx_messageInfo_GraphqlRacks.Size(m)
}
func (m *GraphqlRacks) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphqlRacks.DiscardUnknown(m)
}

var xxx_messageInfo_GraphqlRacks proto.InternalMessageInfo

func (m *GraphqlRacks) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type Query struct {
	Limit                uint32       `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32       `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page                 uint32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32       `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	QueryString          string       `protobuf:"bytes,5,opt,name=queryString,proto3" json:"queryString,omitempty"`
	QueryParams          []*Parameter `protobuf:"bytes,6,rep,name=queryParams,proto3" json:"queryParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{9}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Query) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *Query) GetQueryParams() []*Parameter {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

type Racks struct {
	Racks                []*Rack  `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	Totals               uint32   `protobuf:"varint,4,opt,name=totals,proto3" json:"totals,omitempty"`
	Totalpages           uint32   `protobuf:"varint,2,opt,name=totalpages,proto3" json:"totalpages,omitempty"`
	Currpages            uint32   `protobuf:"varint,3,opt,name=currpages,proto3" json:"currpages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Racks) Reset()         { *m = Racks{} }
func (m *Racks) String() string { return proto.CompactTextString(m) }
func (*Racks) ProtoMessage()    {}
func (*Racks) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{10}
}

func (m *Racks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Racks.Unmarshal(m, b)
}
func (m *Racks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Racks.Marshal(b, m, deterministic)
}
func (m *Racks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Racks.Merge(m, src)
}
func (m *Racks) XXX_Size() int {
	return xxx_messageInfo_Racks.Size(m)
}
func (m *Racks) XXX_DiscardUnknown() {
	xxx_messageInfo_Racks.DiscardUnknown(m)
}

var xxx_messageInfo_Racks proto.InternalMessageInfo

func (m *Racks) GetRacks() []*Rack {
	if m != nil {
		return m.Racks
	}
	return nil
}

func (m *Racks) GetTotals() uint32 {
	if m != nil {
		return m.Totals
	}
	return 0
}

func (m *Racks) GetTotalpages() uint32 {
	if m != nil {
		return m.Totalpages
	}
	return 0
}

func (m *Racks) GetCurrpages() uint32 {
	if m != nil {
		return m.Currpages
	}
	return 0
}

type TypeReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeReq) Reset()         { *m = TypeReq{} }
func (m *TypeReq) String() string { return proto.CompactTextString(m) }
func (*TypeReq) ProtoMessage()    {}
func (*TypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{11}
}

func (m *TypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeReq.Unmarshal(m, b)
}
func (m *TypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeReq.Marshal(b, m, deterministic)
}
func (m *TypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeReq.Merge(m, src)
}
func (m *TypeReq) XXX_Size() int {
	return xxx_messageInfo_TypeReq.Size(m)
}
func (m *TypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TypeReq proto.InternalMessageInfo

func (m *TypeReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TypeReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type LayerNumsReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayerNumsReq) Reset()         { *m = LayerNumsReq{} }
func (m *LayerNumsReq) String() string { return proto.CompactTextString(m) }
func (*LayerNumsReq) ProtoMessage()    {}
func (*LayerNumsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{12}
}

func (m *LayerNumsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayerNumsReq.Unmarshal(m, b)
}
func (m *LayerNumsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayerNumsReq.Marshal(b, m, deterministic)
}
func (m *LayerNumsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayerNumsReq.Merge(m, src)
}
func (m *LayerNumsReq) XXX_Size() int {
	return xxx_messageInfo_LayerNumsReq.Size(m)
}
func (m *LayerNumsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LayerNumsReq.DiscardUnknown(m)
}

var xxx_messageInfo_LayerNumsReq proto.InternalMessageInfo

func (m *LayerNumsReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RackIDsReq struct {
	Ids                  []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RackIDsReq) Reset()         { *m = RackIDsReq{} }
func (m *RackIDsReq) String() string { return proto.CompactTextString(m) }
func (*RackIDsReq) ProtoMessage()    {}
func (*RackIDsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{13}
}

func (m *RackIDsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RackIDsReq.Unmarshal(m, b)
}
func (m *RackIDsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RackIDsReq.Marshal(b, m, deterministic)
}
func (m *RackIDsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RackIDsReq.Merge(m, src)
}
func (m *RackIDsReq) XXX_Size() int {
	return xxx_messageInfo_RackIDsReq.Size(m)
}
func (m *RackIDsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RackIDsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RackIDsReq proto.InternalMessageInfo

func (m *RackIDsReq) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type CellsReq struct {
	RackID               uint32   `protobuf:"varint,1,opt,name=rackID,proto3" json:"rackID,omitempty"`
	Cells                []*Cell  `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellsReq) Reset()         { *m = CellsReq{} }
func (m *CellsReq) String() string { return proto.CompactTextString(m) }
func (*CellsReq) ProtoMessage()    {}
func (*CellsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{14}
}

func (m *CellsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellsReq.Unmarshal(m, b)
}
func (m *CellsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellsReq.Marshal(b, m, deterministic)
}
func (m *CellsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellsReq.Merge(m, src)
}
func (m *CellsReq) XXX_Size() int {
	return xxx_messageInfo_CellsReq.Size(m)
}
func (m *CellsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CellsReq.DiscardUnknown(m)
}

var xxx_messageInfo_CellsReq proto.InternalMessageInfo

func (m *CellsReq) GetRackID() uint32 {
	if m != nil {
		return m.RackID
	}
	return 0
}

func (m *CellsReq) GetCells() []*Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

type CellIDsReq struct {
	RackID               uint32   `protobuf:"varint,1,opt,name=rackID,proto3" json:"rackID,omitempty"`
	CellIDs              []uint32 `protobuf:"varint,2,rep,packed,name=cellIDs,proto3" json:"cellIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellIDsReq) Reset()         { *m = CellIDsReq{} }
func (m *CellIDsReq) String() string { return proto.CompactTextString(m) }
func (*CellIDsReq) ProtoMessage()    {}
func (*CellIDsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{15}
}

func (m *CellIDsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellIDsReq.Unmarshal(m, b)
}
func (m *CellIDsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellIDsReq.Marshal(b, m, deterministic)
}
func (m *CellIDsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellIDsReq.Merge(m, src)
}
func (m *CellIDsReq) XXX_Size() int {
	return xxx_messageInfo_CellIDsReq.Size(m)
}
func (m *CellIDsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CellIDsReq.DiscardUnknown(m)
}

var xxx_messageInfo_CellIDsReq proto.InternalMessageInfo

func (m *CellIDsReq) GetRackID() uint32 {
	if m != nil {
		return m.RackID
	}
	return 0
}

func (m *CellIDsReq) GetCellIDs() []uint32 {
	if m != nil {
		return m.CellIDs
	}
	return nil
}

type RacklotReq struct {
	RackID               uint32   `protobuf:"varint,1,opt,name=rackID,proto3" json:"rackID,omitempty"`
	RacklotID            uint32   `protobuf:"varint,2,opt,name=racklotID,proto3" json:"racklotID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RacklotReq) Reset()         { *m = RacklotReq{} }
func (m *RacklotReq) String() string { return proto.CompactTextString(m) }
func (*RacklotReq) ProtoMessage()    {}
func (*RacklotReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{16}
}

func (m *RacklotReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RacklotReq.Unmarshal(m, b)
}
func (m *RacklotReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RacklotReq.Marshal(b, m, deterministic)
}
func (m *RacklotReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RacklotReq.Merge(m, src)
}
func (m *RacklotReq) XXX_Size() int {
	return xxx_messageInfo_RacklotReq.Size(m)
}
func (m *RacklotReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RacklotReq.DiscardUnknown(m)
}

var xxx_messageInfo_RacklotReq proto.InternalMessageInfo

func (m *RacklotReq) GetRackID() uint32 {
	if m != nil {
		return m.RackID
	}
	return 0
}

func (m *RacklotReq) GetRacklotID() uint32 {
	if m != nil {
		return m.RacklotID
	}
	return 0
}

type MaterialReq struct {
	RackID               uint32   `protobuf:"varint,1,opt,name=rackID,proto3" json:"rackID,omitempty"`
	CellID               uint32   `protobuf:"varint,2,opt,name=cellID,proto3" json:"cellID,omitempty"`
	MaterialID           uint32   `protobuf:"varint,3,opt,name=materialID,proto3" json:"materialID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaterialReq) Reset()         { *m = MaterialReq{} }
func (m *MaterialReq) String() string { return proto.CompactTextString(m) }
func (*MaterialReq) ProtoMessage()    {}
func (*MaterialReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{17}
}

func (m *MaterialReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialReq.Unmarshal(m, b)
}
func (m *MaterialReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialReq.Marshal(b, m, deterministic)
}
func (m *MaterialReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialReq.Merge(m, src)
}
func (m *MaterialReq) XXX_Size() int {
	return xxx_messageInfo_MaterialReq.Size(m)
}
func (m *MaterialReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialReq.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialReq proto.InternalMessageInfo

func (m *MaterialReq) GetRackID() uint32 {
	if m != nil {
		return m.RackID
	}
	return 0
}

func (m *MaterialReq) GetCellID() uint32 {
	if m != nil {
		return m.CellID
	}
	return 0
}

func (m *MaterialReq) GetMaterialID() uint32 {
	if m != nil {
		return m.MaterialID
	}
	return 0
}

type Parameter struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f24b60e0ed6c04, []int{18}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*RackType)(nil), "go.micro.srv.rack.RackType")
	proto.RegisterType((*Cell)(nil), "go.micro.srv.rack.Cell")
	proto.RegisterType((*Rack)(nil), "go.micro.srv.rack.Rack")
	proto.RegisterType((*Response)(nil), "go.micro.srv.rack.Response")
	proto.RegisterType((*RackIDReq)(nil), "go.micro.srv.rack.RackIDReq")
	proto.RegisterType((*CellIDReq)(nil), "go.micro.srv.rack.CellIDReq")
	proto.RegisterType((*UpdateRackReq)(nil), "go.micro.srv.rack.UpdateRackReq")
	proto.RegisterType((*GraphqlQuery)(nil), "go.micro.srv.rack.GraphqlQuery")
	proto.RegisterType((*GraphqlRacks)(nil), "go.micro.srv.rack.GraphqlRacks")
	proto.RegisterType((*Query)(nil), "go.micro.srv.rack.Query")
	proto.RegisterType((*Racks)(nil), "go.micro.srv.rack.Racks")
	proto.RegisterType((*TypeReq)(nil), "go.micro.srv.rack.TypeReq")
	proto.RegisterType((*LayerNumsReq)(nil), "go.micro.srv.rack.LayerNumsReq")
	proto.RegisterType((*RackIDsReq)(nil), "go.micro.srv.rack.RackIDsReq")
	proto.RegisterType((*CellsReq)(nil), "go.micro.srv.rack.CellsReq")
	proto.RegisterType((*CellIDsReq)(nil), "go.micro.srv.rack.CellIDsReq")
	proto.RegisterType((*RacklotReq)(nil), "go.micro.srv.rack.RacklotReq")
	proto.RegisterType((*MaterialReq)(nil), "go.micro.srv.rack.MaterialReq")
	proto.RegisterType((*Parameter)(nil), "go.micro.srv.rack.Parameter")
}

func init() { proto.RegisterFile("proto/rack/rack.proto", fileDescriptor_80f24b60e0ed6c04) }

var fileDescriptor_80f24b60e0ed6c04 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0x16, 0x10, 0x02, 0x1c, 0x42, 0xb4, 0x3b, 0xda, 0x90, 0x09, 0x01, 0x96, 0x5a, 0x55, 0x85,
	0x2a, 0x85, 0x95, 0xb2, 0xf7, 0xa9, 0x36, 0xa1, 0xa2, 0x74, 0xbb, 0xdd, 0x5d, 0xa7, 0xe9, 0x5d,
	0x55, 0x39, 0xf6, 0x04, 0x46, 0x31, 0xb6, 0xe3, 0x19, 0x52, 0xf1, 0x0e, 0x7d, 0x86, 0x5e, 0xf6,
	0x01, 0x7a, 0xd9, 0x07, 0xe8, 0x73, 0x55, 0xf3, 0xe3, 0x1f, 0x82, 0x4d, 0xd8, 0x90, 0x9b, 0x68,
	0xce, 0x99, 0x33, 0x9f, 0xe7, 0x7c, 0xdf, 0x39, 0x67, 0x02, 0x1c, 0x04, 0xa1, 0xcf, 0xfd, 0x37,
	0xa1, 0x65, 0xdf, 0xca, 0x3f, 0x03, 0x69, 0xa3, 0x97, 0x13, 0x7f, 0x30, 0xa3, 0x76, 0xe8, 0x0f,
	0x58, 0x78, 0x3f, 0x10, 0x1b, 0xc6, 0x00, 0xaa, 0xa6, 0x65, 0xdf, 0xfe, 0xb2, 0x08, 0x08, 0xda,
	0x87, 0x22, 0x75, 0x70, 0xa1, 0x57, 0xe8, 0x37, 0xcc, 0x22, 0x75, 0x10, 0x82, 0x1d, 0xcf, 0x9a,
	0x11, 0x5c, 0xec, 0x15, 0xfa, 0x35, 0x53, 0xae, 0x8d, 0x7f, 0x8b, 0xb0, 0x73, 0x41, 0x5c, 0x57,
	0x07, 0x1f, 0xc4, 0xc1, 0x2f, 0xa0, 0xc4, 0xad, 0x09, 0x6e, 0xca, 0x58, 0xb1, 0x8c, 0x8f, 0x1f,
	0x26, 0xc7, 0x51, 0x13, 0x76, 0xc5, 0x67, 0xc7, 0x43, 0x8c, 0xe5, 0x49, 0x6d, 0x09, 0xbf, 0x4b,
	0xbc, 0x09, 0x9f, 0xe2, 0xa3, 0x5e, 0xa1, 0x5f, 0x36, 0xb5, 0x85, 0x5e, 0x41, 0xf9, 0x0f, 0xea,
	0xf0, 0x29, 0x6e, 0x49, 0xb7, 0x32, 0x44, 0xf4, 0x94, 0xd0, 0xc9, 0x94, 0xe3, 0x63, 0x15, 0xad,
	0x2c, 0x11, 0xed, 0x5a, 0x0b, 0x12, 0xe2, 0xb6, 0x8a, 0x96, 0x06, 0x6a, 0x41, 0xd5, 0x26, 0xae,
	0x7b, 0xe1, 0x3b, 0x04, 0x77, 0xe4, 0x46, 0x6c, 0x23, 0x0c, 0x15, 0xca, 0x7e, 0xb5, 0x5c, 0xea,
	0xe0, 0x6e, 0xaf, 0xd0, 0xaf, 0x9a, 0x91, 0x89, 0xba, 0x00, 0x33, 0x8b, 0x93, 0x90, 0x5a, 0xee,
	0x78, 0x88, 0x5f, 0xcb, 0xdb, 0xa6, 0x3c, 0x22, 0x3b, 0xbe, 0x08, 0x08, 0xee, 0xc9, 0x1d, 0xb9,
	0x16, 0x67, 0x28, 0xfb, 0x68, 0xdb, 0xf3, 0x80, 0x12, 0x07, 0x7f, 0x25, 0x01, 0x53, 0x1e, 0xe3,
	0xaf, 0x12, 0xec, 0x08, 0xb6, 0x35, 0x79, 0xaf, 0x56, 0x98, 0xee, 0xa6, 0xa8, 0x7a, 0xa3, 0x3f,
	0x20, 0x28, 0xae, 0x9f, 0x1e, 0x0f, 0x56, 0xb4, 0x1b, 0x44, 0xc2, 0xe9, 0xaf, 0xa7, 0x72, 0x69,
	0x2e, 0xe7, 0x92, 0xb0, 0x7b, 0x98, 0xcd, 0x2e, 0xce, 0x66, 0xf7, 0x68, 0x89, 0x5d, 0x0c, 0x15,
	0xf1, 0x59, 0xd7, 0xe7, 0x5a, 0x8d, 0xc8, 0x94, 0xf8, 0x82, 0x6a, 0x16, 0xe9, 0xa1, 0x2c, 0xe1,
	0x67, 0xdc, 0xe2, 0x73, 0x26, 0xf9, 0x2b, 0x9b, 0xda, 0x42, 0xdf, 0xc0, 0x7e, 0x40, 0xed, 0x5b,
	0xea, 0x4d, 0x2e, 0xe7, 0xe1, 0x8d, 0x65, 0x2b, 0x16, 0xcb, 0xe6, 0x03, 0x2f, 0xea, 0x41, 0xdd,
	0x21, 0xcc, 0x0e, 0x69, 0xc0, 0xa9, 0xef, 0x49, 0x55, 0x6b, 0x66, 0xda, 0x85, 0x4e, 0xa0, 0x2c,
	0xb4, 0x64, 0xb8, 0xd3, 0x2b, 0xf5, 0xeb, 0xa7, 0x87, 0x19, 0x2c, 0x89, 0x6a, 0x35, 0x55, 0xd4,
	0xa3, 0x02, 0x01, 0x54, 0x4d, 0xc2, 0x02, 0xdf, 0x63, 0xc4, 0x38, 0x86, 0x9a, 0x29, 0x8b, 0xd3,
	0x24, 0x77, 0x0f, 0x5b, 0x43, 0x6c, 0x0a, 0xdc, 0xec, 0xcd, 0xbf, 0x8b, 0xd0, 0xb8, 0x0a, 0x1c,
	0x8b, 0x13, 0x01, 0x90, 0x44, 0xac, 0xea, 0x7d, 0x90, 0xa1, 0x77, 0xf3, 0x09, 0x7a, 0x1f, 0xe6,
	0xe9, 0x8d, 0xb3, 0xf5, 0x3e, 0xca, 0xd6, 0xbb, 0xb5, 0xa4, 0x77, 0x9e, 0xaa, 0xab, 0xea, 0xb5,
	0x37, 0x51, 0xaf, 0xb3, 0xa2, 0x9e, 0xf1, 0x35, 0xec, 0x8d, 0x42, 0x2b, 0x98, 0xde, 0xb9, 0x9f,
	0xe7, 0x24, 0x5c, 0x88, 0xfb, 0xdd, 0x89, 0x85, 0xe4, 0xb2, 0x66, 0x2a, 0xc3, 0xf8, 0x36, 0x8e,
	0x12, 0x04, 0x30, 0xd1, 0xcf, 0xa1, 0x16, 0x49, 0x07, 0xc6, 0xb6, 0xf1, 0x5f, 0x01, 0xca, 0x31,
	0x96, 0x4b, 0x67, 0x94, 0x6b, 0x5d, 0x94, 0x21, 0x72, 0xf2, 0x6f, 0x6e, 0x18, 0xe1, 0x72, 0xa8,
	0x35, 0x4c, 0x6d, 0x09, 0x41, 0x02, 0x6b, 0x42, 0x70, 0x49, 0x75, 0xb3, 0x58, 0xa3, 0x23, 0xa8,
	0x06, 0x24, 0xfc, 0x5d, 0xfa, 0x77, 0xa4, 0xbf, 0x12, 0x90, 0xf0, 0x93, 0xd8, 0xea, 0x41, 0x5d,
	0xde, 0xed, 0x92, 0x87, 0xd4, 0x9b, 0xe0, 0xb2, 0x4a, 0x2d, 0xe5, 0x42, 0x67, 0x3a, 0xe2, 0x93,
	0x15, 0x5a, 0x33, 0x86, 0x77, 0x65, 0x79, 0xb6, 0x33, 0x44, 0x95, 0x01, 0x84, 0x93, 0xd0, 0x4c,
	0x1f, 0x30, 0xfe, 0x2c, 0x40, 0x59, 0xa5, 0x7b, 0x02, 0x65, 0x11, 0xc8, 0x70, 0x21, 0xb7, 0xc4,
	0x65, 0x99, 0xa9, 0x28, 0x91, 0x21, 0xf7, 0xb9, 0xe5, 0x32, 0x7d, 0x67, 0x6d, 0x89, 0xd2, 0x97,
	0x2b, 0x91, 0x0e, 0xd3, 0xd9, 0xa7, 0x3c, 0xa8, 0x0d, 0x35, 0x7b, 0x1e, 0x86, 0x6a, 0x5b, 0xd1,
	0x90, 0x38, 0x8c, 0x13, 0xa8, 0xc8, 0xca, 0x5b, 0xad, 0xf6, 0x78, 0x10, 0x16, 0x93, 0x41, 0x68,
	0x74, 0x61, 0xef, 0x27, 0x51, 0x2c, 0x3f, 0xcf, 0x67, 0x2c, 0xab, 0x43, 0xba, 0x00, 0xaa, 0xb7,
	0xe4, 0xee, 0x0b, 0x28, 0x51, 0x47, 0xe5, 0xd7, 0x30, 0xc5, 0xd2, 0xf8, 0x0c, 0x55, 0xd1, 0x5e,
	0x72, 0x37, 0x79, 0x32, 0x0a, 0x4b, 0x4f, 0x46, 0xdc, 0xfa, 0xc5, 0x4d, 0x5a, 0xdf, 0x38, 0x03,
	0x50, 0x1d, 0xbb, 0x16, 0x14, 0x43, 0xc5, 0x56, 0x51, 0x12, 0xb6, 0x61, 0x46, 0xa6, 0x71, 0xae,
	0xae, 0xec, 0xfa, 0x7c, 0xdd, 0xf9, 0x36, 0xd4, 0xf4, 0x50, 0x1c, 0x0f, 0x35, 0x23, 0x89, 0xc3,
	0xf8, 0x0d, 0xea, 0x1f, 0xf4, 0x0b, 0xb2, 0x0e, 0xa4, 0x09, 0xbb, 0xea, 0xab, 0x51, 0x91, 0x2a,
	0xeb, 0xc1, 0x93, 0x54, 0x7a, 0xf8, 0x24, 0x19, 0x6f, 0xa1, 0x16, 0x57, 0x93, 0x20, 0xf5, 0x96,
	0x44, 0x9d, 0x24, 0x96, 0xa2, 0x23, 0xee, 0x2d, 0x77, 0x1e, 0xbd, 0xe7, 0xca, 0x38, 0xfd, 0xa7,
	0x01, 0x75, 0x91, 0xd8, 0x25, 0x09, 0xef, 0xa9, 0x4d, 0xd0, 0x77, 0x50, 0x79, 0xe7, 0x38, 0xf2,
	0x95, 0xca, 0x2b, 0xb5, 0x56, 0xe6, 0x70, 0xd2, 0x2d, 0x88, 0x46, 0x00, 0x43, 0xe2, 0x12, 0x35,
	0xfc, 0x50, 0x3b, 0x07, 0x43, 0x4e, 0xce, 0xf5, 0x40, 0xef, 0x01, 0x92, 0x29, 0x8a, 0x7a, 0x19,
	0xa1, 0x4b, 0x43, 0x76, 0x3d, 0xd8, 0x05, 0xc0, 0x88, 0xf0, 0x8f, 0xde, 0x26, 0xb7, 0xca, 0xcb,
	0x1b, 0x9d, 0x41, 0x75, 0x44, 0xb8, 0x6a, 0x4b, 0x9c, 0x11, 0x24, 0x27, 0x4f, 0x0b, 0xe7, 0x1c,
	0x67, 0xe8, 0x0a, 0x5e, 0x46, 0xe7, 0xcf, 0x17, 0x7a, 0xa6, 0xa1, 0xd7, 0x19, 0xe1, 0xe9, 0xa9,
	0xd8, 0x5a, 0x13, 0xa0, 0x60, 0x87, 0xb0, 0x9f, 0xc0, 0xca, 0xff, 0xe4, 0x9e, 0x72, 0xb9, 0x31,
	0xd4, 0xbf, 0xf7, 0xac, 0x6b, 0x97, 0x28, 0xb3, 0x93, 0x4b, 0x11, 0x7b, 0x94, 0xec, 0x1f, 0x61,
	0x6f, 0x48, 0xd9, 0xf3, 0x60, 0x8d, 0x00, 0x92, 0x6b, 0x6d, 0x53, 0x4e, 0x3f, 0x40, 0x3d, 0x75,
	0xa9, 0x6d, 0x90, 0xc6, 0x50, 0x3f, 0xa7, 0x9e, 0xa3, 0xc7, 0x41, 0x6e, 0x76, 0x6a, 0x54, 0x3c,
	0x56, 0xe3, 0x8d, 0x2b, 0xef, 0xfa, 0x99, 0xc0, 0x86, 0x50, 0x7d, 0xe7, 0x38, 0x72, 0x70, 0xa2,
	0xe3, 0x9c, 0x71, 0xc8, 0x36, 0xc9, 0xce, 0x24, 0x33, 0xff, 0x9e, 0x28, 0xa0, 0x4e, 0x0e, 0xd0,
	0x26, 0xda, 0xc5, 0x25, 0xb5, 0x3d, 0x54, 0x52, 0x52, 0xdb, 0x63, 0xbd, 0x87, 0x3d, 0xa1, 0x5f,
	0x34, 0x8a, 0x51, 0x37, 0x23, 0x38, 0x35, 0xa7, 0xd7, 0x83, 0x7d, 0x80, 0x7d, 0xa5, 0xe0, 0xf3,
	0xc0, 0x8d, 0x00, 0xe4, 0x7f, 0xa3, 0x8b, 0x67, 0x28, 0x77, 0x93, 0xb8, 0xc4, 0x62, 0x5b, 0x97,
	0x7b, 0x7c, 0x25, 0xf9, 0xbb, 0xaf, 0x9d, 0x4b, 0xfc, 0x17, 0x5c, 0x69, 0x4b, 0xa4, 0xeb, 0x5d,
	0xf9, 0x7b, 0xf6, 0xed, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xee, 0x41, 0x01, 0xe8, 0x0e,
	0x00, 0x00,
}
