// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/material/material.proto

package go_micro_srv_material

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MaterialService service

func NewMaterialServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MaterialService service

type MaterialService interface {
	// 添加物料类型
	AddMaterialType(ctx context.Context, in *MaterialType, opts ...client.CallOption) (*Response, error)
	// 移除物料类型
	DeleteMaterialType(ctx context.Context, in *MaterialTypeIDReq, opts ...client.CallOption) (*Response, error)
	// 更新物料类型
	UpdateMaterialType(ctx context.Context, in *UpdateMaterialTypeReq, opts ...client.CallOption) (*Response, error)
	// 根据查询条件获取物料类型列表
	GetMaterialTypes(ctx context.Context, in *MaterialTypeQuery, opts ...client.CallOption) (*MaterialTypesResp, error)
	// 根据ID获取指定的物料类型
	GetMaterialType(ctx context.Context, in *MaterialTypeIDReq, opts ...client.CallOption) (*MaterialType, error)
	// 获取出入库记录
	GetRecord(ctx context.Context, in *RecordQuery, opts ...client.CallOption) (*MaterialRecords, error)
	// 添加物料
	AddMaterial(ctx context.Context, in *Material, opts ...client.CallOption) (*Response, error)
	// 移除物料
	DeleteMaterial(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Response, error)
	// 更新物料
	UpdateMaterial(ctx context.Context, in *UpdateMaterialReq, opts ...client.CallOption) (*Response, error)
	// 根据查询条件获取物料信息
	GetMaterials(ctx context.Context, in *MaterialQuery, opts ...client.CallOption) (*MaterialsResp, error)
	// 根据ID获取指定的物料类型
	GetMaterial(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Material, error)
	BatchAddMaterials(ctx context.Context, in *Materials, opts ...client.CallOption) (*Response, error)
	BatchDeleteMaterials(ctx context.Context, in *MaterialIDsReq, opts ...client.CallOption) (*Response, error)
	// 添加物料
	BindCell(ctx context.Context, in *CellReq, opts ...client.CallOption) (*Response, error)
	// 移除物料
	UnbindCell(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Response, error)
	// rpc AddMaterialProperties(Material) returns(Response);
	// rpc DeleteAddMaterialProperties()
	//获取服务日志等级
	GetLogLevel(ctx context.Context, in *LogLevelRequest, opts ...client.CallOption) (*Loglevel, error)
	//设置服务日志等级
	SetLogLevel(ctx context.Context, in *Loglevel, opts ...client.CallOption) (*LogResponse, error)
}

type materialService struct {
	c    client.Client
	name string
}

func NewMaterialService(name string, c client.Client) MaterialService {
	return &materialService{
		c:    c,
		name: name,
	}
}

func (c *materialService) AddMaterialType(ctx context.Context, in *MaterialType, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.AddMaterialType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) DeleteMaterialType(ctx context.Context, in *MaterialTypeIDReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.DeleteMaterialType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) UpdateMaterialType(ctx context.Context, in *UpdateMaterialTypeReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.UpdateMaterialType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetMaterialTypes(ctx context.Context, in *MaterialTypeQuery, opts ...client.CallOption) (*MaterialTypesResp, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetMaterialTypes", in)
	out := new(MaterialTypesResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetMaterialType(ctx context.Context, in *MaterialTypeIDReq, opts ...client.CallOption) (*MaterialType, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetMaterialType", in)
	out := new(MaterialType)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetRecord(ctx context.Context, in *RecordQuery, opts ...client.CallOption) (*MaterialRecords, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetRecord", in)
	out := new(MaterialRecords)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) AddMaterial(ctx context.Context, in *Material, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.AddMaterial", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) DeleteMaterial(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.DeleteMaterial", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) UpdateMaterial(ctx context.Context, in *UpdateMaterialReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.UpdateMaterial", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetMaterials(ctx context.Context, in *MaterialQuery, opts ...client.CallOption) (*MaterialsResp, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetMaterials", in)
	out := new(MaterialsResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetMaterial(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Material, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetMaterial", in)
	out := new(Material)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) BatchAddMaterials(ctx context.Context, in *Materials, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.BatchAddMaterials", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) BatchDeleteMaterials(ctx context.Context, in *MaterialIDsReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.BatchDeleteMaterials", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) BindCell(ctx context.Context, in *CellReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.BindCell", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) UnbindCell(ctx context.Context, in *MaterialIDReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MaterialService.UnbindCell", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) GetLogLevel(ctx context.Context, in *LogLevelRequest, opts ...client.CallOption) (*Loglevel, error) {
	req := c.c.NewRequest(c.name, "MaterialService.GetLogLevel", in)
	out := new(Loglevel)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *materialService) SetLogLevel(ctx context.Context, in *Loglevel, opts ...client.CallOption) (*LogResponse, error) {
	req := c.c.NewRequest(c.name, "MaterialService.SetLogLevel", in)
	out := new(LogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MaterialService service

type MaterialServiceHandler interface {
	// 添加物料类型
	AddMaterialType(context.Context, *MaterialType, *Response) error
	// 移除物料类型
	DeleteMaterialType(context.Context, *MaterialTypeIDReq, *Response) error
	// 更新物料类型
	UpdateMaterialType(context.Context, *UpdateMaterialTypeReq, *Response) error
	// 根据查询条件获取物料类型列表
	GetMaterialTypes(context.Context, *MaterialTypeQuery, *MaterialTypesResp) error
	// 根据ID获取指定的物料类型
	GetMaterialType(context.Context, *MaterialTypeIDReq, *MaterialType) error
	// 获取出入库记录
	GetRecord(context.Context, *RecordQuery, *MaterialRecords) error
	// 添加物料
	AddMaterial(context.Context, *Material, *Response) error
	// 移除物料
	DeleteMaterial(context.Context, *MaterialIDReq, *Response) error
	// 更新物料
	UpdateMaterial(context.Context, *UpdateMaterialReq, *Response) error
	// 根据查询条件获取物料信息
	GetMaterials(context.Context, *MaterialQuery, *MaterialsResp) error
	// 根据ID获取指定的物料类型
	GetMaterial(context.Context, *MaterialIDReq, *Material) error
	BatchAddMaterials(context.Context, *Materials, *Response) error
	BatchDeleteMaterials(context.Context, *MaterialIDsReq, *Response) error
	// 添加物料
	BindCell(context.Context, *CellReq, *Response) error
	// 移除物料
	UnbindCell(context.Context, *MaterialIDReq, *Response) error
	// rpc AddMaterialProperties(Material) returns(Response);
	// rpc DeleteAddMaterialProperties()
	//获取服务日志等级
	GetLogLevel(context.Context, *LogLevelRequest, *Loglevel) error
	//设置服务日志等级
	SetLogLevel(context.Context, *Loglevel, *LogResponse) error
}

func RegisterMaterialServiceHandler(s server.Server, hdlr MaterialServiceHandler, opts ...server.HandlerOption) error {
	type materialService interface {
		AddMaterialType(ctx context.Context, in *MaterialType, out *Response) error
		DeleteMaterialType(ctx context.Context, in *MaterialTypeIDReq, out *Response) error
		UpdateMaterialType(ctx context.Context, in *UpdateMaterialTypeReq, out *Response) error
		GetMaterialTypes(ctx context.Context, in *MaterialTypeQuery, out *MaterialTypesResp) error
		GetMaterialType(ctx context.Context, in *MaterialTypeIDReq, out *MaterialType) error
		GetRecord(ctx context.Context, in *RecordQuery, out *MaterialRecords) error
		AddMaterial(ctx context.Context, in *Material, out *Response) error
		DeleteMaterial(ctx context.Context, in *MaterialIDReq, out *Response) error
		UpdateMaterial(ctx context.Context, in *UpdateMaterialReq, out *Response) error
		GetMaterials(ctx context.Context, in *MaterialQuery, out *MaterialsResp) error
		GetMaterial(ctx context.Context, in *MaterialIDReq, out *Material) error
		BatchAddMaterials(ctx context.Context, in *Materials, out *Response) error
		BatchDeleteMaterials(ctx context.Context, in *MaterialIDsReq, out *Response) error
		BindCell(ctx context.Context, in *CellReq, out *Response) error
		UnbindCell(ctx context.Context, in *MaterialIDReq, out *Response) error
		GetLogLevel(ctx context.Context, in *LogLevelRequest, out *Loglevel) error
		SetLogLevel(ctx context.Context, in *Loglevel, out *LogResponse) error
	}
	type MaterialService struct {
		materialService
	}
	h := &materialServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MaterialService{h}, opts...))
}

type materialServiceHandler struct {
	MaterialServiceHandler
}

func (h *materialServiceHandler) AddMaterialType(ctx context.Context, in *MaterialType, out *Response) error {
	return h.MaterialServiceHandler.AddMaterialType(ctx, in, out)
}

func (h *materialServiceHandler) DeleteMaterialType(ctx context.Context, in *MaterialTypeIDReq, out *Response) error {
	return h.MaterialServiceHandler.DeleteMaterialType(ctx, in, out)
}

func (h *materialServiceHandler) UpdateMaterialType(ctx context.Context, in *UpdateMaterialTypeReq, out *Response) error {
	return h.MaterialServiceHandler.UpdateMaterialType(ctx, in, out)
}

func (h *materialServiceHandler) GetMaterialTypes(ctx context.Context, in *MaterialTypeQuery, out *MaterialTypesResp) error {
	return h.MaterialServiceHandler.GetMaterialTypes(ctx, in, out)
}

func (h *materialServiceHandler) GetMaterialType(ctx context.Context, in *MaterialTypeIDReq, out *MaterialType) error {
	return h.MaterialServiceHandler.GetMaterialType(ctx, in, out)
}

func (h *materialServiceHandler) GetRecord(ctx context.Context, in *RecordQuery, out *MaterialRecords) error {
	return h.MaterialServiceHandler.GetRecord(ctx, in, out)
}

func (h *materialServiceHandler) AddMaterial(ctx context.Context, in *Material, out *Response) error {
	return h.MaterialServiceHandler.AddMaterial(ctx, in, out)
}

func (h *materialServiceHandler) DeleteMaterial(ctx context.Context, in *MaterialIDReq, out *Response) error {
	return h.MaterialServiceHandler.DeleteMaterial(ctx, in, out)
}

func (h *materialServiceHandler) UpdateMaterial(ctx context.Context, in *UpdateMaterialReq, out *Response) error {
	return h.MaterialServiceHandler.UpdateMaterial(ctx, in, out)
}

func (h *materialServiceHandler) GetMaterials(ctx context.Context, in *MaterialQuery, out *MaterialsResp) error {
	return h.MaterialServiceHandler.GetMaterials(ctx, in, out)
}

func (h *materialServiceHandler) GetMaterial(ctx context.Context, in *MaterialIDReq, out *Material) error {
	return h.MaterialServiceHandler.GetMaterial(ctx, in, out)
}

func (h *materialServiceHandler) BatchAddMaterials(ctx context.Context, in *Materials, out *Response) error {
	return h.MaterialServiceHandler.BatchAddMaterials(ctx, in, out)
}

func (h *materialServiceHandler) BatchDeleteMaterials(ctx context.Context, in *MaterialIDsReq, out *Response) error {
	return h.MaterialServiceHandler.BatchDeleteMaterials(ctx, in, out)
}

func (h *materialServiceHandler) BindCell(ctx context.Context, in *CellReq, out *Response) error {
	return h.MaterialServiceHandler.BindCell(ctx, in, out)
}

func (h *materialServiceHandler) UnbindCell(ctx context.Context, in *MaterialIDReq, out *Response) error {
	return h.MaterialServiceHandler.UnbindCell(ctx, in, out)
}

func (h *materialServiceHandler) GetLogLevel(ctx context.Context, in *LogLevelRequest, out *Loglevel) error {
	return h.MaterialServiceHandler.GetLogLevel(ctx, in, out)
}

func (h *materialServiceHandler) SetLogLevel(ctx context.Context, in *Loglevel, out *LogResponse) error {
	return h.MaterialServiceHandler.SetLogLevel(ctx, in, out)
}
