// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/log/log.proto

package go_micro_srv_log

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogConfig struct {
	LogKeepDays          uint32   `protobuf:"varint,1,opt,name=logKeepDays,proto3" json:"logKeepDays,omitempty"`
	LogLevel             uint32   `protobuf:"varint,2,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogConfig) Reset()         { *m = LogConfig{} }
func (m *LogConfig) String() string { return proto.CompactTextString(m) }
func (*LogConfig) ProtoMessage()    {}
func (*LogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{0}
}

func (m *LogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogConfig.Unmarshal(m, b)
}
func (m *LogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogConfig.Marshal(b, m, deterministic)
}
func (m *LogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogConfig.Merge(m, src)
}
func (m *LogConfig) XXX_Size() int {
	return xxx_messageInfo_LogConfig.Size(m)
}
func (m *LogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogConfig proto.InternalMessageInfo

func (m *LogConfig) GetLogKeepDays() uint32 {
	if m != nil {
		return m.LogKeepDays
	}
	return 0
}

func (m *LogConfig) GetLogLevel() uint32 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

type LogContent struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	FuncName             string   `protobuf:"bytes,3,opt,name=funcName,proto3" json:"funcName,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Line                 uint32   `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	Service              string   `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	IpAddr               string   `protobuf:"bytes,7,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	Msg                  string   `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	TaskID               uint32   `protobuf:"varint,9,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogContent) Reset()         { *m = LogContent{} }
func (m *LogContent) String() string { return proto.CompactTextString(m) }
func (*LogContent) ProtoMessage()    {}
func (*LogContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{1}
}

func (m *LogContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogContent.Unmarshal(m, b)
}
func (m *LogContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogContent.Marshal(b, m, deterministic)
}
func (m *LogContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogContent.Merge(m, src)
}
func (m *LogContent) XXX_Size() int {
	return xxx_messageInfo_LogContent.Size(m)
}
func (m *LogContent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogContent.DiscardUnknown(m)
}

var xxx_messageInfo_LogContent proto.InternalMessageInfo

func (m *LogContent) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *LogContent) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *LogContent) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *LogContent) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *LogContent) GetLine() uint32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *LogContent) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *LogContent) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

func (m *LogContent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogContent) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Query struct {
	Page                 uint32     `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32     `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Filter               *LogFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{4}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Query) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Query) GetFilter() *LogFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type LogFilter struct {
	And                  []*LogFilter `protobuf:"bytes,1,rep,name=and,proto3" json:"and,omitempty"`
	Or                   []*LogFilter `protobuf:"bytes,2,rep,name=or,proto3" json:"or,omitempty"`
	FromTime             string       `protobuf:"bytes,3,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime               string       `protobuf:"bytes,4,opt,name=toTime,proto3" json:"toTime,omitempty"`
	LevelIn              []string     `protobuf:"bytes,5,rep,name=levelIn,proto3" json:"levelIn,omitempty"`
	FuncIn               []string     `protobuf:"bytes,6,rep,name=funcIn,proto3" json:"funcIn,omitempty"`
	FileIn               []string     `protobuf:"bytes,7,rep,name=fileIn,proto3" json:"fileIn,omitempty"`
	LineIn               []uint32     `protobuf:"varint,8,rep,packed,name=lineIn,proto3" json:"lineIn,omitempty"`
	ServiceIn            []string     `protobuf:"bytes,9,rep,name=serviceIn,proto3" json:"serviceIn,omitempty"`
	IpIn                 []string     `protobuf:"bytes,10,rep,name=ipIn,proto3" json:"ipIn,omitempty"`
	MsgIn                []string     `protobuf:"bytes,11,rep,name=msgIn,proto3" json:"msgIn,omitempty"`
	TaskID               uint32       `protobuf:"varint,12,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogFilter) Reset()         { *m = LogFilter{} }
func (m *LogFilter) String() string { return proto.CompactTextString(m) }
func (*LogFilter) ProtoMessage()    {}
func (*LogFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{5}
}

func (m *LogFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogFilter.Unmarshal(m, b)
}
func (m *LogFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogFilter.Marshal(b, m, deterministic)
}
func (m *LogFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogFilter.Merge(m, src)
}
func (m *LogFilter) XXX_Size() int {
	return xxx_messageInfo_LogFilter.Size(m)
}
func (m *LogFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_LogFilter.DiscardUnknown(m)
}

var xxx_messageInfo_LogFilter proto.InternalMessageInfo

func (m *LogFilter) GetAnd() []*LogFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *LogFilter) GetOr() []*LogFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *LogFilter) GetFromTime() string {
	if m != nil {
		return m.FromTime
	}
	return ""
}

func (m *LogFilter) GetToTime() string {
	if m != nil {
		return m.ToTime
	}
	return ""
}

func (m *LogFilter) GetLevelIn() []string {
	if m != nil {
		return m.LevelIn
	}
	return nil
}

func (m *LogFilter) GetFuncIn() []string {
	if m != nil {
		return m.FuncIn
	}
	return nil
}

func (m *LogFilter) GetFileIn() []string {
	if m != nil {
		return m.FileIn
	}
	return nil
}

func (m *LogFilter) GetLineIn() []uint32 {
	if m != nil {
		return m.LineIn
	}
	return nil
}

func (m *LogFilter) GetServiceIn() []string {
	if m != nil {
		return m.ServiceIn
	}
	return nil
}

func (m *LogFilter) GetIpIn() []string {
	if m != nil {
		return m.IpIn
	}
	return nil
}

func (m *LogFilter) GetMsgIn() []string {
	if m != nil {
		return m.MsgIn
	}
	return nil
}

func (m *LogFilter) GetTaskID() uint32 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

type LogContents struct {
	LogContents          []*LogContent `protobuf:"bytes,1,rep,name=logContents,proto3" json:"logContents,omitempty"`
	TotalCount           uint32        `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LogContents) Reset()         { *m = LogContents{} }
func (m *LogContents) String() string { return proto.CompactTextString(m) }
func (*LogContents) ProtoMessage()    {}
func (*LogContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_c672f68bc74af5b1, []int{6}
}

func (m *LogContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogContents.Unmarshal(m, b)
}
func (m *LogContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogContents.Marshal(b, m, deterministic)
}
func (m *LogContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogContents.Merge(m, src)
}
func (m *LogContents) XXX_Size() int {
	return xxx_messageInfo_LogContents.Size(m)
}
func (m *LogContents) XXX_DiscardUnknown() {
	xxx_messageInfo_LogContents.DiscardUnknown(m)
}

var xxx_messageInfo_LogContents proto.InternalMessageInfo

func (m *LogContents) GetLogContents() []*LogContent {
	if m != nil {
		return m.LogContents
	}
	return nil
}

func (m *LogContents) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*LogConfig)(nil), "go.micro.srv.log.LogConfig")
	proto.RegisterType((*LogContent)(nil), "go.micro.srv.log.LogContent")
	proto.RegisterType((*Request)(nil), "go.micro.srv.log.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.log.Response")
	proto.RegisterType((*Query)(nil), "go.micro.srv.log.Query")
	proto.RegisterType((*LogFilter)(nil), "go.micro.srv.log.LogFilter")
	proto.RegisterType((*LogContents)(nil), "go.micro.srv.log.LogContents")
}

func init() { proto.RegisterFile("proto/log/log.proto", fileDescriptor_c672f68bc74af5b1) }

var fileDescriptor_c672f68bc74af5b1 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0x26, 0x77, 0xcd, 0x8f, 0x9b, 0x54, 0x28, 0xab, 0xe8, 0x9a, 0x56, 0x09, 0xf7, 0x24, 0x88,
	0x27, 0xb4, 0xef, 0x42, 0x49, 0x30, 0x1c, 0x06, 0xd1, 0xa3, 0xe2, 0xf3, 0x99, 0x4c, 0x96, 0xd5,
	0xbb, 0xdd, 0x73, 0x77, 0x13, 0xe8, 0xff, 0xe2, 0xbf, 0xa6, 0x7f, 0x8b, 0xec, 0xdc, 0x26, 0x8d,
	0xb6, 0x4d, 0x1f, 0x02, 0xf3, 0x7d, 0xdf, 0xcc, 0xec, 0xee, 0x7c, 0x73, 0x81, 0xc7, 0x8d, 0xd1,
	0x4e, 0xbf, 0xad, 0xb4, 0xf0, 0xbf, 0x8c, 0x10, 0x3b, 0x11, 0x3a, 0xab, 0xe5, 0xc2, 0xe8, 0xcc,
	0x9a, 0x4d, 0x56, 0x69, 0x91, 0xe6, 0x90, 0xcc, 0xb5, 0x98, 0x68, 0xb5, 0x92, 0x82, 0x8d, 0x61,
	0x58, 0x69, 0xf1, 0x01, 0xb1, 0x99, 0x96, 0xd7, 0x96, 0x77, 0xc6, 0x9d, 0x57, 0x8f, 0x8a, 0x7d,
	0x8a, 0x8d, 0x60, 0x50, 0x69, 0x31, 0xc7, 0x0d, 0x56, 0x3c, 0x22, 0x79, 0x87, 0xd3, 0x3f, 0x1d,
	0x80, 0xb6, 0x97, 0x43, 0xe5, 0x18, 0x83, 0x23, 0x27, 0x6b, 0xa4, 0x2e, 0x49, 0x41, 0x31, 0x7b,
	0x02, 0xdd, 0x6a, 0x57, 0x9b, 0x14, 0x2d, 0xf0, 0x4d, 0x57, 0x6b, 0xb5, 0xf8, 0x58, 0xd6, 0xc8,
	0x63, 0x12, 0x76, 0x98, 0x34, 0x59, 0x21, 0x69, 0x47, 0x41, 0x0b, 0xd8, 0x9f, 0x50, 0x49, 0x85,
	0xbc, 0x4b, 0x17, 0xa1, 0x98, 0x71, 0xe8, 0x5b, 0x34, 0x1b, 0xb9, 0x40, 0xde, 0xa3, 0xf4, 0x2d,
	0x64, 0x4f, 0xa1, 0x27, 0x9b, 0xcb, 0xe5, 0xd2, 0xf0, 0x3e, 0x09, 0x01, 0xb1, 0x13, 0x88, 0x6b,
	0x2b, 0xf8, 0x80, 0x48, 0x1f, 0xfa, 0x4c, 0x57, 0xda, 0x1f, 0xf9, 0x94, 0x27, 0xd4, 0x39, 0xa0,
	0x34, 0x81, 0x7e, 0x81, 0x3f, 0xd7, 0x68, 0x5d, 0x0a, 0x30, 0x28, 0xd0, 0x36, 0x5a, 0x59, 0x4c,
	0xbf, 0x43, 0xf7, 0xf3, 0x1a, 0xcd, 0xb5, 0xbf, 0x4f, 0x53, 0x0a, 0x0c, 0x73, 0xa3, 0xd8, 0xdf,
	0xa7, 0x41, 0xf3, 0xc9, 0xd3, 0xed, 0xbc, 0xb6, 0x90, 0x5d, 0x40, 0x6f, 0x25, 0x2b, 0x87, 0x86,
	0xde, 0x3c, 0x3c, 0x3f, 0xcd, 0xfe, 0x37, 0x27, 0x9b, 0x6b, 0xf1, 0x9e, 0x52, 0x8a, 0x90, 0x9a,
	0xfe, 0x8e, 0xc8, 0xaf, 0x96, 0x65, 0x6f, 0x20, 0x2e, 0xd5, 0x92, 0x77, 0xc6, 0xf1, 0x43, 0xf5,
	0x3e, 0x8f, 0xbd, 0x86, 0x48, 0x1b, 0x1e, 0x3d, 0x9c, 0x1d, 0x69, 0x43, 0x83, 0x37, 0xba, 0xbe,
	0x92, 0x7b, 0xa6, 0x04, 0x4c, 0x03, 0xd2, 0xa4, 0xb4, 0x96, 0x04, 0xe4, 0x1f, 0x4b, 0x8e, 0xe6,
	0x8a, 0x77, 0xc7, 0xb1, 0x1f, 0x7e, 0x80, 0xbe, 0xc2, 0x5b, 0x9a, 0x2b, 0xde, 0x23, 0x21, 0x20,
	0xe2, 0x65, 0x85, 0xb9, 0xe2, 0xfd, 0xc0, 0x13, 0xf2, 0xbc, 0xb7, 0x33, 0x57, 0x7c, 0x30, 0x8e,
	0xbd, 0x05, 0x2d, 0x62, 0x67, 0x90, 0x04, 0x3f, 0x73, 0xc5, 0x13, 0x2a, 0xb9, 0x21, 0xbc, 0x01,
	0xb2, 0xc9, 0x15, 0x07, 0x12, 0x28, 0xf6, 0x2b, 0x57, 0x5b, 0x91, 0x2b, 0x3e, 0x24, 0xb2, 0x05,
	0x7b, 0x16, 0x1f, 0xff, 0x63, 0x71, 0x0d, 0xc3, 0x9b, 0x15, 0xb6, 0xec, 0x1d, 0x7d, 0x10, 0x5b,
	0x18, 0x06, 0x7d, 0x76, 0xe7, 0xe8, 0x42, 0x52, 0xb1, 0x5f, 0xc0, 0x5e, 0x02, 0x5c, 0x69, 0x57,
	0x56, 0x13, 0xbd, 0x56, 0x2e, 0x2c, 0xc0, 0x1e, 0x73, 0xfe, 0x2b, 0x82, 0x78, 0xae, 0x05, 0x9b,
	0xc1, 0xf1, 0x97, 0x66, 0x59, 0x3a, 0x0c, 0x1f, 0xe2, 0xe9, 0x7d, 0x47, 0xac, 0xa4, 0x18, 0x8d,
	0x6e, 0x8b, 0xdb, 0x5d, 0x64, 0x13, 0x48, 0x66, 0xe8, 0x42, 0x97, 0xe7, 0x77, 0x25, 0xd2, 0xfe,
	0x8e, 0x0e, 0x1d, 0xc0, 0x2e, 0xa1, 0x3f, 0x43, 0x37, 0xd7, 0xc2, 0xb2, 0x67, 0xb7, 0xf3, 0x68,
	0xd7, 0x47, 0x2f, 0x0e, 0x0d, 0xc1, 0xb2, 0x29, 0x0c, 0xbe, 0x1a, 0xe9, 0xd0, 0x3f, 0xee, 0xe0,
	0xbc, 0x0e, 0xbd, 0xe6, 0x5b, 0x8f, 0xfe, 0xb5, 0x2e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x2c, 0x6b, 0xb9, 0xcc, 0x04, 0x00, 0x00,
}
